$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1426560830670.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8217efa3d5d4393a67c7e57b9beb497",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2e94a1d155fb42ea9ab683bb371e1856",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":120,
              "y":0},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abe0abbee74d410288e8df60d3fb93f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u178.png"}},
{
          "id":"6e727895cb4b4c57b319fae3a1125930",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":0},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f410293c0741899fa2ba8029d862d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"1c8070cc1ee5442591662f68a34b7e89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":400,
              "y":63},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e6e96e4c8e4b5cad0cad4f7547448d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":400,
                  "y":63},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7f9d9b417a54f32bb9ea95b21745e67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":0},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8a47d6af1e47cc9ed5a9b9638caac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u31.png"}},
{
          "id":"839056828f7d46b8822e104a7c8924d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":134,
              "y":64},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f55d45581f4535b691130a62eccbcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":64},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6297aaa4ddf7471182b4a8a225c3ea09",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":13,
              "y":334.5},
            "size":{
              "width":73,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"750dff276c594eef8e0fe21856fafc14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":13,
                  "y":334.5},
                "size":{
                  "width":73,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"620d999ae40041a4a92757b0791697b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":13,
              "y":312},
            "size":{
              "width":73,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476dc93cff7f4ba99e6b1010fe1649bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":13,
                  "y":312},
                "size":{
                  "width":73,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a423f00daa34f42bac820ff25709c55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":172},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb6e970fcafd49ebb451740ac792dd2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":172},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/论坛/u100.png"}},
{
          "id":"ba259a2f568b48b499db158f0aa65751",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":152,
              "y":208},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7423858580284e6ebf13edacc2923839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":152,
                  "y":208},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b892c953270446eb9e94b4f7ab2e545",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":469},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d18284dda6ca47d79c8850ac2b453006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":469},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/论坛/u100.png"}},
{
          "id":"f67c7c1271ab4b21975efdb0a7d847e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":152,
              "y":505},
            "size":{
              "width":169,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6647426573cc4e408be6af647a95993e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":152,
                  "y":505},
                "size":{
                  "width":169,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a214747194ce4c2980e5b3c3dee0327f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":501},
            "size":{
              "width":20,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667ec1728e3a418d9deb0115b16e1749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":701,
                  "y":501},
                "size":{
                  "width":20,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bca330ef879493b9aa662207677faa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":271},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f736a99fb9e04fbdba2bf66efddc65e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":271},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/论坛/u100.png"}},
{
          "id":"c86074167aa2447d8b693fdb3c760358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":152,
              "y":307},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f9957a0ec7d48a5a059cddcafce80f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":152,
                  "y":307},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf812c9c5bc34c0db4898e14f7612705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":370},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e77e6d10ef1b43c8acde994752c9db2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":370},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/论坛/u100.png"}},
{
          "id":"de8e764e331d4803ba95a4f0b15baf28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":152,
              "y":406},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e0807c71dd74852ae02450ea0456799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":152,
                  "y":406},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2e94a1d155fb42ea9ab683bb371e1856":{
      "scriptId":"u0"},
    "abe0abbee74d410288e8df60d3fb93f5":{
      "scriptId":"u1"},
    "6e727895cb4b4c57b319fae3a1125930":{
      "scriptId":"u2"},
    "72f410293c0741899fa2ba8029d862d8":{
      "scriptId":"u3"},
    "1c8070cc1ee5442591662f68a34b7e89":{
      "scriptId":"u4"},
    "a8e6e96e4c8e4b5cad0cad4f7547448d":{
      "scriptId":"u5"},
    "b7f9d9b417a54f32bb9ea95b21745e67":{
      "scriptId":"u6"},
    "ec8a47d6af1e47cc9ed5a9b9638caac7":{
      "scriptId":"u7"},
    "839056828f7d46b8822e104a7c8924d1":{
      "scriptId":"u8"},
    "22f55d45581f4535b691130a62eccbcd":{
      "scriptId":"u9"},
    "6297aaa4ddf7471182b4a8a225c3ea09":{
      "scriptId":"u10"},
    "750dff276c594eef8e0fe21856fafc14":{
      "scriptId":"u11"},
    "620d999ae40041a4a92757b0791697b6":{
      "scriptId":"u12"},
    "476dc93cff7f4ba99e6b1010fe1649bf":{
      "scriptId":"u13"},
    "3a423f00daa34f42bac820ff25709c55":{
      "scriptId":"u14"},
    "cb6e970fcafd49ebb451740ac792dd2a":{
      "scriptId":"u15"},
    "ba259a2f568b48b499db158f0aa65751":{
      "scriptId":"u16"},
    "7423858580284e6ebf13edacc2923839":{
      "scriptId":"u17"},
    "1b892c953270446eb9e94b4f7ab2e545":{
      "scriptId":"u18"},
    "d18284dda6ca47d79c8850ac2b453006":{
      "scriptId":"u19"},
    "f67c7c1271ab4b21975efdb0a7d847e2":{
      "scriptId":"u20"},
    "6647426573cc4e408be6af647a95993e":{
      "scriptId":"u21"},
    "a214747194ce4c2980e5b3c3dee0327f":{
      "scriptId":"u22"},
    "667ec1728e3a418d9deb0115b16e1749":{
      "scriptId":"u23"},
    "9bca330ef879493b9aa662207677faa4":{
      "scriptId":"u24"},
    "f736a99fb9e04fbdba2bf66efddc65e2":{
      "scriptId":"u25"},
    "c86074167aa2447d8b693fdb3c760358":{
      "scriptId":"u26"},
    "6f9957a0ec7d48a5a059cddcafce80f3":{
      "scriptId":"u27"},
    "cf812c9c5bc34c0db4898e14f7612705":{
      "scriptId":"u28"},
    "e77e6d10ef1b43c8acde994752c9db2a":{
      "scriptId":"u29"},
    "de8e764e331d4803ba95a4f0b15baf28":{
      "scriptId":"u30"},
    "0e0807c71dd74852ae02450ea0456799":{
      "scriptId":"u31"}}});