$axure.loadCurrentPage({
  "url":"严重.html",
  "generationDate":new Date(1431411287972.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dfe237271c6f4c918d3676a40f463093",
    "type":"Axure:Page",
    "name":"严重",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"431372102d96469c9ae42d662ffe3682",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ecaad8a1c1243dabff237b16cc00ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"d1d9d0b0727f46a9a2e13b8ee873df84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae07a8eb370d42c3a8e015343c3f15da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/医生圈/u2.png"}},
{
          "id":"eac3acaa9a194fadbf76c9fbf4616868",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e06cc0581a6f4c48a4e50984164e2e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"74cb0e9250ea4ed7a0a2fe9299b93705",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":282,
              "y":80},
            "size":{
              "width":116,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b79bb0fb3c14771b343eb061d688ae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":282,
                  "y":80},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e780ac1049624bd591dc6253851da108",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":220},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"708e45b4fb1846b39dd53a40176cb989",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":220},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"b8cff7d6209a44c5a5db706c1d4f23a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":236},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dd3d6785af54712ae99afb76cb63274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":236},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"8584be51f7dd474783656bba80ee842f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":236},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aebad8533ee401a87c8d64a9522ecfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":236},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c9c3be827b242aaafbad609d0629cdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":289},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b28d5405067445eb938a7797844d94f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":289},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caad20c4ffbe4127a62dd282e240ae1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":235,
              "y":230},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ec37c7c9b434b2797aa6bdb0cb186fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":235,
                  "y":230},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u28.png"}},
{
          "id":"2aad2102c2eb4bd1989c50657a5d6091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":339},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6fda199f3db49d0bd9a9a9055e1a10c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":339},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"5e8da6fcd92a4f78a30402521fbfde11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":355},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"004e082dee1942d4b3b9150f11761917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":355},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"e2e63304d6104a10b95f338ddf96b42e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":355},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91867401608c486e91a8824e3653f18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":355},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c831460e10248e0950acfefeb92155a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":207,
              "y":349},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5534065a4e4c44ff8a5ac7ec4d1bb18a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":207,
                  "y":349},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u28.png"}},
{
          "id":"a9a8dd90b2534708ab901ed01264cd1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":257,
              "y":357},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"425db32d97b643eb8b87ef276fcce35d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":257,
                  "y":357},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9d21ee3c64e4ffeb06465729bef0cb6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":74},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"89002414a5d04d739d3873285d1df3d5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":547,
              "y":74},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"766ae4465e1f4cf585c5713cd35ba5a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":458},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8425f06c65604777b333bd23fdf84a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":458},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"ef69289dee6c4fc9937a696b8a409cbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":474},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441e6f8ebcbc42beb74570da4dd7bb8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":474},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"1c07e75e4ce646eca0ebdea2aa929cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":474},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fcec3846bf43e195e3d159781b79c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":474},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3633adb7915c4f4bac89e72d80a13eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":207,
              "y":468},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99947779a26b446a8c78d32e5976f6d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":207,
                  "y":468},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u28.png"}},
{
          "id":"e73ec10a418045abbda9ead60d68a2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":257,
              "y":475},
            "size":{
              "width":65,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0698a1cb875546e0ad6107cb782418fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":257,
                  "y":475},
                "size":{
                  "width":65,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1a9e874105e4577aaa84414a86f2957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":285,
              "y":236},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32a754a9e6f443a9f4df50c2995bcc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":285,
                  "y":236},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6f1864a9f4749b48df6b44c6c9c5e78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":94,
              "y":165},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff1057230124ec6bdbce051bfb276e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":94,
                  "y":165},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"354073c6cb864a3b89c0ecaa3b334ef1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":307,
              "y":165},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f0099f88f37463e91c689378471b100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":307,
                  "y":165},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32acdc44822e4f0395be641a6471581d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":440,
              "y":215},
            "size":{
              "width":220,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df40dfc8c7d74fc78d339ff41713c419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":440,
                  "y":215},
                "size":{
                  "width":220,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者（全部）/u46.png"}},
{
          "id":"6777a277a669489d926148a377b6bde3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":520,
              "y":168},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"632bdb3c0e1e498bbe6f45c6740ff916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":520,
                  "y":168},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c58bd251912424c90bf4c086210d2f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":410,
              "y":292},
            "size":{
              "width":183,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f43ab595cc45f489fcb1c6834e51af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":410,
                  "y":292},
                "size":{
                  "width":183,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84bcc417d2964f829cc3b53bb2d9cea8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":418},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"264f165798b0466197b7d1629685ebc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":418},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6850840857f34d6d81a85b399d966237",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":410,
              "y":421},
            "size":{
              "width":183,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6b5bc7b2c074b5ca5945f3410eb0041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":410,
                  "y":421},
                "size":{
                  "width":183,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"414a616e96e740eeb5f983abb354e520",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":139,
              "y":524},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2bdc21cdbce446e98440d9973412e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":139,
                  "y":524},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2211dda161b34a6ca358550f72f585ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":409,
              "y":527},
            "size":{
              "width":183,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3040d80e9b0841b8a3b4ac14fcda39e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":409,
                  "y":527},
                "size":{
                  "width":183,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "431372102d96469c9ae42d662ffe3682":{
      "scriptId":"u0"},
    "0ecaad8a1c1243dabff237b16cc00ccc":{
      "scriptId":"u1"},
    "d1d9d0b0727f46a9a2e13b8ee873df84":{
      "scriptId":"u2"},
    "ae07a8eb370d42c3a8e015343c3f15da":{
      "scriptId":"u3"},
    "eac3acaa9a194fadbf76c9fbf4616868":{
      "scriptId":"u4"},
    "e06cc0581a6f4c48a4e50984164e2e19":{
      "scriptId":"u5"},
    "74cb0e9250ea4ed7a0a2fe9299b93705":{
      "scriptId":"u6"},
    "6b79bb0fb3c14771b343eb061d688ae7":{
      "scriptId":"u7"},
    "e780ac1049624bd591dc6253851da108":{
      "scriptId":"u8"},
    "708e45b4fb1846b39dd53a40176cb989":{
      "scriptId":"u9"},
    "b8cff7d6209a44c5a5db706c1d4f23a4":{
      "scriptId":"u10"},
    "1dd3d6785af54712ae99afb76cb63274":{
      "scriptId":"u11"},
    "8584be51f7dd474783656bba80ee842f":{
      "scriptId":"u12"},
    "7aebad8533ee401a87c8d64a9522ecfe":{
      "scriptId":"u13"},
    "1c9c3be827b242aaafbad609d0629cdf":{
      "scriptId":"u14"},
    "b28d5405067445eb938a7797844d94f7":{
      "scriptId":"u15"},
    "caad20c4ffbe4127a62dd282e240ae1a":{
      "scriptId":"u16"},
    "8ec37c7c9b434b2797aa6bdb0cb186fd":{
      "scriptId":"u17"},
    "2aad2102c2eb4bd1989c50657a5d6091":{
      "scriptId":"u18"},
    "d6fda199f3db49d0bd9a9a9055e1a10c":{
      "scriptId":"u19"},
    "5e8da6fcd92a4f78a30402521fbfde11":{
      "scriptId":"u20"},
    "004e082dee1942d4b3b9150f11761917":{
      "scriptId":"u21"},
    "e2e63304d6104a10b95f338ddf96b42e":{
      "scriptId":"u22"},
    "91867401608c486e91a8824e3653f18d":{
      "scriptId":"u23"},
    "5c831460e10248e0950acfefeb92155a":{
      "scriptId":"u24"},
    "5534065a4e4c44ff8a5ac7ec4d1bb18a":{
      "scriptId":"u25"},
    "a9a8dd90b2534708ab901ed01264cd1e":{
      "scriptId":"u26"},
    "425db32d97b643eb8b87ef276fcce35d":{
      "scriptId":"u27"},
    "e9d21ee3c64e4ffeb06465729bef0cb6":{
      "scriptId":"u28"},
    "89002414a5d04d739d3873285d1df3d5":{
      "scriptId":"u29"},
    "766ae4465e1f4cf585c5713cd35ba5a0":{
      "scriptId":"u30"},
    "8425f06c65604777b333bd23fdf84a69":{
      "scriptId":"u31"},
    "ef69289dee6c4fc9937a696b8a409cbf":{
      "scriptId":"u32"},
    "441e6f8ebcbc42beb74570da4dd7bb8c":{
      "scriptId":"u33"},
    "1c07e75e4ce646eca0ebdea2aa929cf1":{
      "scriptId":"u34"},
    "26fcec3846bf43e195e3d159781b79c5":{
      "scriptId":"u35"},
    "3633adb7915c4f4bac89e72d80a13eb4":{
      "scriptId":"u36"},
    "99947779a26b446a8c78d32e5976f6d7":{
      "scriptId":"u37"},
    "e73ec10a418045abbda9ead60d68a2a6":{
      "scriptId":"u38"},
    "0698a1cb875546e0ad6107cb782418fb":{
      "scriptId":"u39"},
    "a1a9e874105e4577aaa84414a86f2957":{
      "scriptId":"u40"},
    "c32a754a9e6f443a9f4df50c2995bcc6":{
      "scriptId":"u41"},
    "a6f1864a9f4749b48df6b44c6c9c5e78":{
      "scriptId":"u42"},
    "dff1057230124ec6bdbce051bfb276e0":{
      "scriptId":"u43"},
    "354073c6cb864a3b89c0ecaa3b334ef1":{
      "scriptId":"u44"},
    "1f0099f88f37463e91c689378471b100":{
      "scriptId":"u45"},
    "32acdc44822e4f0395be641a6471581d":{
      "scriptId":"u46"},
    "df40dfc8c7d74fc78d339ff41713c419":{
      "scriptId":"u47"},
    "6777a277a669489d926148a377b6bde3":{
      "scriptId":"u48"},
    "632bdb3c0e1e498bbe6f45c6740ff916":{
      "scriptId":"u49"},
    "8c58bd251912424c90bf4c086210d2f4":{
      "scriptId":"u50"},
    "24f43ab595cc45f489fcb1c6834e51af":{
      "scriptId":"u51"},
    "84bcc417d2964f829cc3b53bb2d9cea8":{
      "scriptId":"u52"},
    "264f165798b0466197b7d1629685ebc5":{
      "scriptId":"u53"},
    "6850840857f34d6d81a85b399d966237":{
      "scriptId":"u54"},
    "c6b5bc7b2c074b5ca5945f3410eb0041":{
      "scriptId":"u55"},
    "414a616e96e740eeb5f983abb354e520":{
      "scriptId":"u56"},
    "a2bdc21cdbce446e98440d9973412e68":{
      "scriptId":"u57"},
    "2211dda161b34a6ca358550f72f585ec":{
      "scriptId":"u58"},
    "3040d80e9b0841b8a3b4ac14fcda39e5":{
      "scriptId":"u59"}}});