$axure.loadCurrentPage({
  "url":"话题.html",
  "generationDate":new Date(1425355640984.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0056be7ce2c446b6915f19fe83d0362e",
    "type":"Axure:Page",
    "name":"话题",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"97215ed2147847c38215d2df6a16a47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5b5d8d4f3441da8f87b17289ec7517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"02820291dc6b4019a3fbde6a075c6d53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":238,
              "y":183},
            "size":{
              "width":205,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"160976ce8c6545c6ad1a60b60509f085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":238,
                  "y":183},
                "size":{
                  "width":205,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8caeef465a284e1392a58694d69bc871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":259},
            "size":{
              "width":620,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb54b8530c54b318f1b46266e888976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":259},
                "size":{
                  "width":620,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话题/u4.png"}},
{
          "id":"e2bb643e20c144339fb7244ec06ad0ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":54,
              "y":284},
            "size":{
              "width":547,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84af4ff203684d1fb52b3e0ddeb05560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":54,
                  "y":284},
                "size":{
                  "width":547,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc9eca5727b4621a44adbcb052809a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d077581cdbfa4de58b1a2ed580030e45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"497f51375cb54af0b1a9df5996d81715",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca2c20e64daa4c849fb71589ae926307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cec979112ab46e798359fd02e4b2d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15fec55776b04978aa4deff2c389d7d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85ad32a7c7df46b98285a9f90c0da0cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b39fcc7e84441bbb537604fd2f194d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"b912fc32ac4749d3ab67cc596c33d6d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"865e003cf3324e0db889d888f4d7277d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/病史/u10.png"}},
{
          "id":"839e84b7c3dc4cf3be45fe7e6aba0236",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":75,
              "y":185},
            "size":{
              "width":79,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e89cc0a2bb0d49e58476f35f3808babd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":185},
                "size":{
                  "width":79,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eddbe2a8b51c487fadac8d9a4bba8f5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":241,
              "y":182},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f60d20b1b0240a4aa5efa6eecf03d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":241,
                  "y":182},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f8a385a8e924b04b0663892a9c02d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":450,
              "y":185},
            "size":{
              "width":151,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3738d3329de4287a55d8e04b40970c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":185},
                "size":{
                  "width":151,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7206342208ac400187ed6eb2553ff774",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":164},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/病史/u18_line.png"}},
{
          "id":"48f471a41a094f9bae3cebff54808356",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":166},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/病史/u18_line.png"}},
{
          "id":"e669b471d3b3417888f278008cf16033",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9cdfab8a6a9452f8242325aea674280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"a9dbf237ba504bf087e90a46720ea805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a570b1b677dc45ea8279fc78eea0ad27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7678a7493ca415c99d335027af3ded7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1ef1e2234494dd28d9b1514d4963b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb41bc4355c047a5ad3f3253bd19cd0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cc770e9ff7446189e949d45acc2b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"bf70de60d7314bc0a87f362c08fdd616",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e6aaad426643ad830868392ce1bcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/病史/u10.png"}},
{
          "id":"7a94256084024ba0bab66557fe907c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":75,
              "y":185},
            "size":{
              "width":79,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a2208cb4d041439de3742e2676ed05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":185},
                "size":{
                  "width":79,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"593f63082e36483ca55428d542739f03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":241,
              "y":182},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99490bdcb05d44f5aef111de51250f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":241,
                  "y":182},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72e95142ece7418ba0e5d97338275e19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":450,
              "y":185},
            "size":{
              "width":151,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5f0cd5c5eb44088bc244e3267640abd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":185},
                "size":{
                  "width":151,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4903c61b83e9403292f465edf3c55dc9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":164},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/病史/u18_line.png"}},
{
          "id":"91fc1f03cf444010b8e89c5642e50d6f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":166},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/病史/u18_line.png"}},
{
          "id":"fde45924b71746a78c3e2201b2ca637b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"22px",
            "fontWeight":"200",
            "location":{
              "x":479,
              "y":341},
            "size":{
              "width":153,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ff115652364c39b82c634d970c1647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"22px",
                "fontWeight":"200",
                "location":{
                  "x":479,
                  "y":341},
                "size":{
                  "width":153,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b097c015e824f63ab627d1178a2e7c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":402},
            "size":{
              "width":620,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a588d1e8d14578953761e429ab854e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":402},
                "size":{
                  "width":620,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话题/u4.png"}},
{
          "id":"45ad411c7b09411489d34eb4941b6003",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":54,
              "y":427},
            "size":{
              "width":547,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f519d0a45846440aa4bdbb4f4c6075d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":54,
                  "y":427},
                "size":{
                  "width":547,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93fc0e2682f34f7ab573eb76b56586b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"22px",
            "fontWeight":"200",
            "location":{
              "x":479,
              "y":484},
            "size":{
              "width":153,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60943a440b0f47d8a625f7218778e68f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"22px",
                "fontWeight":"200",
                "location":{
                  "x":479,
                  "y":484},
                "size":{
                  "width":153,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "97215ed2147847c38215d2df6a16a47e":{
      "scriptId":"u0"},
    "1a5b5d8d4f3441da8f87b17289ec7517":{
      "scriptId":"u1"},
    "02820291dc6b4019a3fbde6a075c6d53":{
      "scriptId":"u2"},
    "160976ce8c6545c6ad1a60b60509f085":{
      "scriptId":"u3"},
    "8caeef465a284e1392a58694d69bc871":{
      "scriptId":"u4"},
    "fdb54b8530c54b318f1b46266e888976":{
      "scriptId":"u5"},
    "e2bb643e20c144339fb7244ec06ad0ff":{
      "scriptId":"u6"},
    "84af4ff203684d1fb52b3e0ddeb05560":{
      "scriptId":"u7"},
    "9bc9eca5727b4621a44adbcb052809a3":{
      "scriptId":"u8"},
    "d077581cdbfa4de58b1a2ed580030e45":{
      "scriptId":"u9"},
    "497f51375cb54af0b1a9df5996d81715":{
      "scriptId":"u10"},
    "ca2c20e64daa4c849fb71589ae926307":{
      "scriptId":"u11"},
    "6cec979112ab46e798359fd02e4b2d13":{
      "scriptId":"u12"},
    "15fec55776b04978aa4deff2c389d7d3":{
      "scriptId":"u13"},
    "85ad32a7c7df46b98285a9f90c0da0cb":{
      "scriptId":"u14"},
    "6b39fcc7e84441bbb537604fd2f194d7":{
      "scriptId":"u15"},
    "b912fc32ac4749d3ab67cc596c33d6d3":{
      "scriptId":"u16"},
    "865e003cf3324e0db889d888f4d7277d":{
      "scriptId":"u17"},
    "839e84b7c3dc4cf3be45fe7e6aba0236":{
      "scriptId":"u18"},
    "e89cc0a2bb0d49e58476f35f3808babd":{
      "scriptId":"u19"},
    "eddbe2a8b51c487fadac8d9a4bba8f5d":{
      "scriptId":"u20"},
    "6f60d20b1b0240a4aa5efa6eecf03d91":{
      "scriptId":"u21"},
    "9f8a385a8e924b04b0663892a9c02d3b":{
      "scriptId":"u22"},
    "c3738d3329de4287a55d8e04b40970c2":{
      "scriptId":"u23"},
    "7206342208ac400187ed6eb2553ff774":{
      "scriptId":"u24"},
    "48f471a41a094f9bae3cebff54808356":{
      "scriptId":"u25"},
    "e669b471d3b3417888f278008cf16033":{
      "scriptId":"u26"},
    "b9cdfab8a6a9452f8242325aea674280":{
      "scriptId":"u27"},
    "a9dbf237ba504bf087e90a46720ea805":{
      "scriptId":"u28"},
    "a570b1b677dc45ea8279fc78eea0ad27":{
      "scriptId":"u29"},
    "a7678a7493ca415c99d335027af3ded7":{
      "scriptId":"u30"},
    "a1ef1e2234494dd28d9b1514d4963b1e":{
      "scriptId":"u31"},
    "fb41bc4355c047a5ad3f3253bd19cd0b":{
      "scriptId":"u32"},
    "77cc770e9ff7446189e949d45acc2b27":{
      "scriptId":"u33"},
    "bf70de60d7314bc0a87f362c08fdd616":{
      "scriptId":"u34"},
    "13e6aaad426643ad830868392ce1bcca":{
      "scriptId":"u35"},
    "7a94256084024ba0bab66557fe907c15":{
      "scriptId":"u36"},
    "58a2208cb4d041439de3742e2676ed05":{
      "scriptId":"u37"},
    "593f63082e36483ca55428d542739f03":{
      "scriptId":"u38"},
    "99490bdcb05d44f5aef111de51250f73":{
      "scriptId":"u39"},
    "72e95142ece7418ba0e5d97338275e19":{
      "scriptId":"u40"},
    "e5f0cd5c5eb44088bc244e3267640abd":{
      "scriptId":"u41"},
    "4903c61b83e9403292f465edf3c55dc9":{
      "scriptId":"u42"},
    "91fc1f03cf444010b8e89c5642e50d6f":{
      "scriptId":"u43"},
    "fde45924b71746a78c3e2201b2ca637b":{
      "scriptId":"u44"},
    "73ff115652364c39b82c634d970c1647":{
      "scriptId":"u45"},
    "6b097c015e824f63ab627d1178a2e7c7":{
      "scriptId":"u46"},
    "19a588d1e8d14578953761e429ab854e":{
      "scriptId":"u47"},
    "45ad411c7b09411489d34eb4941b6003":{
      "scriptId":"u48"},
    "f519d0a45846440aa4bdbb4f4c6075d2":{
      "scriptId":"u49"},
    "93fc0e2682f34f7ab573eb76b56586b4":{
      "scriptId":"u50"},
    "60943a440b0f47d8a625f7218778e68f":{
      "scriptId":"u51"}}});