$axure.loadCurrentPage({
  "url":"血糖记录.html",
  "generationDate":new Date(1429527574196.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0056be7ce2c446b6915f19fe83d0362e",
    "type":"Axure:Page",
    "name":"血糖记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1973cd76e2514c2b8270add3dac95aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac778947ae043cb9c4820d6300d06b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"7215bf107ea2424d89b0b0183c9bdefa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d75b33f50514490a04bf71091f3d48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"6733e9efb7914ce7b01aa8b5402eca29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0231bcad52b647e994391c3efacb57a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbca3148ed8747eca9247daa65d7c8d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1d50b093dda4f53a4e32778eec9a6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f253c227f05648ccbc017832579ebf26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4125b58ebc66448cab5f2a8351f4ce9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"9434b055c78e46e492bdafe600ab15cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068c60388403460581d5568c42adfd36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"16ab5a6e925246c4b4ab9e836f0fb0d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":432,
              "y":185},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d4f4fcc0ae44bf8c91082fc6c76e44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":432,
                  "y":185},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1eb55baab5348db980464cec3658ac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":100,
              "y":185},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7ba36a16390408a9db807da3e5fe688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":185},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98079a7db5c94b40978912b9e72ec3fd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":166},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/血糖记录/u16_line.png"}},
{
          "id":"fea4ca0b68644a6d839ef14a378bfa75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":581},
            "size":{
              "width":640,
              "height":575}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e2b6a8f03c43cbad0a48e26493bc10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":581},
                "size":{
                  "width":640,
                  "height":575}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/血糖记录/u17.png"}},
{
          "id":"f7b6f68c37da429ab61fb00fc98ec92b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":248},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe0c4de8e0354f03adafc94ada2294e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":248},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u14.png"}},
{
          "id":"4f262bb852f242c9bbd193aae826e229",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'ArialMT', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":269.5},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a70ad1b46b4356b0d183abc3ca0a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ArialMT', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":269.5},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7e61bae8d814b3baab222646bd7b2b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":356},
            "size":{
              "width":225,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c93b4e454d69493686d330b7c99f320a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":356},
                "size":{
                  "width":225,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4c1cbc4c229418f80db096a5af5639b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":423},
            "size":{
              "width":225,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41f54fab6f3d463a83b85cf7519be43e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":423},
                "size":{
                  "width":225,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d44b007c5c841a9aa5527a0f7286af7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":500},
            "size":{
              "width":225,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c3751b7bb84fd898298e57abcfb65c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":500},
                "size":{
                  "width":225,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e392552fa1484a238e9adfffdbafee66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":300,
              "y":356},
            "size":{
              "width":186,
              "height":186}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c619377ec7d541f2b23651ea44ddf839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":300,
                  "y":356},
                "size":{
                  "width":186,
                  "height":186}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/血糖记录/u29.png"}},
{
          "id":"2300a2ad56dd47ecbc5e47bb4259fc32",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'AppleSymbols', 'Apple Symbols'",
            "fontWeight":"400",
            "location":{
              "x":399,
              "y":275},
            "size":{
              "width":20,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff5354f0f6c646f692085b972546fb76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AppleSymbols', 'Apple Symbols'",
                "fontWeight":"400",
                "location":{
                  "x":399,
                  "y":275},
                "size":{
                  "width":20,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"628230e934454496a09b420ff9a82532",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":440,
              "y":382},
            "size":{
              "width":124,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0524754fca1493babc0ce797974608c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":440,
                  "y":382},
                "size":{
                  "width":124,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eccf254276444382b967190f1b0cd6d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":581},
            "size":{
              "width":626,
              "height":499}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c79a495f321243e39d751a0febc151ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":581},
                "size":{
                  "width":626,
                  "height":499}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/血糖记录/u35.png"}},
{
          "id":"a4894ea235484e728ac6c7cda265c2c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1076},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45f539ecf46d4555bcf066d3dbdb480c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1076},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u14.png"}},
{
          "id":"5f3380cb822746028d979c7ad0e85d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":240,
              "y":1096},
            "size":{
              "width":200,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88be76dca27c422f95a9bb9263ca118f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":240,
                  "y":1096},
                "size":{
                  "width":200,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1973cd76e2514c2b8270add3dac95aa1":{
      "scriptId":"u0"},
    "eac778947ae043cb9c4820d6300d06b1":{
      "scriptId":"u1"},
    "7215bf107ea2424d89b0b0183c9bdefa":{
      "scriptId":"u2"},
    "1d75b33f50514490a04bf71091f3d48f":{
      "scriptId":"u3"},
    "6733e9efb7914ce7b01aa8b5402eca29":{
      "scriptId":"u4"},
    "0231bcad52b647e994391c3efacb57a2":{
      "scriptId":"u5"},
    "fbca3148ed8747eca9247daa65d7c8d3":{
      "scriptId":"u6"},
    "d1d50b093dda4f53a4e32778eec9a6d0":{
      "scriptId":"u7"},
    "f253c227f05648ccbc017832579ebf26":{
      "scriptId":"u8"},
    "4125b58ebc66448cab5f2a8351f4ce9b":{
      "scriptId":"u9"},
    "9434b055c78e46e492bdafe600ab15cf":{
      "scriptId":"u10"},
    "068c60388403460581d5568c42adfd36":{
      "scriptId":"u11"},
    "16ab5a6e925246c4b4ab9e836f0fb0d8":{
      "scriptId":"u12"},
    "36d4f4fcc0ae44bf8c91082fc6c76e44":{
      "scriptId":"u13"},
    "b1eb55baab5348db980464cec3658ac9":{
      "scriptId":"u14"},
    "c7ba36a16390408a9db807da3e5fe688":{
      "scriptId":"u15"},
    "98079a7db5c94b40978912b9e72ec3fd":{
      "scriptId":"u16"},
    "fea4ca0b68644a6d839ef14a378bfa75":{
      "scriptId":"u17"},
    "54e2b6a8f03c43cbad0a48e26493bc10":{
      "scriptId":"u18"},
    "f7b6f68c37da429ab61fb00fc98ec92b":{
      "scriptId":"u19"},
    "fe0c4de8e0354f03adafc94ada2294e3":{
      "scriptId":"u20"},
    "4f262bb852f242c9bbd193aae826e229":{
      "scriptId":"u21"},
    "02a70ad1b46b4356b0d183abc3ca0a0f":{
      "scriptId":"u22"},
    "c7e61bae8d814b3baab222646bd7b2b0":{
      "scriptId":"u23"},
    "c93b4e454d69493686d330b7c99f320a":{
      "scriptId":"u24"},
    "e4c1cbc4c229418f80db096a5af5639b":{
      "scriptId":"u25"},
    "41f54fab6f3d463a83b85cf7519be43e":{
      "scriptId":"u26"},
    "8d44b007c5c841a9aa5527a0f7286af7":{
      "scriptId":"u27"},
    "64c3751b7bb84fd898298e57abcfb65c":{
      "scriptId":"u28"},
    "e392552fa1484a238e9adfffdbafee66":{
      "scriptId":"u29"},
    "c619377ec7d541f2b23651ea44ddf839":{
      "scriptId":"u30"},
    "2300a2ad56dd47ecbc5e47bb4259fc32":{
      "scriptId":"u31"},
    "ff5354f0f6c646f692085b972546fb76":{
      "scriptId":"u32"},
    "628230e934454496a09b420ff9a82532":{
      "scriptId":"u33"},
    "d0524754fca1493babc0ce797974608c":{
      "scriptId":"u34"},
    "eccf254276444382b967190f1b0cd6d6":{
      "scriptId":"u35"},
    "c79a495f321243e39d751a0febc151ff":{
      "scriptId":"u36"},
    "a4894ea235484e728ac6c7cda265c2c3":{
      "scriptId":"u37"},
    "45f539ecf46d4555bcf066d3dbdb480c":{
      "scriptId":"u38"},
    "5f3380cb822746028d979c7ad0e85d9d":{
      "scriptId":"u39"},
    "88be76dca27c422f95a9bb9263ca118f":{
      "scriptId":"u40"}}});