$axure.loadCurrentPage({
  "url":"选择工作地址.html",
  "generationDate":new Date(1431411288954.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b5eaf2e1d1594986a050c33511686bbd",
    "type":"Axure:Page",
    "name":"选择工作地址",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42baf6d0726745728debac6ac04ef88b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca0f1ddabdbf4642b84330ae42c01ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"c91f58d12c8349f58ce08e99bf24d684",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c4ec9a1fd541f091960bb549e2e89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"69441a3e5eb547ceb3fd909c1aa88b85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75541e29d7904606baa39d844d625a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"1cd787670c1345b79b00e7e32e246d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":175},
            "size":{
              "width":640,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"623974d2fdf54cc6880dcd11e88f051f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":175},
                "size":{
                  "width":640,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作地址/u6.png"}},
{
          "id":"3badb16ff1424028aadfdf7ca0032fd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":265,
              "y":80},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50e6ea010081426ca6db6992a9bab4cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":265,
                  "y":80},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9473b848d9224b8cae75f547fdfd450d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f104feeb2ea4ad1b6b237ceb0a6b324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d27424c51e494ae5aa97b55c153a75d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":557,
              "y":80},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6449144b672e46ad8b77a7933833a99e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":557,
                  "y":80},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a177112a80bf4774b4087a2b9f042825",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":209},
            "size":{
              "width":20,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960a22f945c541bf9929fe8d13fdb9b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":209},
                "size":{
                  "width":20,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02ea0009ebde41be8875391defb9db0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":208},
            "size":{
              "width":392,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225c4f066f774457b9235253f1e24e6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":208},
                "size":{
                  "width":392,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95ad3a1bb6dc45c480348331f69069fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"070fa5b573eb452fb599a58e1191fa1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择工作地址/u18.png"}},
{
          "id":"f4a51aa32e404a66b4a181b64d48e194",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":913.999938964844},
            "size":{
              "width":640,
              "height":246}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da814666eb3416b95032fcac449230f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":913.999938964844},
                "size":{
                  "width":640,
                  "height":246}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/省份/u40.png"}},
{
          "id":"57b9d802187748cf94ed913d7c6d29d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":1016.99993896484},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d9951fe8b234d459472d1b3d2e0a3f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":1016.99993896484},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdf54c6594234b4c941fe0b814c317bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":292,
              "y":1016.99993896484},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19647c63f4cd4c13878a1c7a50feb80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":292,
                  "y":1016.99993896484},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4f3eee91d434d1cbfd2069a7f23f2d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":534,
              "y":1016.99993896484},
            "size":{
              "width":103,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb42c075238f46bea4c46c1d4a51cd67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":534,
                  "y":1016.99993896484},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1f8f19e241c41a7b88b2c199ac3f919",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":63,
              "y":943.999938964844},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73a3df5c86da4b12a92ec490cbe84d6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":63,
                  "y":943.999938964844},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca88b29e7f544fbb72b889803550368",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":307,
              "y":943.999938964844},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf9914cb56494b9ea9b7d285a78163eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":307,
                  "y":943.999938964844},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43ed222c48f046d991386864e21c143b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":541,
              "y":943.999938964844},
            "size":{
              "width":103,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f953ff63834bca93610c639678f919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":541,
                  "y":943.999938964844},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c88bea3a8e864fadb96f839ddf85b800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":63,
              "y":1092},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e37226378ed41798e888469dbdcab85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":63,
                  "y":1092},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"721a431a20154acf95cc13cb24da90f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":307,
              "y":1092},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2eac4b818e42e2abc5c06677753d68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":307,
                  "y":1092},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f53d89545c89436e969bb177f2283b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":541,
              "y":1092},
            "size":{
              "width":103,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c4629083f7c41b19921235139b8aa7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":541,
                  "y":1092},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "42baf6d0726745728debac6ac04ef88b":{
      "scriptId":"u0"},
    "ca0f1ddabdbf4642b84330ae42c01ebc":{
      "scriptId":"u1"},
    "c91f58d12c8349f58ce08e99bf24d684":{
      "scriptId":"u2"},
    "c0c4ec9a1fd541f091960bb549e2e89a":{
      "scriptId":"u3"},
    "69441a3e5eb547ceb3fd909c1aa88b85":{
      "scriptId":"u4"},
    "75541e29d7904606baa39d844d625a2f":{
      "scriptId":"u5"},
    "1cd787670c1345b79b00e7e32e246d2c":{
      "scriptId":"u6"},
    "623974d2fdf54cc6880dcd11e88f051f":{
      "scriptId":"u7"},
    "3badb16ff1424028aadfdf7ca0032fd3":{
      "scriptId":"u8"},
    "50e6ea010081426ca6db6992a9bab4cf":{
      "scriptId":"u9"},
    "9473b848d9224b8cae75f547fdfd450d":{
      "scriptId":"u10"},
    "5f104feeb2ea4ad1b6b237ceb0a6b324":{
      "scriptId":"u11"},
    "d27424c51e494ae5aa97b55c153a75d1":{
      "scriptId":"u12"},
    "6449144b672e46ad8b77a7933833a99e":{
      "scriptId":"u13"},
    "a177112a80bf4774b4087a2b9f042825":{
      "scriptId":"u14"},
    "960a22f945c541bf9929fe8d13fdb9b0":{
      "scriptId":"u15"},
    "02ea0009ebde41be8875391defb9db0b":{
      "scriptId":"u16"},
    "225c4f066f774457b9235253f1e24e6c":{
      "scriptId":"u17"},
    "95ad3a1bb6dc45c480348331f69069fe":{
      "scriptId":"u18"},
    "070fa5b573eb452fb599a58e1191fa1b":{
      "scriptId":"u19"},
    "f4a51aa32e404a66b4a181b64d48e194":{
      "scriptId":"u20"},
    "5da814666eb3416b95032fcac449230f":{
      "scriptId":"u21"},
    "57b9d802187748cf94ed913d7c6d29d2":{
      "scriptId":"u22"},
    "0d9951fe8b234d459472d1b3d2e0a3f1":{
      "scriptId":"u23"},
    "cdf54c6594234b4c941fe0b814c317bb":{
      "scriptId":"u24"},
    "19647c63f4cd4c13878a1c7a50feb80a":{
      "scriptId":"u25"},
    "a4f3eee91d434d1cbfd2069a7f23f2d7":{
      "scriptId":"u26"},
    "bb42c075238f46bea4c46c1d4a51cd67":{
      "scriptId":"u27"},
    "a1f8f19e241c41a7b88b2c199ac3f919":{
      "scriptId":"u28"},
    "73a3df5c86da4b12a92ec490cbe84d6a":{
      "scriptId":"u29"},
    "0ca88b29e7f544fbb72b889803550368":{
      "scriptId":"u30"},
    "cf9914cb56494b9ea9b7d285a78163eb":{
      "scriptId":"u31"},
    "43ed222c48f046d991386864e21c143b":{
      "scriptId":"u32"},
    "01f953ff63834bca93610c639678f919":{
      "scriptId":"u33"},
    "c88bea3a8e864fadb96f839ddf85b800":{
      "scriptId":"u34"},
    "4e37226378ed41798e888469dbdcab85":{
      "scriptId":"u35"},
    "721a431a20154acf95cc13cb24da90f2":{
      "scriptId":"u36"},
    "5f2eac4b818e42e2abc5c06677753d68":{
      "scriptId":"u37"},
    "f53d89545c89436e969bb177f2283b32":{
      "scriptId":"u38"},
    "7c4629083f7c41b19921235139b8aa7d":{
      "scriptId":"u39"}}});