$axure.loadCurrentPage({
  "url":"重置支付密码.html",
  "generationDate":new Date(1429527580067.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e3eb6d187434f2589ae64af8c010dc5",
    "type":"Axure:Page",
    "name":"重置支付密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a5030e5ffc7a4b1a8137cd3978a8f8ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69d97eea5ee54282ae5f0804af0846df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"98a610726ea14c6897a129e215e16133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5424c465c9184b73863c05211530f9cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"cb0e4b4bbfee4ac7bbb5d7bcc30c4ddc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8daede33644a648ba784110bcbd670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"4f14b8c2307f45c38f0a5fc12319b497",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":225,
              "y":80},
            "size":{
              "width":230,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ff305d740a4dea96af2297b4685f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":225,
                  "y":80},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ae562c932eb4981bc9423b462c01ef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":64,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65077904c1e4b83b65bbbde82656509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12f657d9c00c4b5398d808b602c0f211",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":543,
              "y":84},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a92d03824e2a4d799b2fb6806e6e9457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":543,
                  "y":84},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6048699ad8be4f3d90c2cf8d97448476",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"48px",
            "fontWeight":"200",
            "location":{
              "x":20,
              "y":656},
            "size":{
              "width":640,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b5fcf97286a40d1a6bf73afefa7bfb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"48px",
                "fontWeight":"200",
                "location":{
                  "x":20,
                  "y":656},
                "size":{
                  "width":640,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现输入银行卡/u18.png"}},
{
          "id":"ea07f24112c8470dbe00ebb751c514bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":190},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b241c805bc1497fbb4f77a74159d4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入密码/u16.png"}},
{
          "id":"95de368c89254d6f926dca00bb02e211",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":190},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1469ab46db6b4438b8a612ee10a38e89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入密码/u16.png"}},
{
          "id":"7906963a0bb64c88a0ff4b0fc959e6c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":978,
              "y":190},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4023a9fffb6e49609442fbed0940bfe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":978,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入密码/u16.png"}},
{
          "id":"bfb7b7c8867f4bcf85f8509d0a97ea2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1078,
              "y":190},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0252b1b4c5e047a29b0ca03b02b5dd42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1078,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入密码/u16.png"}},
{
          "id":"b0bbd6e0bf7d45d68b084282adc32e2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1176,
              "y":190},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"337392549e9c4950885ae76f906d7d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1176,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入密码/u16.png"}},
{
          "id":"9c0354d2a607443492632cd5dc082ecd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1276,
              "y":190},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5caf184f7cb64c178c35fcfe197cfded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1276,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入密码/u16.png"}},
{
          "id":"e93c8a64b0294b88a24f8e6104cb878e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":42,
              "y":159},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0752c0553c48bea89b5c781017a3c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":42,
                  "y":159},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a5a8f297d12488d9b87c0b6ac776fb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1181,
              "y":300},
            "size":{
              "width":197,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53cf8b37cdcf4f008d20a7673905378e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1181,
                  "y":300},
                "size":{
                  "width":197,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82374e3918f546048fee10ea121618ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":185},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2a11d278c5e4226b5ed83fe3e376ee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":185},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"4d9745fc1a7d4df1a0aa0bf8c5ae1633",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":217},
            "size":{
              "width":145,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa8859ef57741e2945b3c06e53ea0d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":217},
                "size":{
                  "width":145,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17f6fb8135dc4ad39eeeb7d20e79c224",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"34px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":191,
              "y":219},
            "size":{
              "width":205,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f740070e59624a25a25f0996549d40be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"34px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":191,
                  "y":219},
                "size":{
                  "width":205,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a5030e5ffc7a4b1a8137cd3978a8f8ca":{
      "scriptId":"u0"},
    "69d97eea5ee54282ae5f0804af0846df":{
      "scriptId":"u1"},
    "98a610726ea14c6897a129e215e16133":{
      "scriptId":"u2"},
    "5424c465c9184b73863c05211530f9cb":{
      "scriptId":"u3"},
    "cb0e4b4bbfee4ac7bbb5d7bcc30c4ddc":{
      "scriptId":"u4"},
    "7a8daede33644a648ba784110bcbd670":{
      "scriptId":"u5"},
    "4f14b8c2307f45c38f0a5fc12319b497":{
      "scriptId":"u6"},
    "18ff305d740a4dea96af2297b4685f02":{
      "scriptId":"u7"},
    "7ae562c932eb4981bc9423b462c01ef7":{
      "scriptId":"u8"},
    "c65077904c1e4b83b65bbbde82656509":{
      "scriptId":"u9"},
    "12f657d9c00c4b5398d808b602c0f211":{
      "scriptId":"u10"},
    "a92d03824e2a4d799b2fb6806e6e9457":{
      "scriptId":"u11"},
    "6048699ad8be4f3d90c2cf8d97448476":{
      "scriptId":"u12"},
    "6b5fcf97286a40d1a6bf73afefa7bfb9":{
      "scriptId":"u13"},
    "ea07f24112c8470dbe00ebb751c514bd":{
      "scriptId":"u14"},
    "6b241c805bc1497fbb4f77a74159d4d4":{
      "scriptId":"u15"},
    "95de368c89254d6f926dca00bb02e211":{
      "scriptId":"u16"},
    "1469ab46db6b4438b8a612ee10a38e89":{
      "scriptId":"u17"},
    "7906963a0bb64c88a0ff4b0fc959e6c3":{
      "scriptId":"u18"},
    "4023a9fffb6e49609442fbed0940bfe4":{
      "scriptId":"u19"},
    "bfb7b7c8867f4bcf85f8509d0a97ea2f":{
      "scriptId":"u20"},
    "0252b1b4c5e047a29b0ca03b02b5dd42":{
      "scriptId":"u21"},
    "b0bbd6e0bf7d45d68b084282adc32e2b":{
      "scriptId":"u22"},
    "337392549e9c4950885ae76f906d7d73":{
      "scriptId":"u23"},
    "9c0354d2a607443492632cd5dc082ecd":{
      "scriptId":"u24"},
    "5caf184f7cb64c178c35fcfe197cfded":{
      "scriptId":"u25"},
    "e93c8a64b0294b88a24f8e6104cb878e":{
      "scriptId":"u26"},
    "ef0752c0553c48bea89b5c781017a3c6":{
      "scriptId":"u27"},
    "3a5a8f297d12488d9b87c0b6ac776fb9":{
      "scriptId":"u28"},
    "53cf8b37cdcf4f008d20a7673905378e":{
      "scriptId":"u29"},
    "82374e3918f546048fee10ea121618ff":{
      "scriptId":"u30"},
    "d2a11d278c5e4226b5ed83fe3e376ee5":{
      "scriptId":"u31"},
    "4d9745fc1a7d4df1a0aa0bf8c5ae1633":{
      "scriptId":"u32"},
    "afa8859ef57741e2945b3c06e53ea0d9":{
      "scriptId":"u33"},
    "17f6fb8135dc4ad39eeeb7d20e79c224":{
      "scriptId":"u34"},
    "f740070e59624a25a25f0996549d40be":{
      "scriptId":"u35"}}});