$axure.loadCurrentPage({
  "url":"绑定银行卡.html",
  "generationDate":new Date(1426560720683.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"62cc1bb42ac042f08c3438b2176c1e27",
    "type":"Axure:Page",
    "name":"绑定银行卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dba5a4583b214d33988a5dcef2e1a68d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015635623e764171922177f3a1e01eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"eb626efb43314f7aae52b4b9bd3dcb4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6493966d1b4361ad1197a021c93555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"2508290c6c6341b4b737efd54df168bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d71155400b684be08162182e44d88203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"b759155e02294ec3a0f4193816463ca1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":80},
            "size":{
              "width":180,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66352755ae5b4a5484c96f0dd678ec65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":80},
                "size":{
                  "width":180,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ace0c440fdc442468b1e904e343c45d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":64,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8916af365e1486b8ec7b89eefd8dc0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebd177a9b39a46fa9802140a5eb83165",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":270},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ddc379575e04bb194273d3d14de9556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":270},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/血糖记录/u10.png"}},
{
          "id":"3dc32859f9db4506b6631d4c66eaa205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d296d418ec84adf842790227044c4b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/血糖记录/u10.png"}},
{
          "id":"f75036bd39014786bf1c34dcc7821996",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":202},
            "size":{
              "width":145,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4de96c599ce4d45847ce44c589d1ff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":202},
                "size":{
                  "width":145,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9610dd1b015543d69f42d8a800123bc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"34px",
            "fontWeight":"200",
            "location":{
              "x":191,
              "y":206},
            "size":{
              "width":69,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86127cf1c2de4b16aefcace9434e8af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"34px",
                "fontWeight":"200",
                "location":{
                  "x":191,
                  "y":206},
                "size":{
                  "width":69,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bafe13d0c95e436db6a9653f8fe88de9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":302},
            "size":{
              "width":109,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f6be2af9ff4ad5bf3ce3ed7dccae45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":302},
                "size":{
                  "width":109,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b441b6fd963e4e1990f88fc374f3d93f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"34px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":191,
              "y":304},
            "size":{
              "width":137,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94701a42b29c48a0ab7fbb92a04fcd70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"34px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":191,
                  "y":304},
                "size":{
                  "width":137,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5873fea904d24036bfb5a757df347825",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":40,
              "y":390},
            "size":{
              "width":600,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d88127a8616d4afd897785bd0ed48632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":40,
                  "y":390},
                "size":{
                  "width":600,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u14.png"}},
{
          "id":"c1601e36e8384c809dd49b5c09f71cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":292,
              "y":414},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6011d674f56748e7826ad324183935cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":414},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dba5a4583b214d33988a5dcef2e1a68d":{
      "scriptId":"u0"},
    "015635623e764171922177f3a1e01eec":{
      "scriptId":"u1"},
    "eb626efb43314f7aae52b4b9bd3dcb4b":{
      "scriptId":"u2"},
    "8d6493966d1b4361ad1197a021c93555":{
      "scriptId":"u3"},
    "2508290c6c6341b4b737efd54df168bb":{
      "scriptId":"u4"},
    "d71155400b684be08162182e44d88203":{
      "scriptId":"u5"},
    "b759155e02294ec3a0f4193816463ca1":{
      "scriptId":"u6"},
    "66352755ae5b4a5484c96f0dd678ec65":{
      "scriptId":"u7"},
    "ace0c440fdc442468b1e904e343c45d8":{
      "scriptId":"u8"},
    "c8916af365e1486b8ec7b89eefd8dc0c":{
      "scriptId":"u9"},
    "ebd177a9b39a46fa9802140a5eb83165":{
      "scriptId":"u10"},
    "1ddc379575e04bb194273d3d14de9556":{
      "scriptId":"u11"},
    "3dc32859f9db4506b6631d4c66eaa205":{
      "scriptId":"u12"},
    "1d296d418ec84adf842790227044c4b8":{
      "scriptId":"u13"},
    "f75036bd39014786bf1c34dcc7821996":{
      "scriptId":"u14"},
    "f4de96c599ce4d45847ce44c589d1ff5":{
      "scriptId":"u15"},
    "9610dd1b015543d69f42d8a800123bc0":{
      "scriptId":"u16"},
    "86127cf1c2de4b16aefcace9434e8af8":{
      "scriptId":"u17"},
    "bafe13d0c95e436db6a9653f8fe88de9":{
      "scriptId":"u18"},
    "e4f6be2af9ff4ad5bf3ce3ed7dccae45":{
      "scriptId":"u19"},
    "b441b6fd963e4e1990f88fc374f3d93f":{
      "scriptId":"u20"},
    "94701a42b29c48a0ab7fbb92a04fcd70":{
      "scriptId":"u21"},
    "5873fea904d24036bfb5a757df347825":{
      "scriptId":"u22"},
    "d88127a8616d4afd897785bd0ed48632":{
      "scriptId":"u23"},
    "c1601e36e8384c809dd49b5c09f71cd9":{
      "scriptId":"u24"},
    "6011d674f56748e7826ad324183935cd":{
      "scriptId":"u25"}}});