$axure.loadCurrentPage({
  "url":"个人信息.html",
  "generationDate":new Date(1426560718538.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2d9b0513ba404215a9bb08cd6133a4e8",
    "type":"Axure:Page",
    "name":"个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe42151fb2804633be6f326d5e99c62e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afaab1d22bcb466fa990ee8c0b395a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"15166e5d4efa4555abac261f3f885aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7149ff6bba3f4a9783ae4c3c64c941c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"556e92dfa41e4ad78d051f03c27d308d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85f0d495ca59471284223af9d7c2f982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc98b516223d41418e610f33cafea163",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8e4b36b36d94810b053d792acf709b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3131f23d2d9946c9bb90568f8b80d396",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eeebefe25434f45b96a595d8e250033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"8dc09e4fba854581ba334afe28aedbd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7742519373cc44198bf46100a60cfe5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/血糖记录/u10.png"}},
{
          "id":"a209265b04264491b287923ebfe6ab06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":434,
              "y":182},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f626daa6b71042628b6189c7057889b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":182},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea2ef741883d4bc8bf89103705697a4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":114,
              "y":182},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3e41bffdcfe4eed802f65ac4033c9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":182},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ee61354df554dedbbb42c7d57d765cd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":166},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/血糖记录/u16_line.png"}},
{
          "id":"6d9c038c0ae4430fba0edd4ddeb78562",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":259},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8eec950be1248b4b68d970bbe6cd992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":259},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0ced5e725514ac1963c93f2c93c847e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":298},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0da9cc1c715d4571a572a65fee1d62f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":298},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"36841870c62c48ae9ce9701a650e1a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":323},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee5979f4e75a4c2eab520400abdd5cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":323},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a77a6471c364788ae4a855b1a5c77a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":403},
            "size":{
              "width":141,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b244c3b1584d4e858eec1f13d449e90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":403},
                "size":{
                  "width":141,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53f223c39c5148f395ffa11635d02e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":443},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f007ae6461c4a69ad80ed14c90ada66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":443},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"59a34e6a937b4f529334f0193716e58f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":467},
            "size":{
              "width":207,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94efa8889bea40198da08a5f1deda39c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":467},
                "size":{
                  "width":207,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aca473bf71d64633b10e338ad9d76927",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":546},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cdfcd40b9974f0a8578a984a1a98349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":546},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee34468dcbef48a0b2095f7c75dbd478",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":586},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e05f5ceef65d4c9e902cf89945f34c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":586},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"e271609320364398925492ac8370e9df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":610},
            "size":{
              "width":31,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5ba68e9e854f2a8f1ac4c8b515e5c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":610},
                "size":{
                  "width":31,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ab84604aaf94ae28dc30708952d02d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":611},
            "size":{
              "width":20,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaee2e19dc99426eba8c1029dd5ac57c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":611},
                "size":{
                  "width":20,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f00d97fdbc494627b08bc7042af99190",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":688},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9cd9d3ec6ca4b70bff255cb83a0428b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":688},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fafdcd4619f34508b8fe6e80543bc971",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":728},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"027e4530e60949d88cbd9956a9ac5755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":728},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"c8fcfd9b142646b59d741bfecece51e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":752},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31a067beae046d086e23e322a7279d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":752},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab4dcde2452e44d09e14ceaac89c9eab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":851},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad25edeffa454506a3c7ab7c443d5d0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":851},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"238bf70060074ae281569ba3cb2eb05d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":891},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2515a75b5d64a5ca04e89ee6ef89639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":891},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"1a4876da23294f74be1b0b7f4c956a5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":915},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"606623db830543d884b766aa6115a825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":915},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f2392a460ac42a1bd38c949d8d9eab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":1002},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757d8e24aff1489585ac7278af78952d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":1002},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9fdd87a2345403985242a2fe2fd05f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":1042},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df66cdf481584d7a9371e5bcb3a5841e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":1042},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"dbaab315a9ac4ddfa274d51d6c408921",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":1066},
            "size":{
              "width":31,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa5bb752c0048b1b10856bec759a145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":1066},
                "size":{
                  "width":31,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd428bef17d14d539c951830c8ad62c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":568,
              "y":468},
            "size":{
              "width":64,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a267a0a319044a42a754201bea97b2aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":568,
                  "y":468},
                "size":{
                  "width":64,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fe42151fb2804633be6f326d5e99c62e":{
      "scriptId":"u0"},
    "afaab1d22bcb466fa990ee8c0b395a09":{
      "scriptId":"u1"},
    "15166e5d4efa4555abac261f3f885aee":{
      "scriptId":"u2"},
    "7149ff6bba3f4a9783ae4c3c64c941c3":{
      "scriptId":"u3"},
    "556e92dfa41e4ad78d051f03c27d308d":{
      "scriptId":"u4"},
    "85f0d495ca59471284223af9d7c2f982":{
      "scriptId":"u5"},
    "cc98b516223d41418e610f33cafea163":{
      "scriptId":"u6"},
    "d8e4b36b36d94810b053d792acf709b9":{
      "scriptId":"u7"},
    "3131f23d2d9946c9bb90568f8b80d396":{
      "scriptId":"u8"},
    "4eeebefe25434f45b96a595d8e250033":{
      "scriptId":"u9"},
    "8dc09e4fba854581ba334afe28aedbd9":{
      "scriptId":"u10"},
    "7742519373cc44198bf46100a60cfe5b":{
      "scriptId":"u11"},
    "a209265b04264491b287923ebfe6ab06":{
      "scriptId":"u12"},
    "f626daa6b71042628b6189c7057889b1":{
      "scriptId":"u13"},
    "ea2ef741883d4bc8bf89103705697a4d":{
      "scriptId":"u14"},
    "e3e41bffdcfe4eed802f65ac4033c9e6":{
      "scriptId":"u15"},
    "8ee61354df554dedbbb42c7d57d765cd":{
      "scriptId":"u16"},
    "6d9c038c0ae4430fba0edd4ddeb78562":{
      "scriptId":"u17"},
    "c8eec950be1248b4b68d970bbe6cd992":{
      "scriptId":"u18"},
    "a0ced5e725514ac1963c93f2c93c847e":{
      "scriptId":"u19"},
    "0da9cc1c715d4571a572a65fee1d62f5":{
      "scriptId":"u20"},
    "36841870c62c48ae9ce9701a650e1a7d":{
      "scriptId":"u21"},
    "ee5979f4e75a4c2eab520400abdd5cf2":{
      "scriptId":"u22"},
    "9a77a6471c364788ae4a855b1a5c77a6":{
      "scriptId":"u23"},
    "b244c3b1584d4e858eec1f13d449e90e":{
      "scriptId":"u24"},
    "53f223c39c5148f395ffa11635d02e69":{
      "scriptId":"u25"},
    "7f007ae6461c4a69ad80ed14c90ada66":{
      "scriptId":"u26"},
    "59a34e6a937b4f529334f0193716e58f":{
      "scriptId":"u27"},
    "94efa8889bea40198da08a5f1deda39c":{
      "scriptId":"u28"},
    "aca473bf71d64633b10e338ad9d76927":{
      "scriptId":"u29"},
    "7cdfcd40b9974f0a8578a984a1a98349":{
      "scriptId":"u30"},
    "ee34468dcbef48a0b2095f7c75dbd478":{
      "scriptId":"u31"},
    "e05f5ceef65d4c9e902cf89945f34c5f":{
      "scriptId":"u32"},
    "e271609320364398925492ac8370e9df":{
      "scriptId":"u33"},
    "1a5ba68e9e854f2a8f1ac4c8b515e5c9":{
      "scriptId":"u34"},
    "5ab84604aaf94ae28dc30708952d02d8":{
      "scriptId":"u35"},
    "aaee2e19dc99426eba8c1029dd5ac57c":{
      "scriptId":"u36"},
    "f00d97fdbc494627b08bc7042af99190":{
      "scriptId":"u37"},
    "a9cd9d3ec6ca4b70bff255cb83a0428b":{
      "scriptId":"u38"},
    "fafdcd4619f34508b8fe6e80543bc971":{
      "scriptId":"u39"},
    "027e4530e60949d88cbd9956a9ac5755":{
      "scriptId":"u40"},
    "c8fcfd9b142646b59d741bfecece51e5":{
      "scriptId":"u41"},
    "d31a067beae046d086e23e322a7279d6":{
      "scriptId":"u42"},
    "ab4dcde2452e44d09e14ceaac89c9eab":{
      "scriptId":"u43"},
    "ad25edeffa454506a3c7ab7c443d5d0a":{
      "scriptId":"u44"},
    "238bf70060074ae281569ba3cb2eb05d":{
      "scriptId":"u45"},
    "a2515a75b5d64a5ca04e89ee6ef89639":{
      "scriptId":"u46"},
    "1a4876da23294f74be1b0b7f4c956a5f":{
      "scriptId":"u47"},
    "606623db830543d884b766aa6115a825":{
      "scriptId":"u48"},
    "5f2392a460ac42a1bd38c949d8d9eab1":{
      "scriptId":"u49"},
    "757d8e24aff1489585ac7278af78952d":{
      "scriptId":"u50"},
    "b9fdd87a2345403985242a2fe2fd05f0":{
      "scriptId":"u51"},
    "df66cdf481584d7a9371e5bcb3a5841e":{
      "scriptId":"u52"},
    "dbaab315a9ac4ddfa274d51d6c408921":{
      "scriptId":"u53"},
    "bfa5bb752c0048b1b10856bec759a145":{
      "scriptId":"u54"},
    "dd428bef17d14d539c951830c8ad62c0":{
      "scriptId":"u55"},
    "a267a0a319044a42a754201bea97b2aa":{
      "scriptId":"u56"}}});