$axure.loadCurrentPage({
  "url":"输入卡.html",
  "generationDate":new Date(1429527579791.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e4a5e00d95f48aa9eef5567f12e5f36",
    "type":"Axure:Page",
    "name":"输入卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a4af9aa133364700a7ab8df52f62c3e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380517193f814385b8db17a30e6dac2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"ccc8af41af9a4e46b024a1219134329c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fd204571eb94359b97ecfa8d9374688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"0effd6767de84f729c8b1aef5409363d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf2c7f27c7a4a9dab2d62684f1a9f03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"d7e30b71812441fc8dcfeb6147f6b12b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":80},
            "size":{
              "width":180,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f70662d9b04d4192590519a3a3567c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":80},
                "size":{
                  "width":180,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aba31bc5177c49e29de63ef57038e218",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":64,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0bd89fdef3d4cb3bf38cbdab7b4c1c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8610a857463447738a50f6e7379248d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":464},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aa908b9a60e4eedb8cf008aa538a408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":464},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"0765cb51b3ea4948a01b8546727d69e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cd6e8be1473490db1222c1541cd99d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"85c361b1b9cc4022bd20ff3cce684897",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":202},
            "size":{
              "width":217,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39f6c150e4b469dab4f535787a41851",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":202},
                "size":{
                  "width":217,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"880703a9b3684020bfe63dd2b9fe759e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"34px",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":202},
            "size":{
              "width":246,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa74063522ee42b9a2e774fe700883fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"34px",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":202},
                "size":{
                  "width":246,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9abb4ee411c2466895f83512e18c96ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":856,
              "y":496},
            "size":{
              "width":145,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdbfc7ce11f64cd48c62e4a4af1d4e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":856,
                  "y":496},
                "size":{
                  "width":145,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62c6e8da0b394bc69281f152f38160f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"34px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":1011,
              "y":498},
            "size":{
              "width":205,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1a789de973b4f82bbead6cf242082d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"34px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":1011,
                  "y":498},
                "size":{
                  "width":205,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82de007e847447f2956d7816b1a82d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":40,
              "y":330},
            "size":{
              "width":600,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5027c1c66cf44374ae25586cfc112248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":40,
                  "y":330},
                "size":{
                  "width":600,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现输入银行卡/u12.png"}},
{
          "id":"3fd1471023bd4fa08597f762e97b8293",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":292,
              "y":354},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8d207ac82c2420d972f4a529fc89d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":354},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ca4411249594ad5a4919d192d0ddf99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":36,
              "y":280},
            "size":{
              "width":301,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01b1223bf0574c77adcb2a62d133be31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":280},
                "size":{
                  "width":301,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a4af9aa133364700a7ab8df52f62c3e0":{
      "scriptId":"u0"},
    "380517193f814385b8db17a30e6dac2b":{
      "scriptId":"u1"},
    "ccc8af41af9a4e46b024a1219134329c":{
      "scriptId":"u2"},
    "5fd204571eb94359b97ecfa8d9374688":{
      "scriptId":"u3"},
    "0effd6767de84f729c8b1aef5409363d":{
      "scriptId":"u4"},
    "ebf2c7f27c7a4a9dab2d62684f1a9f03":{
      "scriptId":"u5"},
    "d7e30b71812441fc8dcfeb6147f6b12b":{
      "scriptId":"u6"},
    "f9f70662d9b04d4192590519a3a3567c":{
      "scriptId":"u7"},
    "aba31bc5177c49e29de63ef57038e218":{
      "scriptId":"u8"},
    "e0bd89fdef3d4cb3bf38cbdab7b4c1c0":{
      "scriptId":"u9"},
    "8610a857463447738a50f6e7379248d1":{
      "scriptId":"u10"},
    "5aa908b9a60e4eedb8cf008aa538a408":{
      "scriptId":"u11"},
    "0765cb51b3ea4948a01b8546727d69e6":{
      "scriptId":"u12"},
    "9cd6e8be1473490db1222c1541cd99d3":{
      "scriptId":"u13"},
    "85c361b1b9cc4022bd20ff3cce684897":{
      "scriptId":"u14"},
    "f39f6c150e4b469dab4f535787a41851":{
      "scriptId":"u15"},
    "880703a9b3684020bfe63dd2b9fe759e":{
      "scriptId":"u16"},
    "aa74063522ee42b9a2e774fe700883fa":{
      "scriptId":"u17"},
    "9abb4ee411c2466895f83512e18c96ea":{
      "scriptId":"u18"},
    "fdbfc7ce11f64cd48c62e4a4af1d4e39":{
      "scriptId":"u19"},
    "62c6e8da0b394bc69281f152f38160f0":{
      "scriptId":"u20"},
    "c1a789de973b4f82bbead6cf242082d2":{
      "scriptId":"u21"},
    "82de007e847447f2956d7816b1a82d51":{
      "scriptId":"u22"},
    "5027c1c66cf44374ae25586cfc112248":{
      "scriptId":"u23"},
    "3fd1471023bd4fa08597f762e97b8293":{
      "scriptId":"u24"},
    "c8d207ac82c2420d972f4a529fc89d65":{
      "scriptId":"u25"},
    "5ca4411249594ad5a4919d192d0ddf99":{
      "scriptId":"u26"},
    "01b1223bf0574c77adcb2a62d133be31":{
      "scriptId":"u27"}}});