$axure.loadCurrentPage({
  "url":"社区.html",
  "generationDate":new Date(1426560721000.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"64a469474682416da8303af6be32e1f3",
    "type":"Axure:Page",
    "name":"社区",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c622be15d32e4eb0bc139792f78ab2dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4b545f75b645b49e20f0be83eba7b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"7b34d4d31b1649d78c21565f4c1c65de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312623869aaf4b82b83edba82c364755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"7d32a785dad74640b9ee8f6e80edbca3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1068},
            "size":{
              "width":640,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2373f1dc8cf04780a651549a55e5d512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1068},
                "size":{
                  "width":640,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"af5f83493835441c9b34809126dbe0b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":157,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089664bba82f47209f0998fa95ff6324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c7dac60b5214f3f960003e635607e5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":49,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48636d601a0a4cedaadb09e9920dcf42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5987685d086416a94c25e3796c1a6b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":372,
              "y":1098},
            "size":{
              "width":91,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bc89533e28d44cabd986156699011e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":372,
                  "y":1098},
                "size":{
                  "width":91,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19949f5f535145968014cf92a748222e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":510,
              "y":1098},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f9d59db9dd74d2987ab7f2e015995d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":510,
                  "y":1098},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a493d7724bab490e8a1089b0777a8470",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9cb4f86114041a8b096e8f77a425b8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"ae7c7f5752694b80b61802196bf65ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":297,
              "y":80},
            "size":{
              "width":86,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b99999d2ce44608cafcb3385679875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":297,
                  "y":80},
                "size":{
                  "width":86,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcdd9a2287804b70ac38f551247250f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff1c2036a874d9fad7a7f53573d3647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"f7fc8d8fa5ee4f58873e48a0df38185c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":169},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cefe43e9ebb94e4a9875672988c03ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":169},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u22.png"}},
{
          "id":"40d7747f1b8a4e7d8a51e91392c57536",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":86,
              "y":173},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ffd6206bd3a4ac7aba07b25aa0293a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":86,
                  "y":173},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b534b9a10b6b49728207fe6f013c82fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":264,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49f0d7c1be244e15944dab57fed43e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04d976a8fbd641459d7ddb530b73ae79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":228},
            "size":{
              "width":640,
              "height":301}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7d3c0782cb41d1911bfd20b4de2e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":228},
                "size":{
                  "width":640,
                  "height":301}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u26.png"}},
{
          "id":"43f563c5f2114c61a98cc8c8133fbb89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":246},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3120d1ea557343879c592377727c3417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":246},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"7aa898ec4715424b837d3da9817bd9a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":124,
              "y":254},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9cc444ab62447a1b7bbd3bb7d3a4edc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":124,
                  "y":254},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"509f7b97a5e8484fb3d299307a6527c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":354},
            "size":{
              "width":606,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce4b217de5434b27bf6633196ba286cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":354},
                "size":{
                  "width":606,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"258083fe678b4508936b2ad64c913195",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":124,
              "y":300},
            "size":{
              "width":91,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeba9b64c88347bda2844f8472af285a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":124,
                  "y":300},
                "size":{
                  "width":91,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a0a22bf21b0415e845c80d01f985565",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":413,
              "y":480},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b1f805973284dd0b002a6056c3e78b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":413,
                  "y":480},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90ba05e7c831403b96f5b4e2ed8da4b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":571,
              "y":480},
            "size":{
              "width":79,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e04ca448f1e5401aa9e25236478849c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":571,
                  "y":480},
                "size":{
                  "width":79,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd4c95e1e4de4895968c5e53d2fb3ba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":476,
              "y":483},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d6772eea2e438e8032f8f8436440ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":476,
                  "y":483},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aec1694378404b25aed4946c0ffe461a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":603,
              "y":483},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d91d042b792453886ebf38a782519e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":603,
                  "y":483},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"983004f42fc94e8cb758ec1b124ea448",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":224,
              "y":480},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0219152365496a89cfef9e71d17439",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":224,
                  "y":480},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1114d767aed2458caade203a91c8eaa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":287,
              "y":483},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b95a6dd7744ae7a21d52646838f666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":287,
                  "y":483},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23f6e8dac5ac44bbb8499bd2815e60ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":559,
              "y":246},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0030fe43d8d146abaf8140c3fd8c900e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":559,
                  "y":246},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u48.png"}},
{
          "id":"f6581846e2234ee19b4412c4b9c14b30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":559,
              "y":80},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afb0f5db570d48a4aadd253737024fd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":559,
                  "y":80},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u48.png"}},
{
          "id":"e959718af50d42d38152d94b0f87eb28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":550},
            "size":{
              "width":640,
              "height":301}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1288632cbf234d58846dc8470a6cb6d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":550},
                "size":{
                  "width":640,
                  "height":301}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u26.png"}},
{
          "id":"3bf34ec27e204b938c23a91e4f2ca2c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":568},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3266f24f1bf648b1a21f863db467a201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":568},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"99f9a18e1f354b80a6a181ef6adebfa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":124,
              "y":576},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d56c122790874401911bc995ff2a5eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":124,
                  "y":576},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de68d80166754b308bcbfda0ed8b0176",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":676},
            "size":{
              "width":606,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86f8b5a2efdc48d5ac9cbe40c740f46e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":676},
                "size":{
                  "width":606,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f50a0ea3e83c42a5820397ce7be72a9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":124,
              "y":622},
            "size":{
              "width":91,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5eae218a4c42689f204173d117635a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":124,
                  "y":622},
                "size":{
                  "width":91,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbadb69e25f14e22b213a2476dcf5165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":413,
              "y":802},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f86d0b155c452da4d96fce47a61c3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":413,
                  "y":802},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0dfb50569ea4ae9b06e4bd678bdac3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":571,
              "y":802},
            "size":{
              "width":79,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88cf51492b0448d3a7704efbabbb66aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":571,
                  "y":802},
                "size":{
                  "width":79,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b93ec8580e29446685635a06621a2012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":476,
              "y":805},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7ef4517ed747a4987c472a3085337e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":476,
                  "y":805},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43498775e6c491289aa20ea0fffdecc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":603,
              "y":805},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7980eb199fe1407ea4f81e1b453bbc75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":603,
                  "y":805},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"036bd44fb2624576b5a20744c6eb8c6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":224,
              "y":802},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b74d0f97b9b49fdbe84e1def07a8784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":224,
                  "y":802},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0011b0a8d324fd89208c1112053d6dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":287,
              "y":805},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3af310ed78b4643af71e0e768a122ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":287,
                  "y":805},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2a62fc7bd21454fa8183b1b62ebef82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":559,
              "y":568},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ebfe84c8b64168927d43cfa0b4a40b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":559,
                  "y":568},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u48.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c622be15d32e4eb0bc139792f78ab2dc":{
      "scriptId":"u0"},
    "4e4b545f75b645b49e20f0be83eba7b6":{
      "scriptId":"u1"},
    "7b34d4d31b1649d78c21565f4c1c65de":{
      "scriptId":"u2"},
    "312623869aaf4b82b83edba82c364755":{
      "scriptId":"u3"},
    "7d32a785dad74640b9ee8f6e80edbca3":{
      "scriptId":"u4"},
    "2373f1dc8cf04780a651549a55e5d512":{
      "scriptId":"u5"},
    "af5f83493835441c9b34809126dbe0b9":{
      "scriptId":"u6"},
    "089664bba82f47209f0998fa95ff6324":{
      "scriptId":"u7"},
    "9c7dac60b5214f3f960003e635607e5f":{
      "scriptId":"u8"},
    "48636d601a0a4cedaadb09e9920dcf42":{
      "scriptId":"u9"},
    "d5987685d086416a94c25e3796c1a6b0":{
      "scriptId":"u10"},
    "3bc89533e28d44cabd986156699011e4":{
      "scriptId":"u11"},
    "19949f5f535145968014cf92a748222e":{
      "scriptId":"u12"},
    "2f9d59db9dd74d2987ab7f2e015995d2":{
      "scriptId":"u13"},
    "a493d7724bab490e8a1089b0777a8470":{
      "scriptId":"u14"},
    "d9cb4f86114041a8b096e8f77a425b8c":{
      "scriptId":"u15"},
    "ae7c7f5752694b80b61802196bf65ab3":{
      "scriptId":"u16"},
    "28b99999d2ce44608cafcb3385679875":{
      "scriptId":"u17"},
    "fcdd9a2287804b70ac38f551247250f2":{
      "scriptId":"u18"},
    "dff1c2036a874d9fad7a7f53573d3647":{
      "scriptId":"u19"},
    "f7fc8d8fa5ee4f58873e48a0df38185c":{
      "scriptId":"u20"},
    "cefe43e9ebb94e4a9875672988c03ebc":{
      "scriptId":"u21"},
    "40d7747f1b8a4e7d8a51e91392c57536":{
      "scriptId":"u22"},
    "5ffd6206bd3a4ac7aba07b25aa0293a6":{
      "scriptId":"u23"},
    "b534b9a10b6b49728207fe6f013c82fb":{
      "scriptId":"u24"},
    "49f0d7c1be244e15944dab57fed43e8c":{
      "scriptId":"u25"},
    "04d976a8fbd641459d7ddb530b73ae79":{
      "scriptId":"u26"},
    "0a7d3c0782cb41d1911bfd20b4de2e66":{
      "scriptId":"u27"},
    "43f563c5f2114c61a98cc8c8133fbb89":{
      "scriptId":"u28"},
    "3120d1ea557343879c592377727c3417":{
      "scriptId":"u29"},
    "7aa898ec4715424b837d3da9817bd9a4":{
      "scriptId":"u30"},
    "b9cc444ab62447a1b7bbd3bb7d3a4edc":{
      "scriptId":"u31"},
    "509f7b97a5e8484fb3d299307a6527c2":{
      "scriptId":"u32"},
    "ce4b217de5434b27bf6633196ba286cb":{
      "scriptId":"u33"},
    "258083fe678b4508936b2ad64c913195":{
      "scriptId":"u34"},
    "aeba9b64c88347bda2844f8472af285a":{
      "scriptId":"u35"},
    "5a0a22bf21b0415e845c80d01f985565":{
      "scriptId":"u36"},
    "1b1f805973284dd0b002a6056c3e78b0":{
      "scriptId":"u37"},
    "90ba05e7c831403b96f5b4e2ed8da4b4":{
      "scriptId":"u38"},
    "e04ca448f1e5401aa9e25236478849c9":{
      "scriptId":"u39"},
    "fd4c95e1e4de4895968c5e53d2fb3ba8":{
      "scriptId":"u40"},
    "11d6772eea2e438e8032f8f8436440ef":{
      "scriptId":"u41"},
    "aec1694378404b25aed4946c0ffe461a":{
      "scriptId":"u42"},
    "5d91d042b792453886ebf38a782519e5":{
      "scriptId":"u43"},
    "983004f42fc94e8cb758ec1b124ea448":{
      "scriptId":"u44"},
    "7a0219152365496a89cfef9e71d17439":{
      "scriptId":"u45"},
    "1114d767aed2458caade203a91c8eaa0":{
      "scriptId":"u46"},
    "45b95a6dd7744ae7a21d52646838f666":{
      "scriptId":"u47"},
    "23f6e8dac5ac44bbb8499bd2815e60ea":{
      "scriptId":"u48"},
    "0030fe43d8d146abaf8140c3fd8c900e":{
      "scriptId":"u49"},
    "f6581846e2234ee19b4412c4b9c14b30":{
      "scriptId":"u50"},
    "afb0f5db570d48a4aadd253737024fd7":{
      "scriptId":"u51"},
    "e959718af50d42d38152d94b0f87eb28":{
      "scriptId":"u52"},
    "1288632cbf234d58846dc8470a6cb6d2":{
      "scriptId":"u53"},
    "3bf34ec27e204b938c23a91e4f2ca2c2":{
      "scriptId":"u54"},
    "3266f24f1bf648b1a21f863db467a201":{
      "scriptId":"u55"},
    "99f9a18e1f354b80a6a181ef6adebfa1":{
      "scriptId":"u56"},
    "d56c122790874401911bc995ff2a5eff":{
      "scriptId":"u57"},
    "de68d80166754b308bcbfda0ed8b0176":{
      "scriptId":"u58"},
    "86f8b5a2efdc48d5ac9cbe40c740f46e":{
      "scriptId":"u59"},
    "f50a0ea3e83c42a5820397ce7be72a9e":{
      "scriptId":"u60"},
    "be5eae218a4c42689f204173d117635a":{
      "scriptId":"u61"},
    "bbadb69e25f14e22b213a2476dcf5165":{
      "scriptId":"u62"},
    "c1f86d0b155c452da4d96fce47a61c3f":{
      "scriptId":"u63"},
    "e0dfb50569ea4ae9b06e4bd678bdac3a":{
      "scriptId":"u64"},
    "88cf51492b0448d3a7704efbabbb66aa":{
      "scriptId":"u65"},
    "b93ec8580e29446685635a06621a2012":{
      "scriptId":"u66"},
    "1d7ef4517ed747a4987c472a3085337e":{
      "scriptId":"u67"},
    "c43498775e6c491289aa20ea0fffdecc":{
      "scriptId":"u68"},
    "7980eb199fe1407ea4f81e1b453bbc75":{
      "scriptId":"u69"},
    "036bd44fb2624576b5a20744c6eb8c6a":{
      "scriptId":"u70"},
    "9b74d0f97b9b49fdbe84e1def07a8784":{
      "scriptId":"u71"},
    "e0011b0a8d324fd89208c1112053d6dc":{
      "scriptId":"u72"},
    "b3af310ed78b4643af71e0e768a122ea":{
      "scriptId":"u73"},
    "b2a62fc7bd21454fa8183b1b62ebef82":{
      "scriptId":"u74"},
    "d3ebfe84c8b64168927d43cfa0b4a40b":{
      "scriptId":"u75"}}});