$axure.loadCurrentPage({
  "url":"执照／身份证.html",
  "generationDate":new Date(1431411288626.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"99bec03597704e61b553d3ae15ad6f15",
    "type":"Axure:Page",
    "name":"执照／身份证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ae3d37e50fd9437098d2467d4bb2c039",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b0f81757692452da9f43696eb5ffad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"bed8a8f75afa4c3fb6979cecf0942aa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbedd3315bba49138e31265b4864a799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"a834780d3b85417381b6fccb5f808996",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eda722bb442481bba2e581ccc88b598",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"6d1bc5df8ccc4d1b90a3abd69b460161",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3b13d5990d24384a1cff15e67ae4cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"6f7fba248c6e4e108203765ed02c3a39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":131,
              "y":216},
            "size":{
              "width":225,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6acdd8b2f2ef4271b804f613c21f3adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":131,
                  "y":216},
                "size":{
                  "width":225,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32184a904160492ab10c98d116ab351e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":30,
              "y":180},
            "size":{
              "width":91,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9282ec2561240e99ef3a4322d982a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":30,
                  "y":180},
                "size":{
                  "width":91,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/执照／身份证/u10.png"}},
{
          "id":"f6eb008be3044631bf55b56be326f8fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":265,
              "y":80},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506ad7cf065c4f9eb4035ba6bea13b50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":265,
                  "y":80},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4379bdb7f1a449ce9dee7eacb2e16332",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba06ddba6b6c480c86bcc7b7ff17ac35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47c13f7668a042ee87ecf023cb2a5003",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":557,
              "y":80},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f8adeaf44a74ac9b93add7d12f2fdef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":557,
                  "y":80},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abc5eacb698a408fb52fed4ba209c9a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":289},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce06c575a1d64d2a99d8f61b9ee6c9d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":289},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"67b68ab87b274b3fb335d57fc208bc02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":131,
              "y":335},
            "size":{
              "width":253,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46cccc8cb60a468cb7f6dc800a3ffefd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":131,
                  "y":335},
                "size":{
                  "width":253,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e5d6bf3e94e49659a29ed66209dbfd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":30,
              "y":299},
            "size":{
              "width":91,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dbcf985d71340d28aae3c8d8f6f0e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":30,
                  "y":299},
                "size":{
                  "width":91,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/执照／身份证/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ae3d37e50fd9437098d2467d4bb2c039":{
      "scriptId":"u0"},
    "4b0f81757692452da9f43696eb5ffad8":{
      "scriptId":"u1"},
    "bed8a8f75afa4c3fb6979cecf0942aa2":{
      "scriptId":"u2"},
    "bbedd3315bba49138e31265b4864a799":{
      "scriptId":"u3"},
    "a834780d3b85417381b6fccb5f808996":{
      "scriptId":"u4"},
    "9eda722bb442481bba2e581ccc88b598":{
      "scriptId":"u5"},
    "6d1bc5df8ccc4d1b90a3abd69b460161":{
      "scriptId":"u6"},
    "e3b13d5990d24384a1cff15e67ae4cf5":{
      "scriptId":"u7"},
    "6f7fba248c6e4e108203765ed02c3a39":{
      "scriptId":"u8"},
    "6acdd8b2f2ef4271b804f613c21f3adc":{
      "scriptId":"u9"},
    "32184a904160492ab10c98d116ab351e":{
      "scriptId":"u10"},
    "b9282ec2561240e99ef3a4322d982a9b":{
      "scriptId":"u11"},
    "f6eb008be3044631bf55b56be326f8fe":{
      "scriptId":"u12"},
    "506ad7cf065c4f9eb4035ba6bea13b50":{
      "scriptId":"u13"},
    "4379bdb7f1a449ce9dee7eacb2e16332":{
      "scriptId":"u14"},
    "ba06ddba6b6c480c86bcc7b7ff17ac35":{
      "scriptId":"u15"},
    "47c13f7668a042ee87ecf023cb2a5003":{
      "scriptId":"u16"},
    "0f8adeaf44a74ac9b93add7d12f2fdef":{
      "scriptId":"u17"},
    "abc5eacb698a408fb52fed4ba209c9a5":{
      "scriptId":"u18"},
    "ce06c575a1d64d2a99d8f61b9ee6c9d4":{
      "scriptId":"u19"},
    "67b68ab87b274b3fb335d57fc208bc02":{
      "scriptId":"u20"},
    "46cccc8cb60a468cb7f6dc800a3ffefd":{
      "scriptId":"u21"},
    "8e5d6bf3e94e49659a29ed66209dbfd8":{
      "scriptId":"u22"},
    "2dbcf985d71340d28aae3c8d8f6f0e2c":{
      "scriptId":"u23"}}});