package com.gotye.api;


/**
 * 事件code
 *
 */
public enum GotyeEventCode {
    
    GotyeEventCodeLogin,
    GotyeEventCodeLogout,
    GotyeEventCodeGetProfile,
    GotyeEventCodeGetUserInfo,
    GotyeEventCodeModifyUserInfo,
    GotyeEventCodeGetFriendList,
    GotyeEventCodeGetBlockedList,
    GotyeEventCodeSearchUserList,
    GotyeEventCodeAddFriend,
    GotyeEventCodeAddBlocked,
    GotyeEventCodeRemoveFriend,
    GotyeEventCodeRemoveBlocked,
    GotyeEventCodeGetRoomList,
    GotyeEventCodeEnterRoom,
    GotyeEventCodeLeaveRoom,
    GotyeEventCodeGetUserList,
    GotyeEventCodeGetHistoryMessageList,
    GotyeEventCodeSearchGroup,
    GotyeEventCodeCreateGroup,
    GotyeEventCodeJoinGroup,
    GotyeEventCodeLeaveGroup,
    GotyeEventCodeDismissGroup,
	GotyeEventCodeKickoutUser,
	GotyeEventCodeChangeGroupOwner,
	GotyeEventCodeUserJoinGroup,
    GotyeEventCodeUserLeaveGroup,
    GotyeEventCodeUserDismissGroup,
    GotyeEventCodeUserKickedFromGroup,
    GotyeEventCodeGetGroupList,
    GotyeEventCodeGetGroupInfo,
    GotyeEventCodeModifyGroupInfo,
    GotyeEventCodeGetGroupUserList,
    GotyeEventCodeReceiveNotify,
    GotyeEventCodeGetOfflineMessageList,
    GotyeEventCodeSendMessage,
    GotyeEventCodeReceiveMessage,
    GotyeEventCodeDownloadMessage,
    GotyeEventCodeStartTalk,
    GotyeEventCodeStopTalk, 
    GotyeEventCodeDownloadMedia, 
    GotyeEventCodePlayStart,
    GotyeEventCodeRealPlayStart,
    GotyeEventCodePlaying,
    GotyeEventCodePlayStop,
    GotyeEventCodeReport,
    GotyeEventCodeDecodeFinished,
    GotyeEventCodeSendNotify,
    GotyeEventCodeReconnecting,
    GotyeEventCodeCustomerService,
    GotyeEventCodeOutputAudioData,
    GotyeEventCodeSendPraise,	///< Presenter APIs
    GotyeEventCodeGetPraise,
    GotyeEventCodePraise,
    GotyeEventCodeEnterLiveRoom,
    GotyeEventCodeGetChannelInfo,
    GotyeEventCodeSetChannel,
    GotyeEventCodeCloseChannel,
    GotyeEventCodeUpdateChannelInfo,
    GotyeEventCodeGetRoomOnlineNum,
}
