$axure.loadCurrentPage({
  "url":"同行.html",
  "generationDate":new Date(1429163222474.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92eb44691651481986dae0aa8dea08ff",
    "type":"Axure:Page",
    "name":"同行",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b4bdf4fb3b6f4c9eac9fd708ac065164",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf8d4aa65174879825afc02ed34fe95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"3b716d92de324420978d649efee527bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc2b0cd447b94b1e94765233c550a09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"c7fd74afbd6143118ad2791fe343aa2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1068},
            "size":{
              "width":640,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"160965b2607d4a9e8c3066480165534c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1068},
                "size":{
                  "width":640,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"35f59995465f4db487d2414c81eabf8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":157,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8311ee33e962406c9f9c7f6df311fd93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4b0766cae414533ae5c149cb80e01ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":49,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2e74739441c4939a34896b74c4fd1ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b6d2cbb036245cb8eb193026c858582",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":372,
              "y":1098},
            "size":{
              "width":91,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f428c748b64878987e0a07c4c26fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":372,
                  "y":1098},
                "size":{
                  "width":91,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99716aebe5c74109be7222a5acdf18d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":510,
              "y":1098},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36e1abf6a93444c8f8a1cd00cb4e42e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":510,
                  "y":1098},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d8132a8b7014787a8cc3f91d93dc486",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041039fb20a24dfb886fdc37da2dc528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"c68db1447ecb44cda3f695ab430cd840",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":282,
              "y":80},
            "size":{
              "width":116,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783de00825b642f59094b6a08036fbd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":282,
                  "y":80},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ca8773459ee4e79ad4414d122a6f3bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":300},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cab9bb3251b41d3a6438dc74b2e512d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":300},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"1347b4010296481e981c4bce7d911fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":316},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3768e043f8c4afeb6dff624bbc1723d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":316},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"f31fbef67a8b4f4cb3356284f1116852",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":316},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eceeca3846254d0882c6f02d1008b323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":316},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58d2adc4d26f44beb491fdf636f5d047",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":362},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eba3bd6caf14a2285f5dead01c304b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":362},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21371d3413bd4d849d79b3ee16fff42e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":235,
              "y":310},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"def492f408e2429ca7bcf88b3b7dfba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":235,
                  "y":310},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"59f9cf0d85fb4225a178c50ed29c54bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":419},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff650931905c44a6a8293b76a6d37548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":419},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"24e02c291f02405d852d7be6d2f59992",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":435},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a500b05e8740b6af2d7643f93c4881",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":435},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"56c3764e827145498b1a6f0dc32eac57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":435},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3ae2c09640d4dc391f8d13935c96b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":435},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ea608bd1285465db0179a9f1d32b30c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":207,
              "y":429},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf43f31af74430f8b9df6e5deb463f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":207,
                  "y":429},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"16e4f0ec1bde48dab0a3d67db8c4e605",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":257,
              "y":437},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda9602ede6944c0a733105a3528d811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":257,
                  "y":437},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15aee37375cc4fd29079e2c49d045dc5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":547,
              "y":74},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"363fa2c66de4492e8fd2795f82093d59",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"4aa521c0c4f644b1bc7d550f559a2b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":613,
              "y":340},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa9b6fdc7fb64fe6879d204db7bbf1f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":613,
                  "y":340},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bac80bcd7a324a5dac79a39a32490bce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":485},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ce5170ee4c412b9a4c4bf8782d9fb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":485},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81726e0bb0a1498da6aefce56aa6ee7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":613,
              "y":458},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08196a1944b4067b8785ab88b3f9f2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":613,
                  "y":458},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30b37671f835436998f62b7162e19bd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb88a4f732fe4fcfa6b162d04ec576b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"2ec132fb97e24289878ecbb84c179c79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":169},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ad073356b74116ba7ac5b1321892a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":169},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"2966d97d63134595952a775c59ad2c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":194},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b028ce8b3a4418d9939be8d53341e54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":194},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"677fe59256494d7d9efc3fb3fc382310",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":538},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dd7f4ac19d846b696a0d753849dd4f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":538},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"124b1f51c54948f6b648bdb44d564470",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":554},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"160759785ec84c0dba78b59bf113d399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":554},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"c86c93be7c074102bda6d83d2faba1a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":554},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a4dab2e051c4d0aa1bc929a22979374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":554},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3063eaf59b744b81a3a4631ba3d1bc2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":600},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"836cf70ef3e34a189aa4808d75b76b00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":600},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ce4cebd4f1c4e03bd6fbe28a884df6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":207,
              "y":548},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea1674ef406a4725866b2c702948eb8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":207,
                  "y":548},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"381f789cdec74675acfa64d0c64c8863",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":613,
              "y":578},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11bd1149f1ce4e7aabddd55aa072f7a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":613,
                  "y":578},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1705833ef3f44e5c984e8d6b6cbcec23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":257,
              "y":555},
            "size":{
              "width":65,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"972b11ec56504fd8a13ef8ae140dcdb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":257,
                  "y":555},
                "size":{
                  "width":65,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc1d31500bcc41b4aa72177535f58868",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":285,
              "y":316},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd23f1a8152441abac0f53324090c151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":285,
                  "y":316},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c56d2c891ab34b27852e1565bf25e284",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":264,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50a8ff5b98f04b8d8dd57958010abee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b4bdf4fb3b6f4c9eac9fd708ac065164":{
      "scriptId":"u0"},
    "caf8d4aa65174879825afc02ed34fe95":{
      "scriptId":"u1"},
    "3b716d92de324420978d649efee527bd":{
      "scriptId":"u2"},
    "cc2b0cd447b94b1e94765233c550a09a":{
      "scriptId":"u3"},
    "c7fd74afbd6143118ad2791fe343aa2a":{
      "scriptId":"u4"},
    "160965b2607d4a9e8c3066480165534c":{
      "scriptId":"u5"},
    "35f59995465f4db487d2414c81eabf8f":{
      "scriptId":"u6"},
    "8311ee33e962406c9f9c7f6df311fd93":{
      "scriptId":"u7"},
    "d4b0766cae414533ae5c149cb80e01ab":{
      "scriptId":"u8"},
    "f2e74739441c4939a34896b74c4fd1ea":{
      "scriptId":"u9"},
    "9b6d2cbb036245cb8eb193026c858582":{
      "scriptId":"u10"},
    "92f428c748b64878987e0a07c4c26fdf":{
      "scriptId":"u11"},
    "99716aebe5c74109be7222a5acdf18d5":{
      "scriptId":"u12"},
    "d36e1abf6a93444c8f8a1cd00cb4e42e":{
      "scriptId":"u13"},
    "3d8132a8b7014787a8cc3f91d93dc486":{
      "scriptId":"u14"},
    "041039fb20a24dfb886fdc37da2dc528":{
      "scriptId":"u15"},
    "c68db1447ecb44cda3f695ab430cd840":{
      "scriptId":"u16"},
    "783de00825b642f59094b6a08036fbd0":{
      "scriptId":"u17"},
    "2ca8773459ee4e79ad4414d122a6f3bc":{
      "scriptId":"u18"},
    "7cab9bb3251b41d3a6438dc74b2e512d":{
      "scriptId":"u19"},
    "1347b4010296481e981c4bce7d911fdc":{
      "scriptId":"u20"},
    "f3768e043f8c4afeb6dff624bbc1723d":{
      "scriptId":"u21"},
    "f31fbef67a8b4f4cb3356284f1116852":{
      "scriptId":"u22"},
    "eceeca3846254d0882c6f02d1008b323":{
      "scriptId":"u23"},
    "58d2adc4d26f44beb491fdf636f5d047":{
      "scriptId":"u24"},
    "4eba3bd6caf14a2285f5dead01c304b0":{
      "scriptId":"u25"},
    "21371d3413bd4d849d79b3ee16fff42e":{
      "scriptId":"u26"},
    "def492f408e2429ca7bcf88b3b7dfba4":{
      "scriptId":"u27"},
    "59f9cf0d85fb4225a178c50ed29c54bd":{
      "scriptId":"u28"},
    "ff650931905c44a6a8293b76a6d37548":{
      "scriptId":"u29"},
    "24e02c291f02405d852d7be6d2f59992":{
      "scriptId":"u30"},
    "65a500b05e8740b6af2d7643f93c4881":{
      "scriptId":"u31"},
    "56c3764e827145498b1a6f0dc32eac57":{
      "scriptId":"u32"},
    "b3ae2c09640d4dc391f8d13935c96b9a":{
      "scriptId":"u33"},
    "0ea608bd1285465db0179a9f1d32b30c":{
      "scriptId":"u34"},
    "fbf43f31af74430f8b9df6e5deb463f2":{
      "scriptId":"u35"},
    "16e4f0ec1bde48dab0a3d67db8c4e605":{
      "scriptId":"u36"},
    "fda9602ede6944c0a733105a3528d811":{
      "scriptId":"u37"},
    "15aee37375cc4fd29079e2c49d045dc5":{
      "scriptId":"u38"},
    "363fa2c66de4492e8fd2795f82093d59":{
      "scriptId":"u39"},
    "4aa521c0c4f644b1bc7d550f559a2b04":{
      "scriptId":"u40"},
    "fa9b6fdc7fb64fe6879d204db7bbf1f9":{
      "scriptId":"u41"},
    "bac80bcd7a324a5dac79a39a32490bce":{
      "scriptId":"u42"},
    "89ce5170ee4c412b9a4c4bf8782d9fb5":{
      "scriptId":"u43"},
    "81726e0bb0a1498da6aefce56aa6ee7b":{
      "scriptId":"u44"},
    "b08196a1944b4067b8785ab88b3f9f2f":{
      "scriptId":"u45"},
    "30b37671f835436998f62b7162e19bd6":{
      "scriptId":"u46"},
    "cb88a4f732fe4fcfa6b162d04ec576b1":{
      "scriptId":"u47"},
    "2ec132fb97e24289878ecbb84c179c79":{
      "scriptId":"u48"},
    "26ad073356b74116ba7ac5b1321892a2":{
      "scriptId":"u49"},
    "2966d97d63134595952a775c59ad2c92":{
      "scriptId":"u50"},
    "3b028ce8b3a4418d9939be8d53341e54":{
      "scriptId":"u51"},
    "677fe59256494d7d9efc3fb3fc382310":{
      "scriptId":"u52"},
    "3dd7f4ac19d846b696a0d753849dd4f0":{
      "scriptId":"u53"},
    "124b1f51c54948f6b648bdb44d564470":{
      "scriptId":"u54"},
    "160759785ec84c0dba78b59bf113d399":{
      "scriptId":"u55"},
    "c86c93be7c074102bda6d83d2faba1a2":{
      "scriptId":"u56"},
    "2a4dab2e051c4d0aa1bc929a22979374":{
      "scriptId":"u57"},
    "3063eaf59b744b81a3a4631ba3d1bc2f":{
      "scriptId":"u58"},
    "836cf70ef3e34a189aa4808d75b76b00":{
      "scriptId":"u59"},
    "2ce4cebd4f1c4e03bd6fbe28a884df6e":{
      "scriptId":"u60"},
    "ea1674ef406a4725866b2c702948eb8b":{
      "scriptId":"u61"},
    "381f789cdec74675acfa64d0c64c8863":{
      "scriptId":"u62"},
    "11bd1149f1ce4e7aabddd55aa072f7a3":{
      "scriptId":"u63"},
    "1705833ef3f44e5c984e8d6b6cbcec23":{
      "scriptId":"u64"},
    "972b11ec56504fd8a13ef8ae140dcdb4":{
      "scriptId":"u65"},
    "fc1d31500bcc41b4aa72177535f58868":{
      "scriptId":"u66"},
    "fd23f1a8152441abac0f53324090c151":{
      "scriptId":"u67"},
    "c56d2c891ab34b27852e1565bf25e284":{
      "scriptId":"u68"},
    "50a8ff5b98f04b8d8dd57958010abee7":{
      "scriptId":"u69"}}});