$axure.loadCurrentPage({
  "url":"患者.html",
  "generationDate":new Date(1426560718697.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c1272577b2ef43ada6b74756adbdc148",
    "type":"Axure:Page",
    "name":"患者",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b8a3fd1d4d64728bd146a5486fabc87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acea241d3ce64b079dec671441139313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"cc3e005b3e34424994d03db79564d617",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d5405a98f674766a8c9d49c1bcfc951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"929a181acf64443d9fc21790d9254b87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1068},
            "size":{
              "width":640,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a8e20a6901048af8aac59778a78e086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1068},
                "size":{
                  "width":640,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"d66a8d19656348b9ae4adecd0831299e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":157,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e64e14126a4befbc01461152a18cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0105f6518b24afa8c95cc742363d69c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":49,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5faf9bd30b814fda9622ae3fb2a3579f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f75f7a99f864b6a807fbeb792acf415",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":372,
              "y":1098},
            "size":{
              "width":91,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca044510f23f40c69fe39e2b16306419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":372,
                  "y":1098},
                "size":{
                  "width":91,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"836c0904cfde431f9ff9203e8900c013",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":510,
              "y":1098},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76170a8ab634900a6a8636a5419599c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":510,
                  "y":1098},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3fc43e6ac734237918067c718b7223d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b823403603c4542a266be5396dd301d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"913d4553064440e6b84b75c225640320",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":264,
              "y":80},
            "size":{
              "width":153,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53364cef302a4da98feb6e4b0cdb3847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":264,
                  "y":80},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc485a3404b34726bd5d4136faf0592b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996f337dd880472ab4c17d3e0f42d401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"6fbb52fded18488fa382174418498264",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":228},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fece8bc181ea4f2ea006012153ab5a35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":228},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"3105f072c6a2427896face92cc3bdbe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":172},
            "size":{
              "width":253,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26162b90a13f4036a17bb60329466a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":172},
                "size":{
                  "width":253,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1b680c5ce1c4234ac0263fe9733cac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":244},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e565720ed8a14c41816a92a289e7ea33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":244},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"a721a35526ae4b368f286567426f8292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":244},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f28c5a3f44824a14af9230b28b32e053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":244},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9794f57eb21c48e1a8da91c23597165f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":290},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfe1b8f6919e41599143424ee4dd9803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":290},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30a9cb2e3a2248bca80199831e4f8ebd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":235,
              "y":238},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c94214a4f6cb406d978af3d85cd833fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":235,
                  "y":238},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"dae63080cabc418e97061ad15a042345",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":285,
              "y":246},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3798da33fc864b7899342b587b63c22c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":285,
                  "y":246},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0cd6859e1ed4330a23c0578f79b399d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":347},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2a871e6f9e8443da6cb024dcee7cd8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":347},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"cd789d0eb01a48b8a54708081cd53089",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":363},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81072a6ab6d2429da9868c9317390937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":363},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"34c3a97b659a466db9f365d5815698f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":363},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abbbfe80ac304ba382b22c54cdc3b62c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":363},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64e6b5e199b64cfb979fe573b1d47eaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":207,
              "y":357},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b1e83746b3a4d82983b4e548e214dd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":207,
                  "y":357},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"3ef62ceead7f4ceb887a1e9998bb7841",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":257,
              "y":365},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6634852d46084fc7aa34116765b934ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":257,
                  "y":365},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5389947bd11d4011b6c23ee1580e14cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":299,
              "y":179},
            "size":{
              "width":41,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb5eae5a69a41cab5c40d1ddcff0eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":299,
                  "y":179},
                "size":{
                  "width":41,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd372ef053304ee485878ee8cc2ff242",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":547,
              "y":74},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"94bae4f136ec4471947f1c7bfbb9711a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"5f6b9bddd3594f0eb3d4c2c88973d3b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":613,
              "y":268},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc364315d3d9417e9d3c2f586dc3eea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":613,
                  "y":268},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3140bdf82f264df296ab342cefa878d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":413},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042a7b8a4fef4f17b317dd049b03c6e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":413},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f67449f746904b77b38df2ce855e083d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":613,
              "y":386},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c5baca75c14c1babe5f8e69ae40f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":613,
                  "y":386},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da50c94e6c2b46d89263b3e06ef88549",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":264,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6187e02c4d294239ad1976ca0fbf6dcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1b8a3fd1d4d64728bd146a5486fabc87":{
      "scriptId":"u0"},
    "acea241d3ce64b079dec671441139313":{
      "scriptId":"u1"},
    "cc3e005b3e34424994d03db79564d617":{
      "scriptId":"u2"},
    "2d5405a98f674766a8c9d49c1bcfc951":{
      "scriptId":"u3"},
    "929a181acf64443d9fc21790d9254b87":{
      "scriptId":"u4"},
    "2a8e20a6901048af8aac59778a78e086":{
      "scriptId":"u5"},
    "d66a8d19656348b9ae4adecd0831299e":{
      "scriptId":"u6"},
    "65e64e14126a4befbc01461152a18cf9":{
      "scriptId":"u7"},
    "b0105f6518b24afa8c95cc742363d69c":{
      "scriptId":"u8"},
    "5faf9bd30b814fda9622ae3fb2a3579f":{
      "scriptId":"u9"},
    "1f75f7a99f864b6a807fbeb792acf415":{
      "scriptId":"u10"},
    "ca044510f23f40c69fe39e2b16306419":{
      "scriptId":"u11"},
    "836c0904cfde431f9ff9203e8900c013":{
      "scriptId":"u12"},
    "f76170a8ab634900a6a8636a5419599c":{
      "scriptId":"u13"},
    "d3fc43e6ac734237918067c718b7223d":{
      "scriptId":"u14"},
    "3b823403603c4542a266be5396dd301d":{
      "scriptId":"u15"},
    "913d4553064440e6b84b75c225640320":{
      "scriptId":"u16"},
    "53364cef302a4da98feb6e4b0cdb3847":{
      "scriptId":"u17"},
    "cc485a3404b34726bd5d4136faf0592b":{
      "scriptId":"u18"},
    "996f337dd880472ab4c17d3e0f42d401":{
      "scriptId":"u19"},
    "6fbb52fded18488fa382174418498264":{
      "scriptId":"u20"},
    "fece8bc181ea4f2ea006012153ab5a35":{
      "scriptId":"u21"},
    "3105f072c6a2427896face92cc3bdbe7":{
      "scriptId":"u22"},
    "26162b90a13f4036a17bb60329466a2d":{
      "scriptId":"u23"},
    "d1b680c5ce1c4234ac0263fe9733cac3":{
      "scriptId":"u24"},
    "e565720ed8a14c41816a92a289e7ea33":{
      "scriptId":"u25"},
    "a721a35526ae4b368f286567426f8292":{
      "scriptId":"u26"},
    "f28c5a3f44824a14af9230b28b32e053":{
      "scriptId":"u27"},
    "9794f57eb21c48e1a8da91c23597165f":{
      "scriptId":"u28"},
    "dfe1b8f6919e41599143424ee4dd9803":{
      "scriptId":"u29"},
    "30a9cb2e3a2248bca80199831e4f8ebd":{
      "scriptId":"u30"},
    "c94214a4f6cb406d978af3d85cd833fd":{
      "scriptId":"u31"},
    "dae63080cabc418e97061ad15a042345":{
      "scriptId":"u32"},
    "3798da33fc864b7899342b587b63c22c":{
      "scriptId":"u33"},
    "e0cd6859e1ed4330a23c0578f79b399d":{
      "scriptId":"u34"},
    "b2a871e6f9e8443da6cb024dcee7cd8c":{
      "scriptId":"u35"},
    "cd789d0eb01a48b8a54708081cd53089":{
      "scriptId":"u36"},
    "81072a6ab6d2429da9868c9317390937":{
      "scriptId":"u37"},
    "34c3a97b659a466db9f365d5815698f4":{
      "scriptId":"u38"},
    "abbbfe80ac304ba382b22c54cdc3b62c":{
      "scriptId":"u39"},
    "64e6b5e199b64cfb979fe573b1d47eaa":{
      "scriptId":"u40"},
    "3b1e83746b3a4d82983b4e548e214dd7":{
      "scriptId":"u41"},
    "3ef62ceead7f4ceb887a1e9998bb7841":{
      "scriptId":"u42"},
    "6634852d46084fc7aa34116765b934ea":{
      "scriptId":"u43"},
    "5389947bd11d4011b6c23ee1580e14cc":{
      "scriptId":"u44"},
    "4fb5eae5a69a41cab5c40d1ddcff0eac":{
      "scriptId":"u45"},
    "dd372ef053304ee485878ee8cc2ff242":{
      "scriptId":"u46"},
    "94bae4f136ec4471947f1c7bfbb9711a":{
      "scriptId":"u47"},
    "5f6b9bddd3594f0eb3d4c2c88973d3b0":{
      "scriptId":"u48"},
    "bc364315d3d9417e9d3c2f586dc3eea8":{
      "scriptId":"u49"},
    "3140bdf82f264df296ab342cefa878d2":{
      "scriptId":"u50"},
    "042a7b8a4fef4f17b317dd049b03c6e1":{
      "scriptId":"u51"},
    "f67449f746904b77b38df2ce855e083d":{
      "scriptId":"u52"},
    "78c5baca75c14c1babe5f8e69ae40f3a":{
      "scriptId":"u53"},
    "da50c94e6c2b46d89263b3e06ef88549":{
      "scriptId":"u54"},
    "6187e02c4d294239ad1976ca0fbf6dcf":{
      "scriptId":"u55"}}});