$axure.loadCurrentPage({
  "url":"消息.html",
  "generationDate":new Date(1431411283411.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"781af5ceba9b47f290b518a386f15af9",
    "type":"Axure:Page",
    "name":"消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1022f207811f48ddac51b55300c3c971",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71a6bd625d3a4c47bf177af3fe46fbeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u0.png"}},
{
          "id":"f97795de8ff3484299ecd3e65f325456",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06197772bd7647c9b601c01ba028927f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"b73d84d8e4124c3991327e2d84866fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1068},
            "size":{
              "width":640,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17c385db9fc34daca40c6cc5b3fbc536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1068},
                "size":{
                  "width":640,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u4.png"}},
{
          "id":"174444c9bba1468783e36b8d90e40f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":49,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9525c0ae22e14276ae7cdf734ba3467f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"019adced7c754bc3a1920c99acf84805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":510,
              "y":1098},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4fc9cfc0824a16b7f23491dc9bc50a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":510,
                  "y":1098},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"522b448825934095b943222bc6b7391d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2c7113cd986405c9dbb209c7dd6a09f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"34f9c0e51e3c4fa88fdf419101e387c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":297,
              "y":80},
            "size":{
              "width":86,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b0748c64bd34a6984a27bd299174610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":297,
                  "y":80},
                "size":{
                  "width":86,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfad2686f6e0451abd283115da0d26ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"941ebd53a7584fdc9e4f29e7e0f71d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u14.png"}},
{
          "id":"777c3c4954a646d6a21ede09e9bd5f82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":228},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ef8762a4464fa7b81c5b817821bc36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":228},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"179285c0f6414634a22c05375763977c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":169},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253862539e1047a0ab36721cf701ec47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":169},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u18.png"}},
{
          "id":"36c35869351d49b8ad304aae44058f79",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":86,
              "y":173},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2abf62758b94983ab0a7ea4cc4c30d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":86,
                  "y":173},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0303296ea51436093d7e5004fb5da00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":244},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f935cb18c1984ebe98f39e1e275d1857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":244},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"e0b56feaca864175ba99f5aee3bf6a7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":244},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109061d1cda8449aab1be4ae8fea7a20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":244},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4dacb2640ab4a7e8f881dacc6057343",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":290},
            "size":{
              "width":243,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd9adc53d83647bbad00ee1d2c3f1d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":290},
                "size":{
                  "width":243,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e67072f4318542d2a116ec9b82acd5e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":235,
              "y":238},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40a61fcb46f5491db43ec24f626f1bd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":235,
                  "y":238},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u28.png"}},
{
          "id":"b44f6ccd171a493db38b82a0099361a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":285,
              "y":246},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e42cdf5f21c492db91c676d1120bbbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":285,
                  "y":246},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab33865d30de4143b2efd1b3ec859a81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":550,
              "y":256},
            "size":{
              "width":92,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e85ecd6c1c04402eac716000b5a3e68d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":550,
                  "y":256},
                "size":{
                  "width":92,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3c618b4e33f49a0999c0d83b7e4ab6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":347},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b6bd09403f74e06a853dab0caf94dc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":347},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u16.png"}},
{
          "id":"eb134c499c69457db01ce323d41a734c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":363},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53c3253545c647ce8895a92cf7957e4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":363},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"e4e164cb8714484fa7df0782acbbb82a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":363},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee195dc1bdec4a18ac52701b5eb4f6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":363},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4acf53a6622446b69ff8457c25d7abe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":140,
              "y":409},
            "size":{
              "width":243,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a63d1121ccaa4a14842fb6121f9956ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":140,
                  "y":409},
                "size":{
                  "width":243,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b9a6423a7db4d8981088e94637944eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":207,
              "y":357},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0490017bcd1c42219f932987c21a5ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":207,
                  "y":357},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u28.png"}},
{
          "id":"9f861d88fe0e4fcb9c78037d10efb254",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":257,
              "y":365},
            "size":{
              "width":65,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd5316022ce84fa89b56c1e8949f9e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":257,
                  "y":365},
                "size":{
                  "width":65,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6af795ce785411aa513a750094c4da4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":457,
              "y":375},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5382574c29fd4f70babb315671b7e178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":457,
                  "y":375},
                "size":{
                  "width":180,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fde6f92c339a4d87b277140b55a71f9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":601,
              "y":408},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51f5fa0cedd74215a721032f357915fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":601,
                  "y":408},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u48.png"}},
{
          "id":"e5ff4d28570e466d8cacb7d05b29b3fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":264,
              "y":1098},
            "size":{
              "width":91,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe46acff9edc46f79519c82cf505e534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":1098},
                "size":{
                  "width":91,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c63cd20b91ca42ec8bc4ddab55b69d81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":557,
              "y":80},
            "size":{
              "width":80,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d23e1f108e6c4cd4b2b0815e5f0ab13c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":557,
                  "y":80},
                "size":{
                  "width":80,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc3f62f228434092a52879bfd73ba995",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":360,
              "y":251},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76423b9dc21b4f62b71500101833c8b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":360,
                  "y":251},
                "size":{
                  "width":80,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1022f207811f48ddac51b55300c3c971":{
      "scriptId":"u0"},
    "71a6bd625d3a4c47bf177af3fe46fbeb":{
      "scriptId":"u1"},
    "f97795de8ff3484299ecd3e65f325456":{
      "scriptId":"u2"},
    "06197772bd7647c9b601c01ba028927f":{
      "scriptId":"u3"},
    "b73d84d8e4124c3991327e2d84866fd4":{
      "scriptId":"u4"},
    "17c385db9fc34daca40c6cc5b3fbc536":{
      "scriptId":"u5"},
    "174444c9bba1468783e36b8d90e40f49":{
      "scriptId":"u6"},
    "9525c0ae22e14276ae7cdf734ba3467f":{
      "scriptId":"u7"},
    "019adced7c754bc3a1920c99acf84805":{
      "scriptId":"u8"},
    "4e4fc9cfc0824a16b7f23491dc9bc50a":{
      "scriptId":"u9"},
    "522b448825934095b943222bc6b7391d":{
      "scriptId":"u10"},
    "e2c7113cd986405c9dbb209c7dd6a09f":{
      "scriptId":"u11"},
    "34f9c0e51e3c4fa88fdf419101e387c0":{
      "scriptId":"u12"},
    "3b0748c64bd34a6984a27bd299174610":{
      "scriptId":"u13"},
    "bfad2686f6e0451abd283115da0d26ee":{
      "scriptId":"u14"},
    "941ebd53a7584fdc9e4f29e7e0f71d8c":{
      "scriptId":"u15"},
    "777c3c4954a646d6a21ede09e9bd5f82":{
      "scriptId":"u16"},
    "d8ef8762a4464fa7b81c5b817821bc36":{
      "scriptId":"u17"},
    "179285c0f6414634a22c05375763977c":{
      "scriptId":"u18"},
    "253862539e1047a0ab36721cf701ec47":{
      "scriptId":"u19"},
    "36c35869351d49b8ad304aae44058f79":{
      "scriptId":"u20"},
    "a2abf62758b94983ab0a7ea4cc4c30d8":{
      "scriptId":"u21"},
    "b0303296ea51436093d7e5004fb5da00":{
      "scriptId":"u22"},
    "f935cb18c1984ebe98f39e1e275d1857":{
      "scriptId":"u23"},
    "e0b56feaca864175ba99f5aee3bf6a7e":{
      "scriptId":"u24"},
    "109061d1cda8449aab1be4ae8fea7a20":{
      "scriptId":"u25"},
    "f4dacb2640ab4a7e8f881dacc6057343":{
      "scriptId":"u26"},
    "cd9adc53d83647bbad00ee1d2c3f1d75":{
      "scriptId":"u27"},
    "e67072f4318542d2a116ec9b82acd5e1":{
      "scriptId":"u28"},
    "40a61fcb46f5491db43ec24f626f1bd3":{
      "scriptId":"u29"},
    "b44f6ccd171a493db38b82a0099361a9":{
      "scriptId":"u30"},
    "5e42cdf5f21c492db91c676d1120bbbc":{
      "scriptId":"u31"},
    "ab33865d30de4143b2efd1b3ec859a81":{
      "scriptId":"u32"},
    "e85ecd6c1c04402eac716000b5a3e68d":{
      "scriptId":"u33"},
    "b3c618b4e33f49a0999c0d83b7e4ab6b":{
      "scriptId":"u34"},
    "6b6bd09403f74e06a853dab0caf94dc5":{
      "scriptId":"u35"},
    "eb134c499c69457db01ce323d41a734c":{
      "scriptId":"u36"},
    "53c3253545c647ce8895a92cf7957e4b":{
      "scriptId":"u37"},
    "e4e164cb8714484fa7df0782acbbb82a":{
      "scriptId":"u38"},
    "ee195dc1bdec4a18ac52701b5eb4f6a5":{
      "scriptId":"u39"},
    "4acf53a6622446b69ff8457c25d7abe7":{
      "scriptId":"u40"},
    "a63d1121ccaa4a14842fb6121f9956ca":{
      "scriptId":"u41"},
    "3b9a6423a7db4d8981088e94637944eb":{
      "scriptId":"u42"},
    "0490017bcd1c42219f932987c21a5ef6":{
      "scriptId":"u43"},
    "9f861d88fe0e4fcb9c78037d10efb254":{
      "scriptId":"u44"},
    "bd5316022ce84fa89b56c1e8949f9e11":{
      "scriptId":"u45"},
    "b6af795ce785411aa513a750094c4da4":{
      "scriptId":"u46"},
    "5382574c29fd4f70babb315671b7e178":{
      "scriptId":"u47"},
    "fde6f92c339a4d87b277140b55a71f9e":{
      "scriptId":"u48"},
    "51f5fa0cedd74215a721032f357915fe":{
      "scriptId":"u49"},
    "e5ff4d28570e466d8cacb7d05b29b3fe":{
      "scriptId":"u50"},
    "fe46acff9edc46f79519c82cf505e534":{
      "scriptId":"u51"},
    "c63cd20b91ca42ec8bc4ddab55b69d81":{
      "scriptId":"u52"},
    "d23e1f108e6c4cd4b2b0815e5f0ab13c":{
      "scriptId":"u53"},
    "fc3f62f228434092a52879bfd73ba995":{
      "scriptId":"u54"},
    "76423b9dc21b4f62b71500101833c8b1":{
      "scriptId":"u55"}}});