$axure.loadCurrentPage({
  "url":"银行卡.html",
  "generationDate":new Date(1429163223578.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b819bcd4974144ebafda96d6476a4f89",
    "type":"Axure:Page",
    "name":"银行卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55e4e374c88f4f1d8a07f97c4e8aa1ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54fcb7278ed040ff973fefb4b399d412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"ecfad733aff94a6e81b553607c4df8f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31dc395956ff4214ab01c75c051446a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"4708d28bdbdb475c8e2dc6fb2a89782c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e3fa79e0174dd4b8efdf6d5dcb657b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"39da78f84b394e8dab309ef7f87a65f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":300,
              "y":80},
            "size":{
              "width":79,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e51b7e44ccfb4e1ba45ffb952094ce3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":300,
                  "y":80},
                "size":{
                  "width":79,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"424a90ea4b5a497285c10638d439a783",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":64,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"786bf8d453cd4cf395f49c1fc9231a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8850ae8055b543318aad17b36aadc98d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":171},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab87838c3414681919a0900f940f1be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":171},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"3f163b191d44417485e837ef0c3c97d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":473,
              "y":212},
            "size":{
              "width":147,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e1a5c384cc24cb08b85106955e4194e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":473,
                  "y":212},
                "size":{
                  "width":147,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1714a05c0cfa48d99b468faeb0af3bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":191},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"683e297d3d49488fa6d742a32d928ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":191},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "55e4e374c88f4f1d8a07f97c4e8aa1ca":{
      "scriptId":"u0"},
    "54fcb7278ed040ff973fefb4b399d412":{
      "scriptId":"u1"},
    "ecfad733aff94a6e81b553607c4df8f1":{
      "scriptId":"u2"},
    "31dc395956ff4214ab01c75c051446a5":{
      "scriptId":"u3"},
    "4708d28bdbdb475c8e2dc6fb2a89782c":{
      "scriptId":"u4"},
    "e6e3fa79e0174dd4b8efdf6d5dcb657b":{
      "scriptId":"u5"},
    "39da78f84b394e8dab309ef7f87a65f8":{
      "scriptId":"u6"},
    "e51b7e44ccfb4e1ba45ffb952094ce3b":{
      "scriptId":"u7"},
    "424a90ea4b5a497285c10638d439a783":{
      "scriptId":"u8"},
    "786bf8d453cd4cf395f49c1fc9231a9f":{
      "scriptId":"u9"},
    "8850ae8055b543318aad17b36aadc98d":{
      "scriptId":"u10"},
    "8ab87838c3414681919a0900f940f1be":{
      "scriptId":"u11"},
    "3f163b191d44417485e837ef0c3c97d9":{
      "scriptId":"u12"},
    "9e1a5c384cc24cb08b85106955e4194e":{
      "scriptId":"u13"},
    "1714a05c0cfa48d99b468faeb0af3bf1":{
      "scriptId":"u14"},
    "683e297d3d49488fa6d742a32d928ce8":{
      "scriptId":"u15"}}});