$axure.loadCurrentPage({
  "url":"通知.html",
  "generationDate":new Date(1430278057007.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"28ad8f2489e5496196c68235a07c7c65",
    "type":"Axure:Page",
    "name":"通知",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"08424584ebf34b8cb9068f303d295ae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7080259c0d9241f8b88e320f8774e74d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u178.png"}},
{
          "id":"fa5d94befb334baebcae72d6246f2e4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e238999e4245e3aef05674ba4ff5b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"00281b880205409aa0e1475793eac09b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":590,
              "y":65},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87fe8738705548289b0ea34fd3aa6c48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":590,
                  "y":65},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a78bba9a514b4c52911f67445ae92328",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"986116b5b45144419e2f420c5ac4a460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"d7eddbb3b7084f09baea41a18999dac4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":324,
              "y":65},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7a9678b4d714faa8fefcfd2f4b1eb96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":65},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1752369ac4704f9094420949ce081d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":129},
            "size":{
              "width":640,
              "height":391}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93d0f304f0e140d69d5c0493a2b8d0f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":129},
                "size":{
                  "width":640,
                  "height":391}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u10.png"}},
{
          "id":"ee2adec462a94c8494f6c7adcc25cd6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":414,
              "y":140},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f31a0e256364c79b436bbdc397a2946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":414,
                  "y":140},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed2bbbeb3902417a905c26f1ca5e4fbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":92,
              "y":515},
            "size":{
              "width":73,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"819f5874c273409e9887155e2eaf3bbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":92,
                  "y":515},
                "size":{
                  "width":73,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4bc7fe10fdc46eb9b9d9cde05daf116",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":82,
              "y":494},
            "size":{
              "width":83,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9e9996c69c4d17b0d96bbc378bf571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":82,
                  "y":494},
                "size":{
                  "width":83,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"978914c56de84748b26848bf4f757f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":324,
              "y":140},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a932e0096f94f43a417217afba0d730",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":324,
                  "y":140},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息1/u26.png"}},
{
          "id":"181770c7603c4caeb2e01b072b6a6654",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":840,
              "y":150},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58faf24e857f4dd2885ee97c9db0e65a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":840,
                  "y":150},
                "size":{
                  "width":90,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u20.png"}},
{
          "id":"6f6d6aaeade144a585c75d9e770282cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":414,
              "y":182},
            "size":{
              "width":116,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac574f3d44aa45e58328ae29be8c6e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":182},
                "size":{
                  "width":116,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac91f8b0c09546a58b53bf140a803590",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":332,
              "y":240},
            "size":{
              "width":609,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c7367cd7aa04021bef09a230241f118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":332,
                  "y":240},
                "size":{
                  "width":609,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd14c4d755834e8fb33a357bfc21e644",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":324,
              "y":295},
            "size":{
              "width":606,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565c8ebf9e264a0799ad91973580eb70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":324,
                  "y":295},
                "size":{
                  "width":606,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u26.png"}},
{
          "id":"adb2dbc1357a4f0f8a8d5ab473a6f67f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":332,
              "y":308},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc5fbc255a4414cbf5f4e54195b5a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":332,
                  "y":308},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息1/u26.png"}},
{
          "id":"139ac1a9ba044a2eb04580f3e883617b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":444.5,
              "y":315},
            "size":{
              "width":466,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531e12db6434410587b368ee135ce872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":444.5,
                  "y":315},
                "size":{
                  "width":466,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8ee22eef7f047aca742db1c7d89bda4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":530},
            "size":{
              "width":640,
              "height":391}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fefb944b6087476c8cfa549c834f1490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":530},
                "size":{
                  "width":640,
                  "height":391}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u10.png"}},
{
          "id":"6ad95d0c5dbd4b1ba15c6a9ff3fa7f91",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":414,
              "y":541},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0265d73faca40598cfd9cc62a7b55dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":414,
                  "y":541},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ac6fd79d35547618065a168afb8d0f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":324,
              "y":541},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4945165374434677a1c651dacbf770d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":324,
                  "y":541},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息1/u26.png"}},
{
          "id":"38a02300a78b4258b35f57059b0501df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":840,
              "y":551},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f4e69ceca424a8389b621ac5d2b5dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":840,
                  "y":551},
                "size":{
                  "width":90,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u20.png"}},
{
          "id":"c6dfc9f5ffa742018f96b3101550fb71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":414,
              "y":583},
            "size":{
              "width":116,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd21336b878142b19097e968394d86be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":583},
                "size":{
                  "width":116,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9746b27f948f40f1aad5027f663407db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":332,
              "y":641},
            "size":{
              "width":609,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94cf6f71988240e38105061de47cf1af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":332,
                  "y":641},
                "size":{
                  "width":609,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6b2735d119424c9d027241a8b5f9d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":324,
              "y":696},
            "size":{
              "width":606,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ffb8ead2b6d468db84b747f33ae4f9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":324,
                  "y":696},
                "size":{
                  "width":606,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u26.png"}},
{
          "id":"93febe44f99c4d428577be17ed628921",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":332,
              "y":709},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c6bd9148b1e4d95ad86494ea7b439df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":332,
                  "y":709},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息1/u26.png"}},
{
          "id":"39a384dab9b34631aab9ac1c0df2ceb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":444,
              "y":716},
            "size":{
              "width":466,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7c17c18ce7e4fddbcfa5e3c6c1c51db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":444,
                  "y":716},
                "size":{
                  "width":466,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"180dec6ed2f44b43a9da1f5d2dba2965",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":1017,
              "y":492},
            "size":{
              "width":73,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfeaf644e056474d83684eb49d952af5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":1017,
                  "y":492},
                "size":{
                  "width":73,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c02e70db433c470fb009b5d9daf59b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":1007,
              "y":471},
            "size":{
              "width":83,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce98c603f6c4d99a5ae1640a3b76742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":1007,
                  "y":471},
                "size":{
                  "width":83,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"130df91b4caf4e75a53a60cd192b8aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":1017,
              "y":482},
            "size":{
              "width":83,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab5341ab816b42eeb2ff04db3e476263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":1017,
                  "y":482},
                "size":{
                  "width":83,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46aa097414d24a8aa03a8cd42c2bd7b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1160,
              "y":0},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5eebd0e559c45728ce722728853155f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1160,
                  "y":0},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u178.png"}},
{
          "id":"66f5e2e92aec4bdf85adc02fc2079e46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":0},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf580294f214b549b0f6724d40199d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":0},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"5d56a7bde34a4f4bba05a48e2d151c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":1405,
              "y":65},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"791f249e5b964e508683ccc0b99aa62b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":1405,
                  "y":65},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9466999ac92348a0b1076d8322fa9337",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":0},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d77cd5f96e74fe3bb9152d8c746f094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":0},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"9d53e2eef1bb4ff6a38398c5984c61cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1174,
              "y":65},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31fdfaf9b45a42debf5c23b840a6d6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1174,
                  "y":65},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07bb0cbf442b4d049526d2cdbf0c1083",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":1690,
              "y":50},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1fbe48f46448b1b49cbb54c4e7a8fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":1690,
                  "y":50},
                "size":{
                  "width":90,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知/u20.png"}},
{
          "id":"910233039a174e63a4241e897d7c3cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":129},
            "size":{
              "width":640,
              "height":451}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50afcacf433a4662aea060dc09dbcf86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":129},
                "size":{
                  "width":640,
                  "height":451}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/论坛/u177.png"}},
{
          "id":"ecdb23d99f3a4f1589bb98021bda1468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":1177,
              "y":154},
            "size":{
              "width":606,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e58cbc8b31f64c27b157569927c6bc6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":1177,
                  "y":154},
                "size":{
                  "width":606,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c9f81a01c954b039666e7daf895d783",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":1737,
              "y":541},
            "size":{
              "width":48,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c317c3afd334ccab0264b1c2a2fa87a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":1737,
                  "y":541},
                "size":{
                  "width":48,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6417f1eee9a1476c9b26c86adb9472c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":616},
            "size":{
              "width":640,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7348e23a1f254fb9b0265975199857ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":616},
                "size":{
                  "width":640,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u206.png"}},
{
          "id":"4ebf0831e2c44ec78997c298adce42e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":1448,
              "y":830},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b64d1cf76c034648af97e0e5e66987d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":1448,
                  "y":830},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "08424584ebf34b8cb9068f303d295ae7":{
      "scriptId":"u0"},
    "7080259c0d9241f8b88e320f8774e74d":{
      "scriptId":"u1"},
    "fa5d94befb334baebcae72d6246f2e4d":{
      "scriptId":"u2"},
    "e5e238999e4245e3aef05674ba4ff5b0":{
      "scriptId":"u3"},
    "00281b880205409aa0e1475793eac09b":{
      "scriptId":"u4"},
    "87fe8738705548289b0ea34fd3aa6c48":{
      "scriptId":"u5"},
    "a78bba9a514b4c52911f67445ae92328":{
      "scriptId":"u6"},
    "986116b5b45144419e2f420c5ac4a460":{
      "scriptId":"u7"},
    "d7eddbb3b7084f09baea41a18999dac4":{
      "scriptId":"u8"},
    "f7a9678b4d714faa8fefcfd2f4b1eb96":{
      "scriptId":"u9"},
    "1752369ac4704f9094420949ce081d05":{
      "scriptId":"u10"},
    "93d0f304f0e140d69d5c0493a2b8d0f2":{
      "scriptId":"u11"},
    "ee2adec462a94c8494f6c7adcc25cd6b":{
      "scriptId":"u12"},
    "6f31a0e256364c79b436bbdc397a2946":{
      "scriptId":"u13"},
    "ed2bbbeb3902417a905c26f1ca5e4fbf":{
      "scriptId":"u14"},
    "819f5874c273409e9887155e2eaf3bbb":{
      "scriptId":"u15"},
    "a4bc7fe10fdc46eb9b9d9cde05daf116":{
      "scriptId":"u16"},
    "be9e9996c69c4d17b0d96bbc378bf571":{
      "scriptId":"u17"},
    "978914c56de84748b26848bf4f757f4f":{
      "scriptId":"u18"},
    "3a932e0096f94f43a417217afba0d730":{
      "scriptId":"u19"},
    "181770c7603c4caeb2e01b072b6a6654":{
      "scriptId":"u20"},
    "58faf24e857f4dd2885ee97c9db0e65a":{
      "scriptId":"u21"},
    "6f6d6aaeade144a585c75d9e770282cb":{
      "scriptId":"u22"},
    "ac574f3d44aa45e58328ae29be8c6e22":{
      "scriptId":"u23"},
    "ac91f8b0c09546a58b53bf140a803590":{
      "scriptId":"u24"},
    "2c7367cd7aa04021bef09a230241f118":{
      "scriptId":"u25"},
    "bd14c4d755834e8fb33a357bfc21e644":{
      "scriptId":"u26"},
    "565c8ebf9e264a0799ad91973580eb70":{
      "scriptId":"u27"},
    "adb2dbc1357a4f0f8a8d5ab473a6f67f":{
      "scriptId":"u28"},
    "1fc5fbc255a4414cbf5f4e54195b5a45":{
      "scriptId":"u29"},
    "139ac1a9ba044a2eb04580f3e883617b":{
      "scriptId":"u30"},
    "531e12db6434410587b368ee135ce872":{
      "scriptId":"u31"},
    "e8ee22eef7f047aca742db1c7d89bda4":{
      "scriptId":"u32"},
    "fefb944b6087476c8cfa549c834f1490":{
      "scriptId":"u33"},
    "6ad95d0c5dbd4b1ba15c6a9ff3fa7f91":{
      "scriptId":"u34"},
    "b0265d73faca40598cfd9cc62a7b55dd":{
      "scriptId":"u35"},
    "6ac6fd79d35547618065a168afb8d0f2":{
      "scriptId":"u36"},
    "4945165374434677a1c651dacbf770d5":{
      "scriptId":"u37"},
    "38a02300a78b4258b35f57059b0501df":{
      "scriptId":"u38"},
    "2f4e69ceca424a8389b621ac5d2b5dc9":{
      "scriptId":"u39"},
    "c6dfc9f5ffa742018f96b3101550fb71":{
      "scriptId":"u40"},
    "bd21336b878142b19097e968394d86be":{
      "scriptId":"u41"},
    "9746b27f948f40f1aad5027f663407db":{
      "scriptId":"u42"},
    "94cf6f71988240e38105061de47cf1af":{
      "scriptId":"u43"},
    "0b6b2735d119424c9d027241a8b5f9d6":{
      "scriptId":"u44"},
    "7ffb8ead2b6d468db84b747f33ae4f9f":{
      "scriptId":"u45"},
    "93febe44f99c4d428577be17ed628921":{
      "scriptId":"u46"},
    "3c6bd9148b1e4d95ad86494ea7b439df":{
      "scriptId":"u47"},
    "39a384dab9b34631aab9ac1c0df2ceb7":{
      "scriptId":"u48"},
    "c7c17c18ce7e4fddbcfa5e3c6c1c51db":{
      "scriptId":"u49"},
    "180dec6ed2f44b43a9da1f5d2dba2965":{
      "scriptId":"u50"},
    "dfeaf644e056474d83684eb49d952af5":{
      "scriptId":"u51"},
    "c02e70db433c470fb009b5d9daf59b6c":{
      "scriptId":"u52"},
    "6ce98c603f6c4d99a5ae1640a3b76742":{
      "scriptId":"u53"},
    "130df91b4caf4e75a53a60cd192b8aee":{
      "scriptId":"u54"},
    "ab5341ab816b42eeb2ff04db3e476263":{
      "scriptId":"u55"},
    "46aa097414d24a8aa03a8cd42c2bd7b7":{
      "scriptId":"u56"},
    "f5eebd0e559c45728ce722728853155f":{
      "scriptId":"u57"},
    "66f5e2e92aec4bdf85adc02fc2079e46":{
      "scriptId":"u58"},
    "adf580294f214b549b0f6724d40199d5":{
      "scriptId":"u59"},
    "5d56a7bde34a4f4bba05a48e2d151c4b":{
      "scriptId":"u60"},
    "791f249e5b964e508683ccc0b99aa62b":{
      "scriptId":"u61"},
    "9466999ac92348a0b1076d8322fa9337":{
      "scriptId":"u62"},
    "2d77cd5f96e74fe3bb9152d8c746f094":{
      "scriptId":"u63"},
    "9d53e2eef1bb4ff6a38398c5984c61cc":{
      "scriptId":"u64"},
    "31fdfaf9b45a42debf5c23b840a6d6ae":{
      "scriptId":"u65"},
    "07bb0cbf442b4d049526d2cdbf0c1083":{
      "scriptId":"u66"},
    "2c1fbe48f46448b1b49cbb54c4e7a8fc":{
      "scriptId":"u67"},
    "910233039a174e63a4241e897d7c3cae":{
      "scriptId":"u68"},
    "50afcacf433a4662aea060dc09dbcf86":{
      "scriptId":"u69"},
    "ecdb23d99f3a4f1589bb98021bda1468":{
      "scriptId":"u70"},
    "e58cbc8b31f64c27b157569927c6bc6e":{
      "scriptId":"u71"},
    "3c9f81a01c954b039666e7daf895d783":{
      "scriptId":"u72"},
    "3c317c3afd334ccab0264b1c2a2fa87a":{
      "scriptId":"u73"},
    "6417f1eee9a1476c9b26c86adb9472c5":{
      "scriptId":"u74"},
    "7348e23a1f254fb9b0265975199857ff":{
      "scriptId":"u75"},
    "4ebf0831e2c44ec78997c298adce42e1":{
      "scriptId":"u76"},
    "b64d1cf76c034648af97e0e5e66987d2":{
      "scriptId":"u77"}}});