$axure.loadCurrentPage({
  "url":"个人信息_1.html",
  "generationDate":new Date(1429527577306.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"12cc9ada47344c3ab286b021e1462767",
    "type":"Axure:Page",
    "name":"个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73808a36a3394a43952655ca62017de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8975df15ea94437baa6eed289a463754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"c32170b2c2114c7cb341384ae1eec7f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14d9c01cd4c4886bf06691c83990d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"fdb9d9f99c834197a7e29f57b6d53877",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5230c86a2be7499985b41527bc44ecca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c22df7cb3bd2448484489956963020d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f033938958ce48908aec8858437ed18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb123dc44c6946dda1f1c55d771ed02c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63b5a72597b04c5b86add8887affa597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"2537f955fa3c4d4e9f1a9c1ad48a76b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae57910328e4496adc5c20ad4036693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"f7836250482e47c38c6bc5703e8f4587",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":434,
              "y":182},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914dd35e658c4b999a24a565e926eb4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":182},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b631531c952442a68fe99a55a5f69340",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":114,
              "y":182},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e300efcc355f4bd0a8f52938541e9957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":182},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a49dfab1a659465f8dc7fd75b27b3fe1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":166},
            "size":{
              "width":10,
              "height":70}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/血糖记录/u16_line.png"}},
{
          "id":"684e51c1782840cf921cf990cd2074fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":259},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d7b956e5ad417daa9855657ae92d16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":259},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1370003ff0f4d05910bc9c39bd79328",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":298},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f24471c60141d1ae6d7e4df09abfcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":298},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"5badae24b25846b2b0fc6d6e58075aba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":323},
            "size":{
              "width":61,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"417c672f7ded44829f400e83a9304fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":323},
                "size":{
                  "width":61,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0b17fbff43342759b421a8cfb1cd1ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":403},
            "size":{
              "width":141,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53eac2b91e74d37b626ef412a9fb419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":403},
                "size":{
                  "width":141,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a63a87bedfaf4555b14caea288bd9dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":443},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da1c99ab817145e59d31067d89ae59f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":443},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"5afea3456fcd4d598ea906b6a03a4ae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":467},
            "size":{
              "width":207,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b5cf118b8a42b2983aa25fd0c3bb7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":467},
                "size":{
                  "width":207,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb47dc43e5a04dcfbbf37b5c3adcde90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":546},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1a6f0a185c742a0962129a2cf3cad18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":546},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71661eea0df843d687d857cfac2399b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":586},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fd4f1b2d59b472dab47fae1304b135f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":586},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"b631e1a70f0a451d80524d6cb2466b5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":610},
            "size":{
              "width":31,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b08341f32d4c8eae640a40ffe7dca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":610},
                "size":{
                  "width":31,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aa1751ff75341a298674e94a4eca6a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":611},
            "size":{
              "width":20,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9ffa59dead84112b42aef83349b850c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":611},
                "size":{
                  "width":20,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5cb52f530f4d52af64d8dd32c30798",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":688},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ae21ec329c44738ae03d8dacf8ec2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":688},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"713ddc0ea6c64f93a3609b667dd0fd8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":728},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb119d82f22b449f8fda82f850772500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":728},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"8a6f626d92524760afccc1aaaa3b7d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":752},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7824e859c6384082acedf1ed27e8c8d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":752},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ae8fccfed8c400db6f863b033574584",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":851},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb15b099c574808b26370622c956ed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":851},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab5abb5bd9494ecaa268d460d01514c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":891},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0053d03b8640cb910cb1fb20e3c4a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":891},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"5ea3308a035f44d7a109c62f5b6cb9b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":915},
            "size":{
              "width":121,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76956ab29993492aa84522b36c0fb257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":915},
                "size":{
                  "width":121,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab201d133c534e9f9b846b5a911de387",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":36,
              "y":1002},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb55aeceba34263b66438798f32b540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":1002},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45177b78fb1d455e91023435475b290d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":1042},
            "size":{
              "width":607,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9befe31e560c4fdabdd885cb20bcb42b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":1042},
                "size":{
                  "width":607,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u19.png"}},
{
          "id":"414aff62130742ae987a0daa0aac9bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":52,
              "y":1066},
            "size":{
              "width":31,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c586089767214df1858124f42fef1431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":52,
                  "y":1066},
                "size":{
                  "width":31,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84664725542c4de18ba3f4f7127c2b9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":568,
              "y":468},
            "size":{
              "width":64,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eafbb771194749768eef3d46a8ecf58b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":568,
                  "y":468},
                "size":{
                  "width":64,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac94513f1bd6455f99c7f4b770c45648",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1076},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caeaa9ae203245f388486f4a14da337f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1076},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u14.png"}},
{
          "id":"199eedc07d1945b7ac9b5ec49bb2aa77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":240,
              "y":1096},
            "size":{
              "width":200,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e3c6c627354c3b957aca586d40c08f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":240,
                  "y":1096},
                "size":{
                  "width":200,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "73808a36a3394a43952655ca62017de7":{
      "scriptId":"u0"},
    "8975df15ea94437baa6eed289a463754":{
      "scriptId":"u1"},
    "c32170b2c2114c7cb341384ae1eec7f3":{
      "scriptId":"u2"},
    "b14d9c01cd4c4886bf06691c83990d50":{
      "scriptId":"u3"},
    "fdb9d9f99c834197a7e29f57b6d53877":{
      "scriptId":"u4"},
    "5230c86a2be7499985b41527bc44ecca":{
      "scriptId":"u5"},
    "c22df7cb3bd2448484489956963020d2":{
      "scriptId":"u6"},
    "f033938958ce48908aec8858437ed18d":{
      "scriptId":"u7"},
    "cb123dc44c6946dda1f1c55d771ed02c":{
      "scriptId":"u8"},
    "63b5a72597b04c5b86add8887affa597":{
      "scriptId":"u9"},
    "2537f955fa3c4d4e9f1a9c1ad48a76b3":{
      "scriptId":"u10"},
    "eae57910328e4496adc5c20ad4036693":{
      "scriptId":"u11"},
    "f7836250482e47c38c6bc5703e8f4587":{
      "scriptId":"u12"},
    "914dd35e658c4b999a24a565e926eb4d":{
      "scriptId":"u13"},
    "b631531c952442a68fe99a55a5f69340":{
      "scriptId":"u14"},
    "e300efcc355f4bd0a8f52938541e9957":{
      "scriptId":"u15"},
    "a49dfab1a659465f8dc7fd75b27b3fe1":{
      "scriptId":"u16"},
    "684e51c1782840cf921cf990cd2074fd":{
      "scriptId":"u17"},
    "72d7b956e5ad417daa9855657ae92d16":{
      "scriptId":"u18"},
    "a1370003ff0f4d05910bc9c39bd79328":{
      "scriptId":"u19"},
    "a3f24471c60141d1ae6d7e4df09abfcf":{
      "scriptId":"u20"},
    "5badae24b25846b2b0fc6d6e58075aba":{
      "scriptId":"u21"},
    "417c672f7ded44829f400e83a9304fce":{
      "scriptId":"u22"},
    "a0b17fbff43342759b421a8cfb1cd1ac":{
      "scriptId":"u23"},
    "a53eac2b91e74d37b626ef412a9fb419":{
      "scriptId":"u24"},
    "a63a87bedfaf4555b14caea288bd9dc0":{
      "scriptId":"u25"},
    "da1c99ab817145e59d31067d89ae59f2":{
      "scriptId":"u26"},
    "5afea3456fcd4d598ea906b6a03a4ae7":{
      "scriptId":"u27"},
    "00b5cf118b8a42b2983aa25fd0c3bb7a":{
      "scriptId":"u28"},
    "bb47dc43e5a04dcfbbf37b5c3adcde90":{
      "scriptId":"u29"},
    "d1a6f0a185c742a0962129a2cf3cad18":{
      "scriptId":"u30"},
    "71661eea0df843d687d857cfac2399b6":{
      "scriptId":"u31"},
    "3fd4f1b2d59b472dab47fae1304b135f":{
      "scriptId":"u32"},
    "b631e1a70f0a451d80524d6cb2466b5b":{
      "scriptId":"u33"},
    "29b08341f32d4c8eae640a40ffe7dca3":{
      "scriptId":"u34"},
    "8aa1751ff75341a298674e94a4eca6a3":{
      "scriptId":"u35"},
    "f9ffa59dead84112b42aef83349b850c":{
      "scriptId":"u36"},
    "0c5cb52f530f4d52af64d8dd32c30798":{
      "scriptId":"u37"},
    "76ae21ec329c44738ae03d8dacf8ec2b":{
      "scriptId":"u38"},
    "713ddc0ea6c64f93a3609b667dd0fd8c":{
      "scriptId":"u39"},
    "cb119d82f22b449f8fda82f850772500":{
      "scriptId":"u40"},
    "8a6f626d92524760afccc1aaaa3b7d9c":{
      "scriptId":"u41"},
    "7824e859c6384082acedf1ed27e8c8d9":{
      "scriptId":"u42"},
    "3ae8fccfed8c400db6f863b033574584":{
      "scriptId":"u43"},
    "9eb15b099c574808b26370622c956ed7":{
      "scriptId":"u44"},
    "ab5abb5bd9494ecaa268d460d01514c6":{
      "scriptId":"u45"},
    "bf0053d03b8640cb910cb1fb20e3c4a0":{
      "scriptId":"u46"},
    "5ea3308a035f44d7a109c62f5b6cb9b0":{
      "scriptId":"u47"},
    "76956ab29993492aa84522b36c0fb257":{
      "scriptId":"u48"},
    "ab201d133c534e9f9b846b5a911de387":{
      "scriptId":"u49"},
    "aeb55aeceba34263b66438798f32b540":{
      "scriptId":"u50"},
    "45177b78fb1d455e91023435475b290d":{
      "scriptId":"u51"},
    "9befe31e560c4fdabdd885cb20bcb42b":{
      "scriptId":"u52"},
    "414aff62130742ae987a0daa0aac9bec":{
      "scriptId":"u53"},
    "c586089767214df1858124f42fef1431":{
      "scriptId":"u54"},
    "84664725542c4de18ba3f4f7127c2b9a":{
      "scriptId":"u55"},
    "eafbb771194749768eef3d46a8ecf58b":{
      "scriptId":"u56"},
    "ac94513f1bd6455f99c7f4b770c45648":{
      "scriptId":"u57"},
    "caeaa9ae203245f388486f4a14da337f":{
      "scriptId":"u58"},
    "199eedc07d1945b7ac9b5ec49bb2aa77":{
      "scriptId":"u59"},
    "a8e3c6c627354c3b957aca586d40c08f":{
      "scriptId":"u60"}}});