$axure.loadCurrentPage({
  "url":"聊天.html",
  "generationDate":new Date(1431411283588.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"44cee00b7bac485f9336a3778b6501da",
    "type":"Axure:Page",
    "name":"聊天",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0d47056e911341f598a3a2a5e453f2c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":-341.5},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d3f3a1f00ad4ca0a7364f726aa59646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":-341.5},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"a415c9e3b8c54b71be4e573a692079d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":-341.5},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf18c1d2db0f4a16a800507f14ef0155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":-341.5},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"24758bf874124b849e3167b9f2453ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":308,
              "y":-282},
            "size":{
              "width":153,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d2a8bae51e4a4399faef4265598ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":-282},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"503c59d5cbec4ee797a034dae5e93fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":73,
              "y":-282},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de07146da2a3450aa005ee013b608068",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":-282},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0af074dcbe6d4f56ae015f567d637767",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":581,
              "y":-282},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"319844a55ae24029a007b595564ec350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":581,
                  "y":-282},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f207602e2fea4d7eaecb365b8a82f8be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5dc153029b44898880787f612a57ba9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"bdd0df7a89a54f188b476e9c609b5d2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad0d3ffe8ff4b7cb8d05585b0fb5bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"89a6fe8f2aea41f08897f4b8215b907c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":280,
              "y":80},
            "size":{
              "width":121,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e71e4118974b2388341997d0aca5f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":280,
                  "y":80},
                "size":{
                  "width":121,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95ada5f56de642ba8e31b4d0ddf94dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0535ba2230794ac0924c5f1f29bbd127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbf8926a63e8464da055ef86ab3dae9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdbcd8229d6d48b7ade4a81065d74256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"aec8452db264420d853c9f2c4e71e41e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1050},
            "size":{
              "width":640,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63959ba6127e4ac5968e726ba3eccf3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1050},
                "size":{
                  "width":640,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u20.png"}},
{
          "id":"9154a8df88084581909f0b706de8de83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":54,
              "y":1080},
            "size":{
              "width":591,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e38fabbe0548179b4bca880b42af07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":1080},
                "size":{
                  "width":591,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4a1fd5c722c4c0fb70e4167339ed2ef",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1115},
            "size":{
              "width":520,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/聊天/u24_line.png"}},
{
          "id":"a02deb225f5b4cc09247adf8cdbf588d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":1096},
            "size":{
              "width":10,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/聊天/u25_line.png"}},
{
          "id":"ce8a651d1536420893d2f746675cc291",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":554,
              "y":1096},
            "size":{
              "width":10,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/聊天/u25_line.png"}},
{
          "id":"a6ea0d83e7484197b092a79422299133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":1091},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df87829e6a2a48a9ade210a2a375b38a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":1091},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u27.png"}},
{
          "id":"8b4cf25ae609469683d9974daf0f1b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":597,
              "y":1092},
            "size":{
              "width":33,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a27a0dc6442541d582e224ba8d4e0e70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":597,
                  "y":1092},
                "size":{
                  "width":33,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5b981a85b46433384dfff60b11d0474",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":238,
              "y":183},
            "size":{
              "width":205,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f88ed358066b4a8b85902722f40bd6ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":238,
                  "y":183},
                "size":{
                  "width":205,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2a403d92ef74e7fa659bd60ad6fb371",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":242},
            "size":{
              "width":336,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dd60ba13434b8989463416c62d7dcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":242},
                "size":{
                  "width":336,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u33.png"}},
{
          "id":"b75b53d69497457683f2d9823ec6569f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":242},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ee21a6614a4b78adf6205c9b88a99d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":242},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"7069743bec254443b81c2ffe70956914",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":138,
              "y":266},
            "size":{
              "width":326,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9a203ec0c34680896c1b3d7b09c0f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":138,
                  "y":266},
                "size":{
                  "width":326,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13394556893e489bb22ac1b81ad78a92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":344},
            "size":{
              "width":450,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4389b4ff2340289ed1f7c35c6d3053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":344},
                "size":{
                  "width":450,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u39.png"}},
{
          "id":"d60f705362144df9b3f745ec502f05ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":560,
              "y":344},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e802af2ab54d6ab5df866e8eb78b13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":560,
                  "y":344},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"e26d85580c384912b7f89e88168c51bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":124,
              "y":363},
            "size":{
              "width":426,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0d8462db524fe880b168046b3c0580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":124,
                  "y":363},
                "size":{
                  "width":426,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b1f8ef76a2b419a9652cf264d312d28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":459},
            "size":{
              "width":336,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ea204779a294426a445534741425505",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":459},
                "size":{
                  "width":336,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u33.png"}},
{
          "id":"4617a128082b467abadbc7a68668c4cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":459},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b8491919d96478bad4e05a00545feb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":459},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"e76c588aac654395893c4ddc06d9a206",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":138,
              "y":483},
            "size":{
              "width":251,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28c62112915c46f3805919573f38093a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":138,
                  "y":483},
                "size":{
                  "width":251,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1029f8cbd84e6b9b0994405559a66d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":547,
              "y":74},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "0d47056e911341f598a3a2a5e453f2c4":{
      "scriptId":"u0"},
    "5d3f3a1f00ad4ca0a7364f726aa59646":{
      "scriptId":"u1"},
    "a415c9e3b8c54b71be4e573a692079d4":{
      "scriptId":"u2"},
    "bf18c1d2db0f4a16a800507f14ef0155":{
      "scriptId":"u3"},
    "24758bf874124b849e3167b9f2453ffe":{
      "scriptId":"u4"},
    "53d2a8bae51e4a4399faef4265598ab6":{
      "scriptId":"u5"},
    "503c59d5cbec4ee797a034dae5e93fa8":{
      "scriptId":"u6"},
    "de07146da2a3450aa005ee013b608068":{
      "scriptId":"u7"},
    "0af074dcbe6d4f56ae015f567d637767":{
      "scriptId":"u8"},
    "319844a55ae24029a007b595564ec350":{
      "scriptId":"u9"},
    "f207602e2fea4d7eaecb365b8a82f8be":{
      "scriptId":"u10"},
    "b5dc153029b44898880787f612a57ba9":{
      "scriptId":"u11"},
    "bdd0df7a89a54f188b476e9c609b5d2a":{
      "scriptId":"u12"},
    "3ad0d3ffe8ff4b7cb8d05585b0fb5bd2":{
      "scriptId":"u13"},
    "89a6fe8f2aea41f08897f4b8215b907c":{
      "scriptId":"u14"},
    "11e71e4118974b2388341997d0aca5f8":{
      "scriptId":"u15"},
    "95ada5f56de642ba8e31b4d0ddf94dda":{
      "scriptId":"u16"},
    "0535ba2230794ac0924c5f1f29bbd127":{
      "scriptId":"u17"},
    "fbf8926a63e8464da055ef86ab3dae9a":{
      "scriptId":"u18"},
    "fdbcd8229d6d48b7ade4a81065d74256":{
      "scriptId":"u19"},
    "aec8452db264420d853c9f2c4e71e41e":{
      "scriptId":"u20"},
    "63959ba6127e4ac5968e726ba3eccf3c":{
      "scriptId":"u21"},
    "9154a8df88084581909f0b706de8de83":{
      "scriptId":"u22"},
    "45e38fabbe0548179b4bca880b42af07":{
      "scriptId":"u23"},
    "e4a1fd5c722c4c0fb70e4167339ed2ef":{
      "scriptId":"u24"},
    "a02deb225f5b4cc09247adf8cdbf588d":{
      "scriptId":"u25"},
    "ce8a651d1536420893d2f746675cc291":{
      "scriptId":"u26"},
    "a6ea0d83e7484197b092a79422299133":{
      "scriptId":"u27"},
    "df87829e6a2a48a9ade210a2a375b38a":{
      "scriptId":"u28"},
    "8b4cf25ae609469683d9974daf0f1b00":{
      "scriptId":"u29"},
    "a27a0dc6442541d582e224ba8d4e0e70":{
      "scriptId":"u30"},
    "d5b981a85b46433384dfff60b11d0474":{
      "scriptId":"u31"},
    "f88ed358066b4a8b85902722f40bd6ad":{
      "scriptId":"u32"},
    "f2a403d92ef74e7fa659bd60ad6fb371":{
      "scriptId":"u33"},
    "03dd60ba13434b8989463416c62d7dcf":{
      "scriptId":"u34"},
    "b75b53d69497457683f2d9823ec6569f":{
      "scriptId":"u35"},
    "08ee21a6614a4b78adf6205c9b88a99d":{
      "scriptId":"u36"},
    "7069743bec254443b81c2ffe70956914":{
      "scriptId":"u37"},
    "aa9a203ec0c34680896c1b3d7b09c0f2":{
      "scriptId":"u38"},
    "13394556893e489bb22ac1b81ad78a92":{
      "scriptId":"u39"},
    "ee4389b4ff2340289ed1f7c35c6d3053":{
      "scriptId":"u40"},
    "d60f705362144df9b3f745ec502f05ee":{
      "scriptId":"u41"},
    "28e802af2ab54d6ab5df866e8eb78b13":{
      "scriptId":"u42"},
    "e26d85580c384912b7f89e88168c51bf":{
      "scriptId":"u43"},
    "ee0d8462db524fe880b168046b3c0580":{
      "scriptId":"u44"},
    "2b1f8ef76a2b419a9652cf264d312d28":{
      "scriptId":"u45"},
    "2ea204779a294426a445534741425505":{
      "scriptId":"u46"},
    "4617a128082b467abadbc7a68668c4cf":{
      "scriptId":"u47"},
    "1b8491919d96478bad4e05a00545feb6":{
      "scriptId":"u48"},
    "e76c588aac654395893c4ddc06d9a206":{
      "scriptId":"u49"},
    "28c62112915c46f3805919573f38093a":{
      "scriptId":"u50"},
    "0e1029f8cbd84e6b9b0994405559a66d":{
      "scriptId":"u51"}}});