$axure.loadCurrentPage({
  "url":"发帖子.html",
  "generationDate":new Date(1426560721281.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3b089ae1ad1c4daf96c4cf8e127cc9f2",
    "type":"Axure:Page",
    "name":"发帖子",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c19404ac72ae40a2ba672db4bfe3876d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":-339.5},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f3166c1a8ae4e19a0b7ff5f10ec3b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":-339.5},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"6de9585a286f4b65a119e2a26e24ab4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":306,
              "y":-280},
            "size":{
              "width":115,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f78a2c6b92bc4b6e97002024e797e23d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":306,
                  "y":-280},
                "size":{
                  "width":115,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7950fe515504849a9cf3ee50e9d0c27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":-339.5},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6c6d7e4b42f483788c4b97c73e4b5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":-339.5},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"2081f234fb17443fbf50d592e7c18006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":584,
              "y":-284.5},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fa70f98c53546b98210cd38cb44aac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":584,
                  "y":-284.5},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u48.png"}},
{
          "id":"7417a5cdd0414655ace7f3acefbe68b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":58,
              "y":-274},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba6e8c90c61497683f7a68bfaee74a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":-274},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"193b26a885eb417fa8353a5b16b60df5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":58,
              "y":-186},
            "size":{
              "width":606,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e638172798439891eec30f6865ea8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":-186},
                "size":{
                  "width":606,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7675e6bcfe184590a0a3aa516dac728b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf223e727784230a3a1522ef165de5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发帖子/u12.png"}},
{
          "id":"362d82389c1d4b7b8c8bccc25972654a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5543da96793489eb99c5aa72bc2e9e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"b42620922d964e0f9a32e069a7f29476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":282,
              "y":80},
            "size":{
              "width":115,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f893a942aec43d68d45f2cdc32a49e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":282,
                  "y":80},
                "size":{
                  "width":115,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ed3162bd3c543bd8db5dbc43f4820d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c21d39de27f4437842bb1fc88d44a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"e924e919181c4f978197e829d76f281e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":640,
              "height":487}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03babca83b14881aab31e824b2d854e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":640,
                  "height":487}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发帖子/u20.png"}},
{
          "id":"25c3f51b71514a70b26913f387a06c46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":560,
              "y":75},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b8dae321204eaeae9d3d2c06232ab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":560,
                  "y":75},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/社区/u48.png"}},
{
          "id":"8f7ea49a3cf049fda0777263d2b38699",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":611,
              "y":1094},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4feb8b9b77c489185854e5d1f49bde8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":611,
                  "y":1094},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"371d180541c34d48b3ad8d0cddde9920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":85},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eadc58165504f46b3de21fbfd5edf7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":85},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"154fc75f45714ec8b8e0bdc2e03742b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":636},
            "size":{
              "width":640,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aed613daf944f97b134636c0da023e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":636},
                "size":{
                  "width":640,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发帖子/u28.png"}},
{
          "id":"8be01b58428643eb97bc4a5b208a423c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":308,
              "y":850},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181835185c3f40388d15e708a7a173f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":308,
                  "y":850},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8407489e31b84c2f8aedaf899621b7af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":34,
              "y":174},
            "size":{
              "width":606,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49d90f2c71654e7eb7b0a7287d3010a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":174},
                "size":{
                  "width":606,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7455411fb8c14467a6a97d82f9bfcffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":490},
            "size":{
              "width":120,
              "height":120},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0297d7db8ea4db4b54acc1a12eab4eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":490},
                "size":{
                  "width":120,
                  "height":120},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发帖子/u34.png"}},
{
          "id":"9cfc30d226d84b22ba576a880877eb7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"72px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":58,
              "y":513},
            "size":{
              "width":73,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f196bdccb88c40cd87e286c422d6d4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"72px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":513},
                "size":{
                  "width":73,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c19404ac72ae40a2ba672db4bfe3876d":{
      "scriptId":"u0"},
    "7f3166c1a8ae4e19a0b7ff5f10ec3b78":{
      "scriptId":"u1"},
    "6de9585a286f4b65a119e2a26e24ab4c":{
      "scriptId":"u2"},
    "f78a2c6b92bc4b6e97002024e797e23d":{
      "scriptId":"u3"},
    "d7950fe515504849a9cf3ee50e9d0c27":{
      "scriptId":"u4"},
    "d6c6d7e4b42f483788c4b97c73e4b5d7":{
      "scriptId":"u5"},
    "2081f234fb17443fbf50d592e7c18006":{
      "scriptId":"u6"},
    "8fa70f98c53546b98210cd38cb44aac6":{
      "scriptId":"u7"},
    "7417a5cdd0414655ace7f3acefbe68b4":{
      "scriptId":"u8"},
    "eba6e8c90c61497683f7a68bfaee74a3":{
      "scriptId":"u9"},
    "193b26a885eb417fa8353a5b16b60df5":{
      "scriptId":"u10"},
    "92e638172798439891eec30f6865ea8b":{
      "scriptId":"u11"},
    "7675e6bcfe184590a0a3aa516dac728b":{
      "scriptId":"u12"},
    "adf223e727784230a3a1522ef165de5e":{
      "scriptId":"u13"},
    "362d82389c1d4b7b8c8bccc25972654a":{
      "scriptId":"u14"},
    "e5543da96793489eb99c5aa72bc2e9e1":{
      "scriptId":"u15"},
    "b42620922d964e0f9a32e069a7f29476":{
      "scriptId":"u16"},
    "9f893a942aec43d68d45f2cdc32a49e8":{
      "scriptId":"u17"},
    "2ed3162bd3c543bd8db5dbc43f4820d9":{
      "scriptId":"u18"},
    "0c21d39de27f4437842bb1fc88d44a8e":{
      "scriptId":"u19"},
    "e924e919181c4f978197e829d76f281e":{
      "scriptId":"u20"},
    "f03babca83b14881aab31e824b2d854e":{
      "scriptId":"u21"},
    "25c3f51b71514a70b26913f387a06c46":{
      "scriptId":"u22"},
    "85b8dae321204eaeae9d3d2c06232ab0":{
      "scriptId":"u23"},
    "8f7ea49a3cf049fda0777263d2b38699":{
      "scriptId":"u24"},
    "b4feb8b9b77c489185854e5d1f49bde8":{
      "scriptId":"u25"},
    "371d180541c34d48b3ad8d0cddde9920":{
      "scriptId":"u26"},
    "1eadc58165504f46b3de21fbfd5edf7b":{
      "scriptId":"u27"},
    "154fc75f45714ec8b8e0bdc2e03742b4":{
      "scriptId":"u28"},
    "7aed613daf944f97b134636c0da023e4":{
      "scriptId":"u29"},
    "8be01b58428643eb97bc4a5b208a423c":{
      "scriptId":"u30"},
    "181835185c3f40388d15e708a7a173f6":{
      "scriptId":"u31"},
    "8407489e31b84c2f8aedaf899621b7af":{
      "scriptId":"u32"},
    "49d90f2c71654e7eb7b0a7287d3010a8":{
      "scriptId":"u33"},
    "7455411fb8c14467a6a97d82f9bfcffd":{
      "scriptId":"u34"},
    "a0297d7db8ea4db4b54acc1a12eab4eb":{
      "scriptId":"u35"},
    "9cfc30d226d84b22ba576a880877eb7e":{
      "scriptId":"u36"},
    "f196bdccb88c40cd87e286c422d6d4c4":{
      "scriptId":"u37"}}});