$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1429527572604.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"76d38a11674e43c2b62ded037ad562b4",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62fce5bc0d974622a26c964c16460204",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3902d516eebd43b8aa232b41e08de676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"1c48b6aa6733466aa14bc620eb5ef4d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"696f25eab1d44698981caa643ac6e3c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"b437826bb0654ef4a9ca76078800c233",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78ee86479e104c3e8083a67045032793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"78d063f7618e4aa5887589b9a27f8317",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":172,
              "y":627},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f983aae94144cfe9aa80f4770c5609c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":172,
                  "y":627},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebe6a19c789641d5acc4a34641ecc649",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":263.5,
              "y":120},
            "size":{
              "width":153,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a2bba63f1e542d6948f56c7718daae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":263.5,
                  "y":120},
                "size":{
                  "width":153,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dac8ce1dd1d4c688eddb039361fe837",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":247},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57bf17c0225e482e998259525d60c6f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":247},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"7bc8bb1f175e4e84aa131fe910ec5427",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":346},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab6a083d29c4d39a954d868492cdcb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":346},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"81528169dfbb47c8a13cb69a96b83b06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":262},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"065747ef694e4c0d883d2b3541e510d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":262},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"9f41c6569430442aa31a031b39d9cefe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":157,
              "y":278},
            "size":{
              "width":109,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8260279a31c942af94e8de07715f055e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":157,
                  "y":278},
                "size":{
                  "width":109,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b3585fc5f2f4a5fb9eb5163aa03b7ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":362},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746a366124a748189f723cfff7a12c89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":362},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"72b9dc5d22d04fe4926e2f185cb73341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":157,
              "y":378},
            "size":{
              "width":145,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38665bf1659249de912dd5f26423c98e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":157,
                  "y":378},
                "size":{
                  "width":145,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d64d303962d54d25972a5a355b6eb7cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":500},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44b544567e24160b819837bd6357b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":500},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"66751d10d9af44308a8d45c6dc8aa971",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":304,
              "y":532},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b29c1a4141104587be40e31ff2711acc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":532},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"036e53e3f38b491f8ca8f02faa03e3c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":386,
              "y":627},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11671827589e44459974444d809c02dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":386,
                  "y":627},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d950f2cf1614499b9e0cc8871e565b26",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":622},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u28_line.png"}},
{
          "id":"e74f24da881c4f17a7a94a1ce5361105",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":810,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3955baf1b13499a8ed822824826106b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":810,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"29ed15bfde874de79a81583041e5da61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":20},
            "size":{
              "width":640,
              "height":1140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4f1c8780cdc466cb32bd92b90df57d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"8bc25ccd2cce408e8782f832563b8697",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdddaa4f484d4a8ab425c0194757c8ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"3966bba82802424f8770a05746a6bd34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":962,
              "y":627},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9bd7e88bfde404eaddc7edef8b2b710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":962,
                  "y":627},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"814ac61ecbed46f1ac573eb00f241d7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":1054,
              "y":120},
            "size":{
              "width":153,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9950b51bb940128915dea27ca341bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":1054,
                  "y":120},
                "size":{
                  "width":153,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da6e25c727e54d478a02b0fda423606f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":247},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc2dc2ff72d4294a2865371041941eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":247},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"2e426dba34334ff2a58ac8dee0c39538",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":346},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9010ebb7131045fd87031a7e3c0061a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":346},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"c2a74746db1a417ab6eed52d7ec0809d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":840,
              "y":262},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75b8cd83795e49a1bc3ca41acab06983",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":840,
                  "y":262},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"01feb544f20b4733a4646c866ace3f82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":947,
              "y":278},
            "size":{
              "width":109,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f55d9cade034efbae28ca3165742ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":947,
                  "y":278},
                "size":{
                  "width":109,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70bfb59b3a404383a0c97a619863ce11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":840,
              "y":362},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b4429bb11b4b2d980c4a23a85359b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":840,
                  "y":362},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"cd5ee700a9c8477490910c63232ba42f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":947,
              "y":378},
            "size":{
              "width":145,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a805a891563542ebb14fbc07c925fccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":947,
                  "y":378},
                "size":{
                  "width":145,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"566c4caa157347599c52ca5e42eadde1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":500},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"267f076c12bb494cba1a581c6fea58bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":500},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"1d841d2f1f1f4a3397ea89845a2c16e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":1094,
              "y":532},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"053cddfecbc4428793410ef34444a9c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":1094,
                  "y":532},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"194718cc88f7486a9242487e00d4a55d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"25px",
            "fontWeight":"200",
            "location":{
              "x":1176,
              "y":627},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1a6aa2b474f45f19c21c41aa195abd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"25px",
                "fontWeight":"200",
                "location":{
                  "x":1176,
                  "y":627},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2945adcc387c4b57936636af198ce68c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1125,
              "y":622},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u28_line.png"}},
{
          "id":"fe93dd64fa6045f5aa7efdb4a9704aa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":830,
              "y":178},
            "size":{
              "width":600,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b90fe7e047ca4044ab42e5d4a47d89ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":830,
                  "y":178},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u58.png"}},
{
          "id":"f012f5616b4140539e228090097c82c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":936,
              "y":212},
            "size":{
              "width":181,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd874fa6748f448e9804c0fd310221a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":212},
                "size":{
                  "width":181,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84ca17feacfb443a8e94462972b35a3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":845,
              "y":193},
            "size":{
              "width":65,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43eeaa0a5ce46438267b4a17dd53406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":845,
                  "y":193},
                "size":{
                  "width":65,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u62.png"}},
{
          "id":"f20cce6757904a48a263508ae09c3b27",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":362},
            "size":{
              "width":100,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u64_line.png"}},
{
          "id":"87819bb1f2af4af9895307a0d4971921",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":691,
              "y":295},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7911ace06bd4437b18347c2596f8afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":691,
                  "y":295},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "62fce5bc0d974622a26c964c16460204":{
      "scriptId":"u0"},
    "3902d516eebd43b8aa232b41e08de676":{
      "scriptId":"u1"},
    "1c48b6aa6733466aa14bc620eb5ef4d3":{
      "scriptId":"u2"},
    "696f25eab1d44698981caa643ac6e3c4":{
      "scriptId":"u3"},
    "b437826bb0654ef4a9ca76078800c233":{
      "scriptId":"u4"},
    "78ee86479e104c3e8083a67045032793":{
      "scriptId":"u5"},
    "78d063f7618e4aa5887589b9a27f8317":{
      "scriptId":"u6"},
    "6f983aae94144cfe9aa80f4770c5609c":{
      "scriptId":"u7"},
    "ebe6a19c789641d5acc4a34641ecc649":{
      "scriptId":"u8"},
    "3a2bba63f1e542d6948f56c7718daae1":{
      "scriptId":"u9"},
    "8dac8ce1dd1d4c688eddb039361fe837":{
      "scriptId":"u10"},
    "57bf17c0225e482e998259525d60c6f9":{
      "scriptId":"u11"},
    "7bc8bb1f175e4e84aa131fe910ec5427":{
      "scriptId":"u12"},
    "8ab6a083d29c4d39a954d868492cdcb9":{
      "scriptId":"u13"},
    "81528169dfbb47c8a13cb69a96b83b06":{
      "scriptId":"u14"},
    "065747ef694e4c0d883d2b3541e510d8":{
      "scriptId":"u15"},
    "9f41c6569430442aa31a031b39d9cefe":{
      "scriptId":"u16"},
    "8260279a31c942af94e8de07715f055e":{
      "scriptId":"u17"},
    "9b3585fc5f2f4a5fb9eb5163aa03b7ed":{
      "scriptId":"u18"},
    "746a366124a748189f723cfff7a12c89":{
      "scriptId":"u19"},
    "72b9dc5d22d04fe4926e2f185cb73341":{
      "scriptId":"u20"},
    "38665bf1659249de912dd5f26423c98e":{
      "scriptId":"u21"},
    "d64d303962d54d25972a5a355b6eb7cb":{
      "scriptId":"u22"},
    "a44b544567e24160b819837bd6357b23":{
      "scriptId":"u23"},
    "66751d10d9af44308a8d45c6dc8aa971":{
      "scriptId":"u24"},
    "b29c1a4141104587be40e31ff2711acc":{
      "scriptId":"u25"},
    "036e53e3f38b491f8ca8f02faa03e3c6":{
      "scriptId":"u26"},
    "11671827589e44459974444d809c02dc":{
      "scriptId":"u27"},
    "d950f2cf1614499b9e0cc8871e565b26":{
      "scriptId":"u28"},
    "e74f24da881c4f17a7a94a1ce5361105":{
      "scriptId":"u29"},
    "e3955baf1b13499a8ed822824826106b":{
      "scriptId":"u30"},
    "29ed15bfde874de79a81583041e5da61":{
      "scriptId":"u31"},
    "b4f1c8780cdc466cb32bd92b90df57d6":{
      "scriptId":"u32"},
    "8bc25ccd2cce408e8782f832563b8697":{
      "scriptId":"u33"},
    "bdddaa4f484d4a8ab425c0194757c8ac":{
      "scriptId":"u34"},
    "3966bba82802424f8770a05746a6bd34":{
      "scriptId":"u35"},
    "a9bd7e88bfde404eaddc7edef8b2b710":{
      "scriptId":"u36"},
    "814ac61ecbed46f1ac573eb00f241d7f":{
      "scriptId":"u37"},
    "0b9950b51bb940128915dea27ca341bd":{
      "scriptId":"u38"},
    "da6e25c727e54d478a02b0fda423606f":{
      "scriptId":"u39"},
    "1fc2dc2ff72d4294a2865371041941eb":{
      "scriptId":"u40"},
    "2e426dba34334ff2a58ac8dee0c39538":{
      "scriptId":"u41"},
    "9010ebb7131045fd87031a7e3c0061a7":{
      "scriptId":"u42"},
    "c2a74746db1a417ab6eed52d7ec0809d":{
      "scriptId":"u43"},
    "75b8cd83795e49a1bc3ca41acab06983":{
      "scriptId":"u44"},
    "01feb544f20b4733a4646c866ace3f82":{
      "scriptId":"u45"},
    "4f55d9cade034efbae28ca3165742ead":{
      "scriptId":"u46"},
    "70bfb59b3a404383a0c97a619863ce11":{
      "scriptId":"u47"},
    "92b4429bb11b4b2d980c4a23a85359b2":{
      "scriptId":"u48"},
    "cd5ee700a9c8477490910c63232ba42f":{
      "scriptId":"u49"},
    "a805a891563542ebb14fbc07c925fccf":{
      "scriptId":"u50"},
    "566c4caa157347599c52ca5e42eadde1":{
      "scriptId":"u51"},
    "267f076c12bb494cba1a581c6fea58bc":{
      "scriptId":"u52"},
    "1d841d2f1f1f4a3397ea89845a2c16e6":{
      "scriptId":"u53"},
    "053cddfecbc4428793410ef34444a9c1":{
      "scriptId":"u54"},
    "194718cc88f7486a9242487e00d4a55d":{
      "scriptId":"u55"},
    "c1a6aa2b474f45f19c21c41aa195abd4":{
      "scriptId":"u56"},
    "2945adcc387c4b57936636af198ce68c":{
      "scriptId":"u57"},
    "fe93dd64fa6045f5aa7efdb4a9704aa5":{
      "scriptId":"u58"},
    "b90fe7e047ca4044ab42e5d4a47d89ec":{
      "scriptId":"u59"},
    "f012f5616b4140539e228090097c82c3":{
      "scriptId":"u60"},
    "bd874fa6748f448e9804c0fd310221a7":{
      "scriptId":"u61"},
    "84ca17feacfb443a8e94462972b35a3e":{
      "scriptId":"u62"},
    "c43eeaa0a5ce46438267b4a17dd53406":{
      "scriptId":"u63"},
    "f20cce6757904a48a263508ae09c3b27":{
      "scriptId":"u64"},
    "87819bb1f2af4af9895307a0d4971921":{
      "scriptId":"u65"},
    "e7911ace06bd4437b18347c2596f8afd":{
      "scriptId":"u66"}}});