$axure.loadCurrentPage({
  "url":"信息.html",
  "generationDate":new Date(1426560719670.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"44a169b7bc1946d6aa847a5c5041aa27",
    "type":"Axure:Page",
    "name":"信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48ac79afc605418c97e05cdb9a9ddb4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ec3c1e5b3eb46a7a73b3fee4dfea20a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"050a35a0a21141daaada242ffca1c89b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49c7d55540d545b3b56bcf341185a9d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"d5da33739c154644969fc5811d43e4da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26def67ecd31438aa5cefdb1db9a0a1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"ce417f9a76044d1bb5d26f8e58c245de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":300,
              "y":80},
            "size":{
              "width":79,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a500abc13d64d65ad1681422bd75d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":300,
                  "y":80},
                "size":{
                  "width":79,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e40a99c10434866befc4648d65f31c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":173},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf7f75fff53e4371b2e2b276faf4e372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":173},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"ba5c289577754beb80ad769d6fa62d43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":193},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f79326e40aa24785a665a2626d3eca14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":193},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u26.png"}},
{
          "id":"7b4df4651be04f5ea3991f625a9807a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":133,
              "y":218},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c84deebbf8467ea331e0bb8b3f4ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":133,
                  "y":218},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"573dd793a24d420f81906157d34be62f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":668},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"061be43a712d4f63909e7861767714b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":668},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"617c4759a89444abad2f7c0c146d12d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":694},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3b3e5d891f45029a7449edeab74a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":694},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0662a25e05754bf3abc2bf9093bb0010",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":748},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8dee0bde4e6462f91353736bed8a9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":748},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"a004cd65d1d34a60a8394063127a3f78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":772},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b51e357668cf43b3aefc01fc505da2ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":772},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43e7f0a2185c47dcb44093211ab07c62",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":547,
              "y":74},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"141e4fa9b81b41ad908ac87316b09281",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":826},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16655f94df3240bdb786d376224efa0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":826},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"8a4c007ac28e410db3aea2bb03c96919",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":852},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf33f9e398d84ddaa14d5e38ac44ff77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":852},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84ccdcca11824d5a9bdfde71e0ab7c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":906},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6365e46d51240bf8f85ef0d53043c1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":906},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"8f4e76ad29f94bceb326e494b1823aab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":930},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1aef04fe28e4c5090f1a78f927b3586",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":930},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cca493767883499c9a20a27246c9f2e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":411},
            "size":{
              "width":640,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e6e195e2cc04dc38f61b85f99b1940e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":411},
                "size":{
                  "width":640,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息/u31.png"}},
{
          "id":"2285950474d846da9533fef7e6f12dcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":436},
            "size":{
              "width":57,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06eb5f9fedfe47e080962fc28b5c297c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":436},
                "size":{
                  "width":57,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4abc6fdb26ba4bbda2cff7d6d058d869",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":590},
            "size":{
              "width":640,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b361b22d80b4c29a0b6c0ab892307ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":590},
                "size":{
                  "width":640,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"2f6d9ecf4d604345be665b152216aa61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":616},
            "size":{
              "width":113,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8a0b33a03d44f12a41f1dfff9075f7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":616},
                "size":{
                  "width":113,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f382c348caa4827a00c5af763ee3ddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":292},
            "size":{
              "width":640,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf008f34d2c14c6fa626d730181c8df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":292},
                "size":{
                  "width":640,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"2e53ea8324b84965bc2dfb82d931ffe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":337},
            "size":{
              "width":141,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"176dbb8453864e4986d3b33cd45a3680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":337},
                "size":{
                  "width":141,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd6ffd414b73486db5aa6150b1dabf1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":577,
              "y":322},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b38426ff2348389b19ea4052b55124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":577,
                  "y":322},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息_1/u30.png"}},
{
          "id":"7f3f5b5d6b75475e97a3a633105350c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":353,
              "y":620},
            "size":{
              "width":284,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c7f163529c34607b40d33374925750f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":353,
                  "y":620},
                "size":{
                  "width":284,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40d56a5f4ca74d0387fd4c0894f685f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":524,
              "y":698},
            "size":{
              "width":113,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b13a9eedfbc42b287c08a6b178af625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":524,
                  "y":698},
                "size":{
                  "width":113,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3f4067bb4784818b019819a35c3746c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":496,
              "y":774},
            "size":{
              "width":141,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae94231cba0439799e4a92ddffa54f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":496,
                  "y":774},
                "size":{
                  "width":141,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c205720c57a4b759e65a31a8912e35c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":524,
              "y":852},
            "size":{
              "width":113,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a007c985311245dd9c48d90fbb4fe8a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":524,
                  "y":852},
                "size":{
                  "width":113,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63ddadc04daf41a38d53c931daa6f000",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":552,
              "y":932},
            "size":{
              "width":85,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdefe58e407548ebb6010612e8a35888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":552,
                  "y":932},
                "size":{
                  "width":85,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79dceb2cfebb40c08f755adf9e02d07c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":36,
              "y":487},
            "size":{
              "width":385,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2974b722607342b3ae97b2cafaf33db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":487},
                "size":{
                  "width":385,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"273b7bbad7864068ab49f8a93eb1bde0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87509fb2841d4292be3f5dbb86ea2e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "48ac79afc605418c97e05cdb9a9ddb4b":{
      "scriptId":"u0"},
    "5ec3c1e5b3eb46a7a73b3fee4dfea20a":{
      "scriptId":"u1"},
    "050a35a0a21141daaada242ffca1c89b":{
      "scriptId":"u2"},
    "49c7d55540d545b3b56bcf341185a9d0":{
      "scriptId":"u3"},
    "d5da33739c154644969fc5811d43e4da":{
      "scriptId":"u4"},
    "26def67ecd31438aa5cefdb1db9a0a1a":{
      "scriptId":"u5"},
    "ce417f9a76044d1bb5d26f8e58c245de":{
      "scriptId":"u6"},
    "3a500abc13d64d65ad1681422bd75d42":{
      "scriptId":"u7"},
    "6e40a99c10434866befc4648d65f31c7":{
      "scriptId":"u8"},
    "cf7f75fff53e4371b2e2b276faf4e372":{
      "scriptId":"u9"},
    "ba5c289577754beb80ad769d6fa62d43":{
      "scriptId":"u10"},
    "f79326e40aa24785a665a2626d3eca14":{
      "scriptId":"u11"},
    "7b4df4651be04f5ea3991f625a9807a6":{
      "scriptId":"u12"},
    "10c84deebbf8467ea331e0bb8b3f4ae5":{
      "scriptId":"u13"},
    "573dd793a24d420f81906157d34be62f":{
      "scriptId":"u14"},
    "061be43a712d4f63909e7861767714b5":{
      "scriptId":"u15"},
    "617c4759a89444abad2f7c0c146d12d4":{
      "scriptId":"u16"},
    "cb3b3e5d891f45029a7449edeab74a72":{
      "scriptId":"u17"},
    "0662a25e05754bf3abc2bf9093bb0010":{
      "scriptId":"u18"},
    "c8dee0bde4e6462f91353736bed8a9ad":{
      "scriptId":"u19"},
    "a004cd65d1d34a60a8394063127a3f78":{
      "scriptId":"u20"},
    "b51e357668cf43b3aefc01fc505da2ee":{
      "scriptId":"u21"},
    "43e7f0a2185c47dcb44093211ab07c62":{
      "scriptId":"u22"},
    "141e4fa9b81b41ad908ac87316b09281":{
      "scriptId":"u23"},
    "16655f94df3240bdb786d376224efa0e":{
      "scriptId":"u24"},
    "8a4c007ac28e410db3aea2bb03c96919":{
      "scriptId":"u25"},
    "cf33f9e398d84ddaa14d5e38ac44ff77":{
      "scriptId":"u26"},
    "84ccdcca11824d5a9bdfde71e0ab7c0f":{
      "scriptId":"u27"},
    "d6365e46d51240bf8f85ef0d53043c1b":{
      "scriptId":"u28"},
    "8f4e76ad29f94bceb326e494b1823aab":{
      "scriptId":"u29"},
    "f1aef04fe28e4c5090f1a78f927b3586":{
      "scriptId":"u30"},
    "cca493767883499c9a20a27246c9f2e9":{
      "scriptId":"u31"},
    "4e6e195e2cc04dc38f61b85f99b1940e":{
      "scriptId":"u32"},
    "2285950474d846da9533fef7e6f12dcb":{
      "scriptId":"u33"},
    "06eb5f9fedfe47e080962fc28b5c297c":{
      "scriptId":"u34"},
    "4abc6fdb26ba4bbda2cff7d6d058d869":{
      "scriptId":"u35"},
    "2b361b22d80b4c29a0b6c0ab892307ea":{
      "scriptId":"u36"},
    "2f6d9ecf4d604345be665b152216aa61":{
      "scriptId":"u37"},
    "a8a0b33a03d44f12a41f1dfff9075f7a":{
      "scriptId":"u38"},
    "6f382c348caa4827a00c5af763ee3ddb":{
      "scriptId":"u39"},
    "cf008f34d2c14c6fa626d730181c8df5":{
      "scriptId":"u40"},
    "2e53ea8324b84965bc2dfb82d931ffe1":{
      "scriptId":"u41"},
    "176dbb8453864e4986d3b33cd45a3680":{
      "scriptId":"u42"},
    "fd6ffd414b73486db5aa6150b1dabf1f":{
      "scriptId":"u43"},
    "46b38426ff2348389b19ea4052b55124":{
      "scriptId":"u44"},
    "7f3f5b5d6b75475e97a3a633105350c9":{
      "scriptId":"u45"},
    "2c7f163529c34607b40d33374925750f":{
      "scriptId":"u46"},
    "40d56a5f4ca74d0387fd4c0894f685f3":{
      "scriptId":"u47"},
    "0b13a9eedfbc42b287c08a6b178af625":{
      "scriptId":"u48"},
    "a3f4067bb4784818b019819a35c3746c":{
      "scriptId":"u49"},
    "4ae94231cba0439799e4a92ddffa54f7":{
      "scriptId":"u50"},
    "8c205720c57a4b759e65a31a8912e35c":{
      "scriptId":"u51"},
    "a007c985311245dd9c48d90fbb4fe8a4":{
      "scriptId":"u52"},
    "63ddadc04daf41a38d53c931daa6f000":{
      "scriptId":"u53"},
    "cdefe58e407548ebb6010612e8a35888":{
      "scriptId":"u54"},
    "79dceb2cfebb40c08f755adf9e02d07c":{
      "scriptId":"u55"},
    "2974b722607342b3ae97b2cafaf33db7":{
      "scriptId":"u56"},
    "273b7bbad7864068ab49f8a93eb1bde0":{
      "scriptId":"u57"},
    "87509fb2841d4292be3f5dbb86ea2e76":{
      "scriptId":"u58"}}});