$axure.loadCurrentPage({
  "url":"填写邀请码.html",
  "generationDate":new Date(1429527575068.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6251dfdbde94a21b4ef843ac48f8fbd",
    "type":"Axure:Page",
    "name":"填写邀请码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d206a661dd554c59891a2f8e67b4f228",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe7ec63b84c470591835d85199878f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"7f62ecbbdbdd4bd094fa2c09ee02e7b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62756942d73d404597aefa69903081e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"9b3526bde0c546c89e400c1f42ff4240",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":245,
              "y":80},
            "size":{
              "width":190,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a553df8bc9844563952d21737dc1b26a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":245,
                  "y":80},
                "size":{
                  "width":190,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35454c521c9e40fbbf4fbeed5a1f6f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbac5a9057d14f7e9bac502e02beaa64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08b864d37d3f4631b2f80455f6c2511a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d456ed1b29e44a789db4d66fcad5ad5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"9d1ad2c9d4754cc9b5249507a43c7059",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":179.999984741211},
            "size":{
              "width":639,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1484f8dfe774f5f8420a9a52ab48585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":179.999984741211},
                "size":{
                  "width":639,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的邀请码/u14.png"}},
{
          "id":"868098a8ad8d4eda9be83a66b5915128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":38,
              "y":215},
            "size":{
              "width":169,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4de5880c62014aebb93ae30e933d382d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":215},
                "size":{
                  "width":169,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72e8f963db364cf08526fb29bef410b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":20,
              "y":1056},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61c8a5015864ef3a0054403dfbdc9e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":20,
                  "y":1056},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写邀请码/u14.png"}},
{
          "id":"5c77947834d745908677930b026b870b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":37,
              "y":1066},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b483539c3338401fa5e55f14121c187f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":37,
                  "y":1066},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"89685224c53c48aab0a531ca70a77ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"48px",
            "fontWeight":"200",
            "location":{
              "x":127.000007629395,
              "y":1066},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f01e6e470184cdb91bd4ddab4a8daf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"48px",
                "fontWeight":"200",
                "location":{
                  "x":127.000007629395,
                  "y":1066},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u22.png"}},
{
          "id":"3f233b9fbb694defa3a19669847356f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":500,
              "y":1066},
            "size":{
              "width":150,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad63e5c43ca043e5a51a3ebcfb6fc5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":500,
                  "y":1066},
                "size":{
                  "width":150,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写邀请码/u20.png"}},
{
          "id":"cb4b77c21e2b4dc2902815c9a5f528b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"30px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":513,
              "y":1088},
            "size":{
              "width":138,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30338b701e8c462a83a73e4602113b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"30px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":513,
                  "y":1088},
                "size":{
                  "width":138,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd82284a8407446caa119f10c5c364fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":572,
              "y":80},
            "size":{
              "width":88,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a928fbc28f774d68804da5649a9f2270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":572,
                  "y":80},
                "size":{
                  "width":88,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99c5c168138f428a9b5e7ec8ea071558",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":290},
            "size":{
              "width":424,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea54b9a2228c44dea97f53a872950ba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":290},
                "size":{
                  "width":424,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d206a661dd554c59891a2f8e67b4f228":{
      "scriptId":"u0"},
    "6fe7ec63b84c470591835d85199878f8":{
      "scriptId":"u1"},
    "7f62ecbbdbdd4bd094fa2c09ee02e7b6":{
      "scriptId":"u2"},
    "62756942d73d404597aefa69903081e9":{
      "scriptId":"u3"},
    "9b3526bde0c546c89e400c1f42ff4240":{
      "scriptId":"u4"},
    "a553df8bc9844563952d21737dc1b26a":{
      "scriptId":"u5"},
    "35454c521c9e40fbbf4fbeed5a1f6f0f":{
      "scriptId":"u6"},
    "cbac5a9057d14f7e9bac502e02beaa64":{
      "scriptId":"u7"},
    "08b864d37d3f4631b2f80455f6c2511a":{
      "scriptId":"u8"},
    "2d456ed1b29e44a789db4d66fcad5ad5":{
      "scriptId":"u9"},
    "9d1ad2c9d4754cc9b5249507a43c7059":{
      "scriptId":"u10"},
    "a1484f8dfe774f5f8420a9a52ab48585":{
      "scriptId":"u11"},
    "868098a8ad8d4eda9be83a66b5915128":{
      "scriptId":"u12"},
    "4de5880c62014aebb93ae30e933d382d":{
      "scriptId":"u13"},
    "72e8f963db364cf08526fb29bef410b6":{
      "scriptId":"u14"},
    "b61c8a5015864ef3a0054403dfbdc9e2":{
      "scriptId":"u15"},
    "5c77947834d745908677930b026b870b":{
      "scriptId":"u16"},
    "b483539c3338401fa5e55f14121c187f":{
      "scriptId":"u17"},
    "89685224c53c48aab0a531ca70a77ced":{
      "scriptId":"u18"},
    "5f01e6e470184cdb91bd4ddab4a8daf7":{
      "scriptId":"u19"},
    "3f233b9fbb694defa3a19669847356f7":{
      "scriptId":"u20"},
    "ad63e5c43ca043e5a51a3ebcfb6fc5fd":{
      "scriptId":"u21"},
    "cb4b77c21e2b4dc2902815c9a5f528b3":{
      "scriptId":"u22"},
    "30338b701e8c462a83a73e4602113b9c":{
      "scriptId":"u23"},
    "dd82284a8407446caa119f10c5c364fd":{
      "scriptId":"u24"},
    "a928fbc28f774d68804da5649a9f2270":{
      "scriptId":"u25"},
    "99c5c168138f428a9b5e7ec8ea071558":{
      "scriptId":"u26"},
    "ea54b9a2228c44dea97f53a872950ba5":{
      "scriptId":"u27"}}});