$axure.loadCurrentPage({
  "url":"省份.html",
  "generationDate":new Date(1431411283199.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1074c6a8c54b4c6890c595ad39936ab0",
    "type":"Axure:Page",
    "name":"省份",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9ef6a6d096924dc18bfc013248f25680",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3847e87fa3d415aadb2ceb8064d4965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"cd9ac50d1bf244f29359fc53da4ae705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00094dfd4c094b878f9d7bc860d9c6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":640,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"5e166351e68b4b5fa6338283b44dddbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":28},
            "size":{
              "width":640,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfa1f97d4ed74cbe9114002d453f083b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":28},
                "size":{
                  "width":640,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"c3570e13166a4a7da30ca1d37d4674d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":264,
              "y":80},
            "size":{
              "width":153,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a81d3f880dfc48a2ba26e8025bf277f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":264,
                  "y":80},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbebe60d4c394293865abd8139564ad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":571,
              "y":80},
            "size":{
              "width":69,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e79db2875dc4977813b3273e68e7a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":571,
                  "y":80},
                "size":{
                  "width":69,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75e6addffb5944e98b5f23093f0a0a4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":36,
              "y":80},
            "size":{
              "width":100,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fd3be60c8264457a0c88a6b9d65454b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":36,
                  "y":80},
                "size":{
                  "width":100,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c162c6db6fee4589b8428cb188a99b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f92e1407b8b47ef8694d3a319b1b1b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"797e53cc066c4ae78ce0bd259fd62068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":37,
              "y":201},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5dc5a3e93ce4b13a7e9d304ab606a1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":37,
                  "y":201},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a835654029940c0af4b61e740dd3e74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":201},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f32fcb6fc754305b4fe37ac78902d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":201},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed311f2e7a5c4231aa9626524b63dbaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":297},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d1bb614da34996bb5e9c41aaeb7e0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":297},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"c2ec63a8ad314dcc927058fc4e436ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":328},
            "size":{
              "width":181,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f940602e7446cc90837501092fcd11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":328},
                "size":{
                  "width":181,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8aaa42ee224447895ac7226440803af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":396},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efd2d5b8641a4b4b9b0e83a27a2ea055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":396},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"0a936c1778a044afbe2817d927fc4d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":37,
              "y":427},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f717e99616241e996e0c1251122224a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":37,
                  "y":427},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b296205d417241a3b0585d9556364503",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":495},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec6623e17d2d4165aeffd192cdf53c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":495},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"67ee3e8f0ee543afa6a0e8df750833e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":37,
              "y":526},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dbf140167d14401b42b8cbb5da06e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":37,
                  "y":526},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65dc2d52797e42589ed996fbeb8aabdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":526},
            "size":{
              "width":253,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaaca31be03347a3bb19714da2ec5b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":526},
                "size":{
                  "width":253,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93f5b8a79c84496fa544339cae8b31ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":594},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"981b302202ff41cea42a60083c3a6122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":594},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是/u12.png"}},
{
          "id":"2e96d34979da4ee48a285e08117c9135",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":37,
              "y":625},
            "size":{
              "width":73,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d091fc0a41f4e85877ef0a90bba338d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":37,
                  "y":625},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d48751ca2a3142d19dfa0965d655be25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":625},
            "size":{
              "width":253,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d87d4a4b12436c83ee82e4959ef473",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":625},
                "size":{
                  "width":253,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b23a2ce72d7495c87ea0b7b592d8cc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":20,
              "y":914},
            "size":{
              "width":640,
              "height":242}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a401efd48684fd9817a560f5f181d95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":20,
                  "y":914},
                "size":{
                  "width":640,
                  "height":242}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/省份/u38.png"}},
{
          "id":"f629e575b3a94886b4478ebf0cd42d8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":913.999938964844},
            "size":{
              "width":640,
              "height":246}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc15b7ab1fbb465888698f863114303f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":913.999938964844},
                "size":{
                  "width":640,
                  "height":246}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/省份/u40.png"}},
{
          "id":"65866984d3df44f3a798f15da2de35c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":1016.99993896484},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2af547e0d5be4fa29c91c3fce147f49e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":1016.99993896484},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93e01c4d02e7414cb63c7ab618f2ddb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":292,
              "y":1016.99993896484},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecf22173da3644e48fe2c2753193813c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":292,
                  "y":1016.99993896484},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40cc5b794c7245c8b1d00a023efed165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":534,
              "y":1016.99993896484},
            "size":{
              "width":103,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7661597a1ff740529827a74e35c422f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":534,
                  "y":1016.99993896484},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb5c9fc9e0214747b2958cb6ba4f6cb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":63,
              "y":943.999938964844},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"977a2f2b102448719e7bb3e1ed9b9f22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":63,
                  "y":943.999938964844},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddab75f2fece43a5a256e3dd9e146c3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":307,
              "y":943.999938964844},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a43e3ceca94095838309e95e6b6caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":307,
                  "y":943.999938964844},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f2730345fea477882d4dc4614667902",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":541,
              "y":943.999938964844},
            "size":{
              "width":103,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e11d54a78649a7bcd98e1142b893e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":541,
                  "y":943.999938964844},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9eabf707440b4a5da80384252cc612b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":63,
              "y":1092},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8a2ebf563fc4eb49d9673bbd3d9acd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":63,
                  "y":1092},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdea5df106d4467aaaaaa58d8e6287b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":307,
              "y":1092},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04cd4520716c46a8b41f6cf153b68877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":307,
                  "y":1092},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae264c6dd63140f5a042d2db2634c144",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"32px",
            "fontWeight":"200",
            "location":{
              "x":541,
              "y":1092},
            "size":{
              "width":103,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d825af653f8c4fb7a7e51fb4f2093625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"32px",
                "fontWeight":"200",
                "location":{
                  "x":541,
                  "y":1092},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5701c0fd7acf4c31b938475af8881e19",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":342},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/省份/u60_line.png"}},
{
          "id":"10c3467ad94445cf87c9b3de56ee5870",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":534},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/省份/u60_line.png"}},
{
          "id":"e1047ebdc2f641798ff55185276c9359",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":632},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/省份/u60_line.png"}},
{
          "id":"1db21e5081914d44ad5048638ad51eb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":730,
              "y":551},
            "size":{
              "width":300,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecbdddc35d334b49af7070735a430536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":730,
                  "y":551},
                "size":{
                  "width":300,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5da8a919b42f4bb7a5d74d2abe411154",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":37,
              "y":328},
            "size":{
              "width":181,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19803241d2374fd1bdf2817f21a98ddd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":37,
                  "y":328},
                "size":{
                  "width":181,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46ea7d77079a44fb9057b7d33254dbc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"36px",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":427},
            "size":{
              "width":181,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df68dbf5073144a7981f6e50edd7fa0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"36px",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":427},
                "size":{
                  "width":181,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9ef6a6d096924dc18bfc013248f25680":{
      "scriptId":"u0"},
    "f3847e87fa3d415aadb2ceb8064d4965":{
      "scriptId":"u1"},
    "cd9ac50d1bf244f29359fc53da4ae705":{
      "scriptId":"u2"},
    "00094dfd4c094b878f9d7bc860d9c6c9":{
      "scriptId":"u3"},
    "5e166351e68b4b5fa6338283b44dddbd":{
      "scriptId":"u4"},
    "cfa1f97d4ed74cbe9114002d453f083b":{
      "scriptId":"u5"},
    "c3570e13166a4a7da30ca1d37d4674d4":{
      "scriptId":"u6"},
    "a81d3f880dfc48a2ba26e8025bf277f2":{
      "scriptId":"u7"},
    "bbebe60d4c394293865abd8139564ad8":{
      "scriptId":"u8"},
    "7e79db2875dc4977813b3273e68e7a0a":{
      "scriptId":"u9"},
    "75e6addffb5944e98b5f23093f0a0a4d":{
      "scriptId":"u10"},
    "2fd3be60c8264457a0c88a6b9d65454b":{
      "scriptId":"u11"},
    "c162c6db6fee4589b8428cb188a99b83":{
      "scriptId":"u12"},
    "4f92e1407b8b47ef8694d3a319b1b1b0":{
      "scriptId":"u13"},
    "797e53cc066c4ae78ce0bd259fd62068":{
      "scriptId":"u14"},
    "b5dc5a3e93ce4b13a7e9d304ab606a1d":{
      "scriptId":"u15"},
    "2a835654029940c0af4b61e740dd3e74":{
      "scriptId":"u16"},
    "3f32fcb6fc754305b4fe37ac78902d24":{
      "scriptId":"u17"},
    "ed311f2e7a5c4231aa9626524b63dbaa":{
      "scriptId":"u18"},
    "c3d1bb614da34996bb5e9c41aaeb7e0f":{
      "scriptId":"u19"},
    "c2ec63a8ad314dcc927058fc4e436ec7":{
      "scriptId":"u20"},
    "55f940602e7446cc90837501092fcd11":{
      "scriptId":"u21"},
    "d8aaa42ee224447895ac7226440803af":{
      "scriptId":"u22"},
    "efd2d5b8641a4b4b9b0e83a27a2ea055":{
      "scriptId":"u23"},
    "0a936c1778a044afbe2817d927fc4d83":{
      "scriptId":"u24"},
    "4f717e99616241e996e0c1251122224a":{
      "scriptId":"u25"},
    "b296205d417241a3b0585d9556364503":{
      "scriptId":"u26"},
    "ec6623e17d2d4165aeffd192cdf53c55":{
      "scriptId":"u27"},
    "67ee3e8f0ee543afa6a0e8df750833e7":{
      "scriptId":"u28"},
    "8dbf140167d14401b42b8cbb5da06e38":{
      "scriptId":"u29"},
    "65dc2d52797e42589ed996fbeb8aabdc":{
      "scriptId":"u30"},
    "aaaca31be03347a3bb19714da2ec5b3a":{
      "scriptId":"u31"},
    "93f5b8a79c84496fa544339cae8b31ac":{
      "scriptId":"u32"},
    "981b302202ff41cea42a60083c3a6122":{
      "scriptId":"u33"},
    "2e96d34979da4ee48a285e08117c9135":{
      "scriptId":"u34"},
    "0d091fc0a41f4e85877ef0a90bba338d":{
      "scriptId":"u35"},
    "d48751ca2a3142d19dfa0965d655be25":{
      "scriptId":"u36"},
    "c1d87d4a4b12436c83ee82e4959ef473":{
      "scriptId":"u37"},
    "7b23a2ce72d7495c87ea0b7b592d8cc8":{
      "scriptId":"u38"},
    "6a401efd48684fd9817a560f5f181d95":{
      "scriptId":"u39"},
    "f629e575b3a94886b4478ebf0cd42d8b":{
      "scriptId":"u40"},
    "fc15b7ab1fbb465888698f863114303f":{
      "scriptId":"u41"},
    "65866984d3df44f3a798f15da2de35c1":{
      "scriptId":"u42"},
    "2af547e0d5be4fa29c91c3fce147f49e":{
      "scriptId":"u43"},
    "93e01c4d02e7414cb63c7ab618f2ddb0":{
      "scriptId":"u44"},
    "ecf22173da3644e48fe2c2753193813c":{
      "scriptId":"u45"},
    "40cc5b794c7245c8b1d00a023efed165":{
      "scriptId":"u46"},
    "7661597a1ff740529827a74e35c422f4":{
      "scriptId":"u47"},
    "eb5c9fc9e0214747b2958cb6ba4f6cb9":{
      "scriptId":"u48"},
    "977a2f2b102448719e7bb3e1ed9b9f22":{
      "scriptId":"u49"},
    "ddab75f2fece43a5a256e3dd9e146c3a":{
      "scriptId":"u50"},
    "a6a43e3ceca94095838309e95e6b6caa":{
      "scriptId":"u51"},
    "1f2730345fea477882d4dc4614667902":{
      "scriptId":"u52"},
    "a4e11d54a78649a7bcd98e1142b893e3":{
      "scriptId":"u53"},
    "9eabf707440b4a5da80384252cc612b9":{
      "scriptId":"u54"},
    "e8a2ebf563fc4eb49d9673bbd3d9acd7":{
      "scriptId":"u55"},
    "bdea5df106d4467aaaaaa58d8e6287b5":{
      "scriptId":"u56"},
    "04cd4520716c46a8b41f6cf153b68877":{
      "scriptId":"u57"},
    "ae264c6dd63140f5a042d2db2634c144":{
      "scriptId":"u58"},
    "d825af653f8c4fb7a7e51fb4f2093625":{
      "scriptId":"u59"},
    "5701c0fd7acf4c31b938475af8881e19":{
      "scriptId":"u60"},
    "10c3467ad94445cf87c9b3de56ee5870":{
      "scriptId":"u61"},
    "e1047ebdc2f641798ff55185276c9359":{
      "scriptId":"u62"},
    "1db21e5081914d44ad5048638ad51eb7":{
      "scriptId":"u63"},
    "ecbdddc35d334b49af7070735a430536":{
      "scriptId":"u64"},
    "5da8a919b42f4bb7a5d74d2abe411154":{
      "scriptId":"u65"},
    "19803241d2374fd1bdf2817f21a98ddd":{
      "scriptId":"u66"},
    "46ea7d77079a44fb9057b7d33254dbc8":{
      "scriptId":"u67"},
    "df68dbf5073144a7981f6e50edd7fa0e":{
      "scriptId":"u68"}}});